### ISSUE TITLE
nmake weirdness. anyone seen this?

### ISSUE THREAD

**Issue by g40** [wingtk/gvsbuild#1002]
`NMAKE : fatal error U1065: invalid option '-'`

I can reduce this to just trying to build zlib on its own. In order to see if something was amiss with nmake I added a couple of commands to be executed prior to the actual make stage. These can be seen in the log file extract below. 

```
2023-07-04 16:00:37   running which nmake, cwd=r:\src\gtk\zlib_release\build\x64\release\zlib, path+=None
    /r/vs2022/VC/Tools/MSVC/14.36.32532/bin/HostX64/x64/nmake
2023-07-04 16:00:38   running nmake /help, cwd=r:\src\gtk\zlib_release\build\x64\release\zlib, path+=None
    Microsoft (R) Program Maintenance Utility Version 14.36.32532.0
    Copyright (C) Microsoft Corporation.  All rights reserved.
    NMAKE : fatal error U1065: invalid option '-'
    Stop.
```
```
Building project zlib (1.2.13)
Microsoft (R) Program Maintenance Utility Version 14.36.32532.0
Copyright (C) Microsoft Corporation.  All rights reserved.
NMAKE : fatal error U1065: invalid option '-'
Stop.
Traceback (most recent call last):
  File "r:\src\gtk\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 525, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "r:\src\gtk\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 661, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "r:\src\gtk\gvsbuild\.venv\Lib\site-packages\gvsbuild\projects\zlib.py", line 56, in build
    self.exec_vs("nmake /help")
  File "r:\src\gtk\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\base_project.py", line 195, in exec_vs
    self.builder.exec_vs(
  File "r:\src\gtk\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 935, in exec_vs
    self.__execute(
  File "r:\src\gtk\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 1020, in __execute
    res = subprocess.run(
          ^^^^^^^^^^^^^^^
  File "R:\apps\python\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'nmake /help' returned non-zero exit status 2.
Error: zlib build failed
```

**Comment by g40** [comment]
When nmake is called the environment has the following variable set. This macro seems to be expanded by nmake!

```
'MAKEFLAGS': ' -- CONFIG=debug PROJECT=zlib'
```

**Comment by g40** [comment]
It's a product of passing command line macro definitions to `make`! So shot by my own code.

Avoid this sort of thing: ` make gvsbuild PROJECT=zlib CONFIG=debug`
Just do this: ` make gvsbuild ` with the `makefile` modified accordingly. 

For any future readers, there is a hack using gnu `env` to unset variables defined in the current enviornment but this does not play nicely with nmake
