### ISSUE TITLE
build gtk4 error

### ISSUE THREAD

**Issue by FynnFbc** [wingtk/gvsbuild#1093]
inja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\admin\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 529, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 665, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\Users\admin\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\projects\gtk.py", line 153, in build
    Meson.build(
  File "C:\Users\admin\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_builders.py", line 58, in build
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "C:\Users\admin\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 987, in exec_ninja
    self.__execute(
  File "C:\Users\admin\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 1043, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Program Files\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: gtk4 build failed

![image](https://github.com/wingtk/gvsbuild/assets/32776949/df6a4e23-b507-4255-9d18-a1187b6b02b4)

**Comment by danyeaw** [comment]
Hi @FynnFbc, is this the same issue as https://github.com/wingtk/gvsbuild/issues/1081?

**Comment by FynnFbc** [comment]
The problem is different, I failed to install gtk4, but I successfully installed ninja in python

**Comment by Clouud9** [comment]
> Can you translate the GTK build errors? If you switch your computer to English, are you still getting the errors?

I'm still getting these errors over a year later, and my PC is English.

**Comment by danyeaw** [comment]
Hi @Clouud9, could you please provide more information about:

1. The version of Windows you are using
2. How you installed Gvsbuild
3. What command you ran
4. What error messages you got

We run Gvsbuild on CI to build GTK4 with every change committed. So we need to try to pinpoint what about your computer or set up is different so that we can reproduce it and fix the issue.
