### ISSUE TITLE
pkgconf fails to build

### ISSUE THREAD

**Issue by Flamarine** [wingtk/gvsbuild#1104]
Log:
```plaintext
Build type is Configuration.debug_optimized
Cleaning up the build environment
Checking msys tool
Using C:\tools\msys64 for msys installation
Checking Msvc tool

Visual Studio installation(s) found:
    Visual Studio 生成工具 2022 @ C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    Visual Studio Community 2022 @ C:\Program Files\Microsoft Visual Studio\2022\Community

Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
Downloading packages
Building project ninja (1.11.1)
Building project meson (1.2.2)
(tar) Exporting pkgconf
Building project pkgconf (2.0.3)
[0/1] Installing files.
FAILED: meson-internal__install
"C:\Users\Willi\.local\pipx\venvs\gvsbuild\Scripts\python.exe" "C:\gtk-build\tools\meson-1.2.1\meson.py" "install" "--no-rebuild"
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 663, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\projects\pkgconf.py", line 37, in build
    Meson.build(self)
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\base_builders.py", line 56, in build
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 985, in exec_ninja
    self.__execute(
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 1041, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: pkgconf build failed
```
Built on Windows 11

**Comment by Flamarine** [comment]
nvm, got it working with `--clean`.
