### ISSUE TITLE
Build failed generating gtk/Gdk-4.0.gir

### ISSUE THREAD

**Issue by ed10vi** [wingtk/gvsbuild#1115]
Hello. I'm trying to build GTK inside a Windows Container based on an image generated with this Dockerfile:

```dockerfile
# escape=`

FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019

# Reset the shell.
SHELL ["cmd", "/S", "/C"]

# Download channel for fixed install.
ARG CHANNEL_URL=https://aka.ms/vs/17/release/channel
ADD ${CHANNEL_URL} C:\TEMP\VisualStudio.chman

# Download and install Build Tools for Visual Studio 2022 for native desktop workload.
ADD https://aka.ms/vs/17/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe
RUN start /w C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --channelUri C:\TEMP\VisualStudio.chman `
    --installChannelUri C:\TEMP\VisualStudio.chman `
    --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended `
    --add Microsoft.VisualStudio.Component.VC.CLI.Support `
    --add Microsoft.VisualStudio.Component.VC.Modules.x86.x64 `
    --installPath "%programfiles(x86)%\Microsoft Visual Studio\2022\BuildTools"

RUN rmdir /s /q C:\TEMP
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
```

I'm following this steps:

```ps
certutil -generateSSTFromWU roots.sst
certutil -addstore -f root roots.sst
Invoke-WebRequest -OutFile python-installer.exe https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe
.\python-installer.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 Include_doc=0
$env:PATH = $env:PATH+";${env:ProgramFiles}\Python312;${env:ProgramFiles}\Python312\Scripts;${env:AppData}\Python\Python312;${env:AppData}\Python\Python312\Scripts"
Invoke-WebRequest -OutFile msys2-installer.exe https://github.com/msys2/msys2-installer/releases/download/2023-07-18/msys2-base-x86_64-20230718.sfx.exe
.\msys2-installer.exe -y -oC:\
$env:PATH = $env:PATH+";C:\msys64\usr\bin"
bash -lc 'pacman --noconfirm -Syu'
bash -lc 'pacman --noconfirm -S git'
python -m pip install --upgrade pip
python -m pip install --user setuptools
New-Item -ItemType Directory -Path C:\gtk-build -Name github
cd C:\gtk-build\github\
git clone https://github.com/wingtk/gvsbuild.git
cd .\gvsbuild\
python -m pip install --user .
gvsbuild build gtk4 --enable-gi --configuration release --platform x64 --vs-install-path "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools"
```

And I'm getting the following error:
```
[704/1165] Generating gtk/Gdk-4.0.gir with a custom command (wrapped by meson to set PATH, to set env)
FAILED: gtk/Gdk-4.0.gir
"C:\Program Files\Python312\python.exe" "C:\gtk-build\tools\meson-1.2.3\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\gtk4\_gvsbuild-meson\meson-private\meson_exe_python.exe_0b9f9d25fb158b73940bf50edba99293b2495e91.dat"
while executing ['C:\\Program Files\\Python312\\python.exe', 'C:/gtk-build/gtk/x64/release/bin/../bin/g-ir-scanner', '--quiet', '--no-libtool', '--namespace=Gdk', '--nsversion=4.0', '--warn-all', '--output', 'gtk/Gdk-4.0.gir', '--c-include=gdk/gdk.h', '-DGTK_COMPILATION', '--quiet', '-IC:/gtk-build/build/x64/release/gtk4/gtk', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gtk', '-IC:/gtk-build/build/x64/release/gtk4/.', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/.', '-IC:/gtk-build/build/x64/release/gtk4/gdk/.', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gdk/.', '-IC:/gtk-build/build/x64/release/gtk4/gsk', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gsk', '-IC:/gtk-build/build/x64/release/gtk4/gtk', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gtk', '-IC:/gtk-build/build/x64/release/gtk4/gdk/x11', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gdk/x11', '-IC:/gtk-build/build/x64/release/gtk4/gdk/.', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gdk/.', '--filelist=C:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gtk/gtk-4-1.dll.p/Gdk_4.0_gir_filelist', '--include=cairo-1.0', '--include=Gio-2.0', '--include=GdkPixbuf-2.0', '--include=Pango-1.0', '--include=PangoCairo-1.0', '--symbol-prefix=gdk', '--identifier-prefix=Gdk', '--pkg-export=gtk4', '--cflags-begin', '-DG_LOG_USE_STRUCTURED=1', '-DGLIB_DISABLE_DEPRECATION_WARNINGS', '-DGTK_VERSION="4.12.3"', '-D_GNU_SOURCE', '-DG_DISABLE_CAST_CHECKS', '-DG_DISABLE_ASSERT', '-D_USE_MATH_DEFINES', '-IC:/gtk-build/build/x64/release/gtk4/.', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/.', '-IC:/gtk-build/build/x64/release/gtk4/gdk/.', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gdk/.', '-IC:/gtk-build/build/x64/release/gtk4/gsk', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gsk', '-IC:/gtk-build/build/x64/release/gtk4/gtk', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gtk', '-IC:/gtk-build/build/x64/release/gtk4/gdk/x11', '-IC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gdk/x11', '-IC:/gtk-build/gtk/x64/release/bin/../include', '-IC:/gtk-build/gtk/x64/release/bin/../include/glib-2.0', '-IC:/gtk-build/gtk/x64/release/bin/../lib/glib-2.0/include', '-IC:/gtk-build/gtk/x64/release/bin/../include/gio-win32-2.0', '-IC:/gtk-build/gtk/x64/release/bin/../include/pango-1.0', '-IC:/gtk-build/gtk/x64/release/bin/../include/freetype2', '-IC:/gtk-build/gtk/x64/release/bin/../include/harfbuzz', '-IC:/gtk-build/gtk/x64/release/bin/../include/cairo', '-IC:/gtk-build/gtk/x64/release/bin/../include/libpng16', '-IC:/gtk-build/gtk/x64/release/bin/../include/pixman-1', '-IC:/gtk-build/gtk/x64/release/bin/../include/fribidi', '-IC:/gtk-build/gtk/x64/release/bin/../include/gdk-pixbuf-2.0', '-IC:/gtk-build/gtk/x64/release/bin/../include/graphene-1.0', '-IC:/gtk-build/gtk/x64/release/bin/../lib/graphene-1.0/include', '-IC:/gtk-build/gtk/x64/release/bin/../include/gobject-introspection-1.0', '--cflags-end', '--add-include-path=C:/gtk-build/gtk/x64/release/bin/../share/gir-1.0', '-LC:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/gtk', '--library', 'gtk-4', '-LC:/gtk-build/gtk/x64/release/bin/../lib', '-LC:/gtk-build/gtk/x64/release/bin/../lib', '--extra-library=gmodule-2.0', '--extra-library=glib-2.0', '--extra-library=intl', '--extra-library=gobject-2.0', '--extra-library=gio-2.0', '--extra-library=pangocairo-1.0', '--extra-library=pango-1.0', '--extra-library=harfbuzz', '--extra-library=cairo', '--extra-library=fribidi', '--extra-library=cairo-gobject', '--extra-library=gdk_pixbuf-2.0', '--extra-library=epoxy', '--extra-library=graphene-1.0', '--extra-library=pangowin32-1.0', '--extra-library=advapi32', '--extra-library=comctl32', '--extra-library=crypt32', '--extra-library=dwmapi', '--extra-library=imm32', '--extra-library=setupapi', '--extra-library=winmm', '--extra-library=libpng16', '--extra-library=tiff', '--extra-library=jpeg', '--extra-library=hid', '--extra-library=opengl32', '--extra-library=cairo-script-interpreter', '--extra-library=girepository-1.0', '--sources-top-dirs', 'C:/gtk-build/build/x64/release/gtk4/', '--sources-top-dirs', 'C:/gtk-build/build/x64/release/gtk4/_gvsbuild-meson/']
--- stdout ---
Gdk-4.0.c
Microsoft (R) Incremental Linker Version 14.37.32825.0
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library C:\gtk-build\build\x64\release\gtk4\_gvsbuild-meson\tmp-introspectcqyjftlp\Gdk-4.0.lib and object C:\gtk-build\build\x64\release\gtk4\_gvsbuild-meson\tmp-introspectcqyjftlp\Gdk-4.0.exp

--- stderr ---
Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32825 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

g-ir-cpp-jq75ysxs.c
C:\gtk-build\gtk\x64\release\include\glib-2.0\glib\gstring.h:193: syntax error, unexpected identifier in '__forceinline' at '__forceinline'
C:\gtk-build\gtk\x64\release\include\glib-2.0\glib\gstring.h:212: syntax error, unexpected identifier in '__forceinline' at '__forceinline'
C:\gtk-build\gtk\x64\release\include\glib-2.0\glib\gstring.h:249: syntax error, unexpected identifier in '__forceinline' at '__forceinline'
Command '['C:\\gtk-build\\build\\x64\\release\\gtk4\\_gvsbuild-meson\\tmp-introspectcqyjftlp\\Gdk-4.0.exe', '--introspect-dump=C:\\gtk-build\\build\\x64\\release\\gtk4\\_gvsbuild-meson\\tmp-introspectcqyjftlp\\functions.txt,C:\\gtk-build\\build\\x64\\release\\gtk4\\_gvsbuild-meson\\tmp-introspectcqyjftlp\\dump.xml']' returned non-zero exit status 3221225781.

[706/1165] Compiling C object tools/gtk4-rendernode-tool.exe.p/gtk-rendernode-tool-show.c.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last): 
  File "C:\Users\ContainerAdministrator\AppData\Roaming\Python\Python312\site-packages\gvsbuild\utils\builder.py", line 527, in build 
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ContainerAdministrator\AppData\Roaming\Python\Python312\site-packages\gvsbuild\utils\builder.py", line 663, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\Users\ContainerAdministrator\AppData\Roaming\Python\Python312\site-packages\gvsbuild\projects\gtk.py", line 151, in build       
    Meson.build(
  File "C:\Users\ContainerAdministrator\AppData\Roaming\Python\Python312\site-packages\gvsbuild\utils\base_builders.py", line 56, in build 
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "C:\Users\ContainerAdministrator\AppData\Roaming\Python\Python312\site-packages\gvsbuild\utils\builder.py", line 985, in exec_ninja 
    self.__execute(
  File "C:\Users\ContainerAdministrator\AppData\Roaming\Python\Python312\site-packages\gvsbuild\utils\builder.py", line 1041, in __execute 
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Program Files\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: gtk4 build failed
```

Without `--enable-gi` works fine.
What am I doing wrong?

**Comment by danyeaw** [comment]
Hi @ed10vi, I haven't tested your setup, but the thing that stands out to me is that you are using MSYS2 git instead of Git for Windows. Have you tried using Git for Windows?

**Comment by ed10vi** [comment]
I tried this:

```ps
certutil -generateSSTFromWU roots.sst
certutil -addstore -f root roots.sst
Invoke-WebRequest -OutFile python-installer.exe https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe
.\python-installer.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 Include_doc=0
$env:PATH = $env:PATH+";${env:ProgramFiles}\Python312;${env:ProgramFiles}\Python312\Scripts;${env:AppData}\Python\Python312;${env:AppData}\Python\Python312\Scripts"
Invoke-WebRequest -OutFile msys2-installer.exe https://github.com/msys2/msys2-installer/releases/download/2023-07-18/msys2-base-x86_64-20230718.sfx.exe
.\msys2-installer.exe -y -oC:\
$env:PATH = $env:PATH+";C:\msys64\usr\bin"
bash -lc 'pacman --noconfirm -Syu'
Invoke-WebRequest -OutFile min-git.zip https://github.com/git-for-windows/git/releases/download/v2.42.0.windows.2/MinGit-2.42.0.2-64-bit.zip
Expand-Archive min-git.zip -DestinationPath "${env:ProgramFiles}\git"
$env:PATH = $env:PATH+";${env:ProgramFiles}\git\cmd"
$gitconfig = Get-Content "${env:ProgramFiles}\git\etc\gitconfig"
Set-Content "${env:ProgramFiles}\git\etc\gitconfig" $gitconfig[0..($gitconfig.Count-3)]
python -m pip install --upgrade pip
python -m pip install --user setuptools
New-Item -ItemType Directory -Path C:\gtk-build -Name github
cd C:\gtk-build\github\
git clone https://github.com/wingtk/gvsbuild.git
cd .\gvsbuild\
python -m pip install --user .
gvsbuild build gtk4 --enable-gi --configuration release --platform x64 --vs-install-path "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools"
```

Same error
