### ISSUE TITLE
[libadwaita] "ERROR: Program 'sh' not found or not executable"

### ISSUE THREAD

**Issue by mitchhentges** [wingtk/gvsbuild#1133]
I'm using `gvsbuild==2023.11.0` with Python 3.11.4.

The command I ran was `gvsbuild build gtk4 adwaita-icon-theme libadwaita`

```
demo\data\meson.build:20:5: ERROR: Program 'sh' not found or not executable

A full log can be found at C:\gtk-build\build\x64\release\libadwaita\_gvsbuild-meson\meson-logs\meson-log.txt
Traceback (most recent call last):
  File "C:\Users\Mitch\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mitch\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 663, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\Users\Mitch\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\projects\libadwaita.py", line 54, in build
    Meson.build(self)
  File "C:\Users\Mitch\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_builders.py", line 47, in build
    self._setup_meson_and_ninja(ninja_build, meson_params, add_path)
  File "C:\Users\Mitch\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_builders.py", line 79, in _setup_meson_and_ninja
    self.exec_vs(cmd, add_path=add_path)
  File "C:\Users\Mitch\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_project.py", line 192, in exec_vs
    self.builder.exec_vs(
  File "C:\Users\Mitch\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 937, in exec_vs
    self.__execute(
  File "C:\Users\Mitch\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 1041, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\Mitch\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\Mitch\.local\pipx\venvs\gvsbuild\Scripts\python.exe C:\gtk-build\tools\meson-1.2.3\meson.py setup C:\gtk-build\build\x64\release\libadwaita C:\gtk-build\build\x64\release\libadwaita\_gvsbuild-meson --prefix C:\gtk-build\gtk\x64\release -Dintrospection=disabled -Dgtk_doc=false -Dvapi=false --buildtype debugoptimized' returned non-zero exit status 1.
```

[`meson-log.txt`](https://github.com/wingtk/gvsbuild/files/13326231/meson-log.txt)

Running `which sh`:

```
Mitch@mitch-windows MINGW64 ~
$ which sh
/usr/bin/sh
```

-----

I'm not sure how `gvsbuild` isolates its build environments, so I'll need your guidance on what other useful information I can show here.

**Comment by mitchhentges** [comment]
I'm able to reproduce this on two separate machines, so I'm hoping that this isn't due to user error.
However, I'm surprised that CI isn't encountering this.

Looking at the logs for the PR that bumped `libadwaita` to `1.4.0`, [here is where it looks for `sh` and finds it in MSYS2](https://github.com/wingtk/gvsbuild/actions/runs/6216244593/job/16869906445#step:11:25405).

This is strange, considering [that the `Libadwaita` class doesn't depend on `msys2`](https://github.com/wingtk/gvsbuild/blob/main/gvsbuild/projects/libadwaita.py#L32-L38) (I'm comparing it to `ffmpeg`, which explicitly depends on MSYS2 [here](https://github.com/wingtk/gvsbuild/blob/main/gvsbuild/projects/ffmpeg.py#L32) and [here](https://github.com/wingtk/gvsbuild/blob/main/gvsbuild/projects/ffmpeg.py#L52)).
