### ISSUE TITLE
Error while building Glib

### ISSUE THREAD

**Issue by Lynnesbian** [wingtk/gvsbuild#1189]
When building Glib, the process stops at the following step:
`[0/15] Generating gio/tests/digit_test_resources.h with a custom command (wrapped by meson to set PATH)`

A dialogue box then pops up, reading:
>The procedure entry point g_timeout_add_seconds_once could not be located in the dynamic link library C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gio-2.0-0.dll. 

This dialogue, once closed, appears seven more times, and then the build process exits in failure with the following output:

<details>
<summary>Build output</summary>

```
FAILED: gio/tests/test.gresource
"C:\Users\theco\.local\pipx\venvs\gvsbuild\Scripts\python.exe" "C:\gtk-build\tools\meson-1.2.3\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_94f1b75b9d58c0f70108bcd4a087cb0cdd2d0cfa.dat"
while executing ['C:\\gtk-build\\build\\x64\\release\\glib\\_gvsbuild-meson\\gio\\glib-compile-resources.exe', '--compiler=msvc', '--target=gio/tests/test.gresource', '--sourcedir=C:/gtk-build/build/x64/release/glib/gio/tests', '--sourcedir=C:/gtk-build/build/x64/release/glib/_gvsbuild-meson/gio/tests', '--internal', '../gio/tests/test.gresource.xml']
--- stdout ---

--- stderr ---

[2/15] Generating gio/tests/plugin-resources.c with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/plugin-resources.c
"C:\Users\theco\.local\pipx\venvs\gvsbuild\Scripts\python.exe" "C:\gtk-build\tools\meson-1.2.3\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_97b81ecc61be5a9f78377590cf1da6e903418cb3.dat"
while executing ['C:\\gtk-build\\build\\x64\\release\\glib\\_gvsbuild-meson\\gio\\glib-compile-resources.exe', '--compiler=msvc', '--target=gio/tests/plugin-resources.c', '--sourcedir=C:/gtk-build/build/x64/release/glib/gio/tests', '--internal', '--generate-source', '--c-name', '_g_plugin', '../gio/tests/test4.gresource.xml']
--- stdout ---

--- stderr ---

[3/15] Generating gio/tests/test_resources.c with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/test_resources.c
"C:\Users\theco\.local\pipx\venvs\gvsbuild\Scripts\python.exe" "C:\gtk-build\tools\meson-1.2.3\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_54e5f48f8737da87d8c1800550bc01136ed29706.dat"
while executing ['C:\\gtk-build\\build\\x64\\release\\glib\\_gvsbuild-meson\\gio\\glib-compile-resources.exe', '--compiler=msvc', '--target=gio/tests/test_resources.c', '--sourcedir=C:/gtk-build/build/x64/release/glib/gio/tests', '--sourcedir=C:/gtk-build/build/x64/release/glib/_gvsbuild-meson/gio/tests', '--internal', '--generate-source', '--c-name', '_g_test1', '../gio/tests/test2.gresource.xml']
--- stdout ---

--- stderr ---

[4/15] Generating gio/tests/digit_test_resources.c with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/digit_test_resources.c
"C:\Users\theco\.local\pipx\venvs\gvsbuild\Scripts\python.exe" "C:\gtk-build\tools\meson-1.2.3\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_48d746b50717d5d12717226362b857e068aa8b05.dat"
while executing ['C:\\gtk-build\\build\\x64\\release\\glib\\_gvsbuild-meson\\gio\\glib-compile-resources.exe', '--compiler=msvc', '--target=gio/tests/digit_test_resources.c', '--sourcedir=C:/gtk-build/build/x64/release/glib/gio/tests', '--sourcedir=C:/gtk-build/build/x64/release/glib/_gvsbuild-meson/gio/tests', '--internal', '--generate-source', '--manual-register', '../gio/tests/111_digit_test.gresource.xml']
--- stdout ---

--- stderr ---

[5/15] Generating gio/tests/test_resources2.c with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/test_resources2.c
"C:\Users\theco\.local\pipx\venvs\gvsbuild\Scripts\python.exe" "C:\gtk-build\tools\meson-1.2.3\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_451f33be8fbb22f7f69397f5bec1851da4118513.dat"
while executing ['C:\\gtk-build\\build\\x64\\release\\glib\\_gvsbuild-meson\\gio\\glib-compile-resources.exe', '--compiler=msvc', '--target=gio/tests/test_resources2.c', '--sourcedir=C:/gtk-build/build/x64/release/glib/gio/tests', '--internal', '--generate', '--c-name', '_g_test2', '--manual-register', '../gio/tests/test3.gresource.xml']
--- stdout ---

--- stderr ---

[6/15] Generating gio/tests/digit_test_resources.h with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/digit_test_resources.h
"C:\Users\theco\.local\pipx\venvs\gvsbuild\Scripts\python.exe" "C:\gtk-build\tools\meson-1.2.3\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_0a88862b87428948f386bae168d5e046f23913fd.dat"
while executing ['C:\\gtk-build\\build\\x64\\release\\glib\\_gvsbuild-meson\\gio\\glib-compile-resources.exe', '--compiler=msvc', '--target=gio/tests/digit_test_resources.h', '--sourcedir=C:/gtk-build/build/x64/release/glib/gio/tests', '--internal', '--generate', '--manual-register', '../gio/tests/111_digit_test.gresource.xml']
--- stdout ---

--- stderr ---

[7/15] Generating gio/tests/test_resources2.h with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/test_resources2.h
"C:\Users\theco\.local\pipx\venvs\gvsbuild\Scripts\python.exe" "C:\gtk-build\tools\meson-1.2.3\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_dfae59d75c5df5e26e4f5683d21a51f3f77dcca4.dat"
while executing ['C:\\gtk-build\\build\\x64\\release\\glib\\_gvsbuild-meson\\gio\\glib-compile-resources.exe', '--compiler=msvc', '--target=gio/tests/test_resources2.h', '--sourcedir=C:/gtk-build/build/x64/release/glib/gio/tests', '--internal', '--generate', '--c-name', '_g_test2', '--manual-register', '../gio/tests/test3.gresource.xml']
--- stdout ---

--- stderr ---

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\theco\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theco\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 663, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\Users\theco\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\projects\glib.py", line 47, in build
    Meson.build(self)
  File "C:\Users\theco\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_builders.py", line 56, in build
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "C:\Users\theco\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 985, in exec_ninja
    self.__execute(
  File "C:\Users\theco\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 1041, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\theco\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: glib build failed
```
</details>

This occurs even when building with the `--clean` flag.

I am on Windows 11, using Visual Studio Community 2022.

**Comment by Lynnesbian** [comment]
Upgrading to the [latest release of gvsbuild](https://github.com/wingtk/gvsbuild/releases/tag/2023.12.0) has fixed this!

I briefly encountered a different compilation error in an unrelated part of the project, but `gvsbuild build --clean` fixed that.

Thank you for all the work you do on `gvsbuild`, and happy holidays!
