### ISSUE TITLE
GTK4 build fails

### ISSUE THREAD

**Issue by yashranjan1** [wingtk/gvsbuild#1305]
Hi! I couple of days ago I posted this issue #1297 and it was promptly fixed. Thank you so much for that, but now that i tried it again after updating gvsbuild, a different part of the build process failed.

Here are the logs:

```
Building project pcre2 (10.43)
[0/1] Installing files.Installing pcre2-8-0.dll to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-8.lib to C:\gtk-build\gtk\x64\release\lib
Installing pcre2-8-0.pdb to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-posix-3.dll to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-posix.lib to C:\gtk-build\gtk\x64\release\lib
Installing pcre2-posix-3.pdb to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-16-0.dll to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-16.lib to C:\gtk-build\gtk\x64\release\lib
Installing pcre2-16-0.pdb to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-32-0.dll to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-32.lib to C:\gtk-build\gtk\x64\release\lib
Installing pcre2-32-0.pdb to C:\gtk-build\gtk\x64\release\bin
Installing pcre2grep.exe to C:\gtk-build\gtk\x64\release\bin
Installing pcre2grep.pdb to C:\gtk-build\gtk\x64\release\bin
Installing C:\gtk-build\build\x64\release\pcre2\_gvsbuild-meson\pcre2.h to C:\gtk-build\gtk\x64\release\include
Installing C:\gtk-build\build\x64\release\pcre2\src/pcre2posix.h to C:\gtk-build\gtk\x64\release\include
Installing C:\gtk-build\build\x64\release\pcre2\_gvsbuild-meson\meson-private\libpcre2-8.pc to C:\gtk-build\gtk\x64\release\lib\pkgconfig
Installing C:\gtk-build\build\x64\release\pcre2\_gvsbuild-meson\meson-private\libpcre2-16.pc to C:\gtk-build\gtk\x64\release\lib\pkgconfig
Installing C:\gtk-build\build\x64\release\pcre2\_gvsbuild-meson\meson-private\libpcre2-32.pc to C:\gtk-build\gtk\x64\release\lib\pkgconfig

(tar) Exporting glib
Traceback (most recent call last):
  File "C:\Users\yashr\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashr\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 621, in __build_one
    proj.export()
  File "C:\Users\yashr\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_expanders.py", line 250, in export
    zipped_path.write(
  File "C:\Users\yashr\AppData\Local\Programs\Python\Python312\Lib\zipfile\__init__.py", line 1830, in write
    zinfo = ZipInfo.from_file(filename, arcname,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashr\AppData\Local\Programs\Python\Python312\Lib\zipfile\__init__.py", line 557, in from_file
    st = os.stat(filename)
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\gtk-build\\build\\x64\\release\\glib\\001-glib-package-installation-directory.patch'
Error: glib build failed
```

My version:
```
 ⚡Yash ❯❯ gvsbuild --version
gvsbuild v2024.3.1
```

**Comment by danyeaw** [comment]
Hi @yashranjan1, can you please try running the Gvsbuild build command with the `--from-scratch` option?

**Comment by yashranjan1** [comment]
Yes that worked, thank you so much for your help!
