### ISSUE TITLE
patch' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by MLLTex** [wingtk/gvsbuild#1358]
I followed the [guide](https://github.com/wingtk/gvsbuild) to build gtk3 or gtk4. Howerer, when i enter the`gvsbuild build gtk3`  command to build i get 'patch' is not recognised as an internal/external command, operable program or batch file' message

The traceback are followling,but It's ok when i use command `patch --version`. what happend ?
```
Traceback (most recent call last):
  File "C:\Users\22171\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\22171\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 662, in __build_one
    proj.patch()
  File "C:\Users\22171\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_project.py", line 438, in patch
    self.builder.exec_msys(
  File "C:\Users\22171\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 1009, in exec_msys
    self.__execute(
  File "C:\Users\22171\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 1041, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "F:\pythonOL\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['patch', '-p1', '-i', '0001-libpkgconf-add-defines-to-unbreak-build-with-VS2013.patch']' returned non-zero exit status 1.
Error: pkgconf build failed
```

```
PS C:\WINDOWS\system32> patch --version
patch 2.5.9
Copyright (C) 1988 Larry Wall
Copyright (C) 2003 Free Software Foundation, Inc.

This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of this program
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

written by Larry Wall and Paul Eggert
```

**Comment by MLLTex** [comment]
Its maybe the security software 's question .shut down the app please
