### ISSUE TITLE
Download failed with SSL error for some urls, e.g. libpng from prdownloads.sourceforge.net.

### ISSUE THREAD

**Issue by accel2k** [wingtk/gvsbuild#173]
Checked with python 3.4 - 3.6.

Traceback (most recent call last):
  File "c:\python\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\python\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\python\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\python\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\python\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\python\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "c:\python\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "c:\python\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "c:\python\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "c:\python\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\build.py", line 37, in <module>
    args.func(args)
  File "E:\gtk-build\github\gtk-win32\gvsbuild\utils\parser.py", line 105, in do_build
    builder.build(to_build)
  File "E:\gtk-build\github\gtk-win32\gvsbuild\utils\builder.py", line 177, in build
    if self.__prepare_build(projects):
  File "E:\gtk-build\github\gtk-win32\gvsbuild\utils\builder.py", line 210, in __prepare_build
    if self.__download_one(p):
  File "E:\gtk-build\github\gtk-win32\gvsbuild\utils\builder.py", line 346, in __download_one
    urllib.request.urlretrieve(proj.archive_url, proj.archive_file, reporthook=self.__download_progress)
  File "c:\python\lib\urllib\request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "c:\python\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\python\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "c:\python\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\python\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\python\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\python\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "c:\python\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\python\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\python\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\python\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\python\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\python\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\python\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

**Comment by nacho** [comment]
@muntyan reported the same problem but when I tried it worked properly.... Since we are verifying the hash of the downloaded files I think we could disable ssl and be done with the problem
