### ISSUE TITLE
error building gtk3: gtkdbusgenerated.h/.c not found

### ISSUE THREAD

**Issue by joe-92** [wingtk/gvsbuild#182]
Hello,
i'm trying to build gtk3, but the build process stops at the following point:
```
Building project gtk3
  Copying gdkconfig from gdkconfig.win32...
  gdk3-win32.vcxproj -> C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\Release\x64\bin\gdk3-win32.lib
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1189,5): warning MSB8012: TargetPath(C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\Release\x64\bin\gdk-3.dll) does not match the Linker's OutputFil
e property value (C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\Release\x64\bin\gdk-3-3.0.dll). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) pr
operty values match the value specified in %(Link.OutputFile). [C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\gdk-3.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1191,5): warning MSB8012: TargetName(gdk-3) does not match the Linker's OutputFile property value (gdk-3-3.0). This may cause your project to build incorr
ectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile). [C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\gdk-3.vcxproj]
     Creating library C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\Release\x64\bin\gdk-3.0.lib and object C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\Release\x64\bin\gdk-3.0.exp
  Generating code
  65 of 1700 functions ( 3.8%) were compiled, the rest were copied from previous compilation.
    0 functions were new in current compilation
    56 functions had inline decision re-evaluated but remain unchanged
  Finished generating code
  gdk-3.vcxproj -> C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\Release\x64\bin\gdk-3.dll
  gdk-3.vcxproj -> C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\Release\x64\bin\gdk-3-3.0.pdb (Full PDB)
  Generating GTK+ DBus Sources...
  The system cannot find the path specified.
  gtkaccessibility.c
  gtkimagecellaccessible.c
  gtkscaleaccessible.c
  gtkcolorsel.c
..\..\..\gtk\deprecated\gtkcolorsel.c(1202): warning C4267: 'initializing': conversion from 'size_t' to 'gint', possible loss of data [C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\gtk-3.vcxproj]
  gtkstock.c
..\..\..\gtk\deprecated\gtkstock.c(94): warning C4018: '<': signed/unsigned mismatch [C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\gtk-3.vcxproj]
  data-list.c
  strv-editor.c
  gtkactionbar.c
  gtkboxgadget.c
..\..\..\gtk\gtkboxgadget.c(662): warning C4018: '>=': signed/unsigned mismatch [C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\gtk-3.vcxproj]
  gtkcellrendererspin.c
  gtkcssanimation.c
  gtkcssimagegradient.c
  gtkcssparser.c
  gtkcsstransientnode.c
  gtkfilechooserdialog.c
  gtkgesturedrag.c
  gtkimcontext.c
..\..\..\gtk\gtkimcontext.c(655): warning C4267: '=': conversion from 'size_t' to 'gint', possible loss of data [C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\gtk-3.vcxproj]
  gtkmenubutton.c
  gtkmountoperation.c
..\..\..\gtk\gtkmountoperation.c(33): fatal error C1083: Cannot open include file: 'gtkdbusgenerated.h': No such file or directory [C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\gtk-3.vcxproj]
  gtknativedialog.c
  Generating Code...
  Compiling...
  gtkpagesetup.c
  gtkradiobutton.c
  gtkscale.c
  gtkstacksidebar.c
  gtktextdisplay.c
..\..\..\gtk\gtktextdisplay.c(961): warning C4018: '<': signed/unsigned mismatch [C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\gtk-3.vcxproj]
  gtktooltipwindow.c
  gtkwindowgroup.c
  gtkdbusgenerated.c
c1 : fatal error C1083: Cannot open source file: '..\..\..\gtk\gtkdbusgenerated.c': No such file or directory [C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\gtk-3.vcxproj]
  gtkimcontextime.c
  Generating Code...
  Generating code
  1 of 4 functions (25.0%) were compiled, the rest were copied from previous compilation.
    0 functions were new in current compilation
    1 functions had inline decision re-evaluated but remain unchanged
  Finished generating code
  gtk-encode-symbolic-svg.vcxproj -> C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\Release\x64\bin\gtk-encode-symbolic-svg.exe
  gtk-encode-symbolic-svg.vcxproj -> C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\Release\x64\bin\gtk-encode-symbolic-svg.pdb (Full PDB)
  Generating code
  0 of 51 functions ( 0.0%) were compiled, the rest were copied from previous compilation.
    0 functions were new in current compilation
    0 functions had inline decision re-evaluated but remain unchanged
  Finished generating code
  gtk-update-icon-cache.vcxproj -> C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\Release\x64\bin\gtk-update-icon-cache.exe
  gtk-update-icon-cache.vcxproj -> C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\Release\x64\bin\gtk-update-icon-cache.pdb (Full PDB)
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 188, in build
    self.__build_one(p)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 244, in __build_one
    proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 534, in build
    self.exec_msbuild(r'build\win32\vs%(vs_ver)s\gtk+.sln /p:GtkPostInstall=rem')
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 74, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 69, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 435, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 467, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python_3_4_4\lib\subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild build\win32\vs14\gtk+.sln /p:GtkPostInstall=rem /p:Configuration=release /nologo /p:Platform=x64 /p:PythonPath=C:\Python_3_4_4   /v:minimal' returned non-zero exit status 1
Error: gtk3 build failed
```

It looks like the files `gtkdbusgenerated.h` and `gtkdbusgenerated.c` are not created properly:
```
..\..\..\gtk\gtkmountoperation.c(33): fatal error C1083: Cannot open include file: 'gtkdbusgenerated.h': No such file or directory [C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\gtk-3.vcxproj]
c1 : fatal error C1083: Cannot open source file: '..\..\..\gtk\gtkdbusgenerated.c': No such file or directory [C:\gtk-build\build\x64\release\gtk3\build\win32\vs14\gtk-3.vcxproj]
```

I'm using Visual Studio 15 Enterprise, Python 3.4.4 and Windows 10.
Does anybody have an idea what's wrong?

**Comment by nacho** [comment]
GTK+ expects python to be in c:\python34, see https://github.com/wingtk/gvsbuild/blob/master/gtk3/build/win32/vs14/gtk3-version-paths.props#L15

**Comment by joe-92** [comment]
Thank you!
