### ISSUE TITLE
glib compile error

### ISSUE THREAD

**Issue by dbyoung720** [wingtk/gvsbuild#209]
compile bat:
```batch
set "CurrentCD=%~dp0"

set "Path=F:\Green\Language\Python\3.6.3;%Path%"

python %CurrentCD%build.py build -p x64 gtk3 --vs-ver="14" --vs-install-path="D:\Language\VS2015"  --msys-dir="F:\Green\Language\MSYS2"
```

Error:
```python
Traceback (most recent call last):
  File "G:\Source\gvsbuild\gvsbuild\utils\builder.py", line 311, in build
    self.__build_one(p)
  File "G:\Source\gvsbuild\gvsbuild\utils\builder.py", line 390, in __build_one
    proj.build()
  File "G:\Source\gvsbuild\gvsbuild\projects.py", line 378, in build
    self.exec_msbuild(r'win32\vs%(vs_ver)s\glib.sln', configuration=configuration)
  File "G:\Source\gvsbuild\gvsbuild\utils\base_project.py", line 76, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "G:\Source\gvsbuild\gvsbuild\utils\base_project.py", line 71, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "G:\Source\gvsbuild\gvsbuild\utils\builder.py", line 600, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "G:\Source\gvsbuild\gvsbuild\utils\builder.py", line 632, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "F:\Green\Language\Python\3.6.3\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild win32\vs14\glib.sln /p:Configuration=Release_BundledPCRE /nologo /p:Platform=x64 /p:PythonPath="F:\Green\Language\Python\3.6.3" /p:PythonDir="F:\Green\Language\Python\3.6.3"   /v:minimal' returned non-zero exit status 1.
Error: glib build failed
```

**Comment by guruDanny67** [comment]
What's present before the traceback ? Probably the error is indicated there.

Thanks

**Comment by dbyoung720** [comment]
before the traceback is right, When compile glib, error. 
It should be a lack of path, but I don't know how to change it.

'msbuild win32\vs14\glib.sln , win32 before is no path.

**Comment by guruDanny67** [comment]
It can be a mismatch version or something like this. Try to use

```
python %CurrentCD%build.py build -p x64 --vs-ver="14" --vs-install-path="D:\Language\VS2015"  --msys-dir="F:\Green\Language\MSYS2" --clean --no-deps glib
```
to remove and expand a clean versione of glib and try to build only that project.

If it's not working I normally add a --from-scratch (so i should be 
```
python %CurrentCD%build.py build -p x64 --vs-ver="14" --vs-install-path="D:\Language\VS2015"  --msys-dir="F:\Green\Language\MSYS2" --from-scratch gtk3
```
that cleans some (a lot) intemediate build directory before start.

With best regards

**Comment by nacho** [comment]
Since there was no answer on the ticket and appveyor is building fine I am now closing this ticket. Feel free to reopen it if you still have issues.

**Comment by dbyoung720** [comment]
build Success.
OK.
