### ISSUE TITLE
libffi fails to build

### ISSUE THREAD

**Issue by TingPing** [wingtk/gvsbuild#211]
Seems to be a generic Meson error: `The directory name is invalid.`

Full output:

```
Building project libffi
Already on 'meson'
Your branch is up to date with 'origin/meson'.
The directory name is invalid.
Traceback (most recent call last):
  File "C:\Users\tingping\Projects\gvsbuild\gvsbuild\utils\builder.py", line 312, in build
    self.__build_one(p)
  File "C:\Users\tingping\Projects\gvsbuild\gvsbuild\utils\builder.py", line 391, in __build_one
    proj.build()
  File "C:\Users\tingping\Projects\gvsbuild\gvsbuild\projects.py", line 785, in build
    Meson.build(self)
  File "C:\Users\tingping\Projects\gvsbuild\gvsbuild\utils\base_builders.py", line 52, in build
    self.exec_vs(cmd)
  File "C:\Users\tingping\Projects\gvsbuild\gvsbuild\utils\base_project.py", line 71, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\Users\tingping\Projects\gvsbuild\gvsbuild\utils\builder.py", line 601, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\Users\tingping\Projects\gvsbuild\gvsbuild\utils\builder.py", line 633, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\gtk-build\python-3.6\Win32\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\gtk-build\python-3.6\Win32\python.exe\python.exe C:\gtk-build\tools\meson-0.44.0\meson.py C:\gtk-build\build\Win32\release\libffi C:\gtk-build\build\Win32\release\libffi-meson --prefix C:\gtk-build\gtk\Win32\release --buildtype release' returned non-zero exit status 1.
Error: libffi build failed
```

**Comment by TingPing** [comment]
Seems to have gone away... (meson update maybe?)
