### ISSUE TITLE
libffi build failure

### ISSUE THREAD

**Issue by dsorber** [wingtk/gvsbuild#229]
I also see a libffi build failure but I don't think this is related to #211.

```
Configuring fficonfig.h using configuration
Build targets in project: 3
Found ninja-1.8.2 at 'C:\gtk-build\tools\ninja\ninja.EXE'
[1/10] Generating x86_win64_intel_S.i with a custom command.
win64_intel.S
[3/10] Generating x86_win64_intel_S.obj with a custom command.
FAILED: src/x86_win64_intel_S.obj
"C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN/ml.EXE" "/Fo" "src/x86_win64_intel_S.obj" "/c" "src/x86_win64_intel_S.i"
 Assembling: src/x86_win64_intel_S.i
src/x86_win64_intel_S.i(965) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(965) : error A2013:.MODEL must precede this directive
src/x86_win64_intel_S.i(975) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(975) : error A2034:must be in segment block
src/x86_win64_intel_S.i(979) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(979) : error A2034:must be in segment block : ffi_call_win6nt block
src/x86_win64_intel_S.i(982) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(982) : error A2034:must be in segment block
src/x86_win64_intel_S.i(983) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(983) : error A2034:must be in segment block
src/x86_win64_intel_S.i(984) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(984) : error A2034:must be in segment block
src/x86_win64_intel_S.i(985) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(985) : error A2034:must be in segment block
src/x86_win64_intel_S.i(988) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(988) : error A2008:syntax error : ent block
src/x86_win64_intel_S.i(989) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(989) : error A2008:syntax error : ent block
src/x86_win64_intel_S.i(990) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(990) : error A2008:syntax error : ent bl♥src/x86_win64_intel_S.i(991) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(991) : error A2034:must be in segment block
src/x86_win64_intel_S.i(993) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(993) : error A2034:must be in segment block
src/x86_win64_intel_S.i(996) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(996) : error A2034:must be in segment block
src/x86_win64_intel_S.i(997) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(997) : error A2034:must be in segment block
src/x86_win64_intel_S.i(998) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(998) : error A2034:must be in segment block
src/x86_win64_intel_S.i(999) : error A2071:initializer magnitude too large for specified size
src/x86_win64_intel_S.i(999) : error A2034:must be in segment block
src/x86_win64_intel_S.i(1000
src/x86_win64_intel_S.i(1000) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1001
src/x86_win64_intel_S.i(1001) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1002
src/x86_win64_intel_S.i(1002) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1003
src/x86_win64_intel_S.i(1003) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1005
src/x86_win64_intel_S.i(1005) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1007
src/x86_win64_intel_S.i(1007) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1008
src/x86_win64_intel_S.i(1008) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1009
src/x86_win64_intel_S.i(1009) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1010
src/x86_win64_intel_S.i(1010) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1011
src/x86_win64_intel_S.i(1011) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1012
src/x86_win64_intel_S.i(1012) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1013
src/x86_win64_intel_S.i(1013) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1026
src/x86_win64_intel_S.i(1026) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1027
src/x86_win64_intel_S.i(1027) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1028
src/x86_win64_intel_S.i(1028) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1029
 epilogue(1): Macro Called From
  src/x86_win64_intel_S.i(1029): Main Line Code
src/x86_win64_intel_S.i(1029) : error A2034:must be in segment block epilogue(1): Macro Called From
  src/x86_win64_intel_S.i(1029): Main Line Code
src/x86_win64_intel_S.i(1029
 epilogue(5): Macro Called From
  src/x86_win64_intel_S.i(1029): Main Line Code
src/x86_win64_intel_S.i(1029) : error A2034:must be in segment block epilogue(5): Macro Called From
  src/x86_win64_intel_S.i(1029): Main Line Code
src/x86_win64_intel_S.i(1030
src/x86_win64_intel_S.i(1030) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1031
src/x86_win64_intel_S.i(1031) : error A2008:syntax error : regment blocksrc/x86_win64_intel_S.i(1032
src/x86_win64_intel_S.i(1032) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1033
 epilogue(1): Macro Called From
  src/x86_win64_intel_S.i(1033): Main Line Code
src/x86_win64_intel_S.i(1033) : error A2034:must be in segment block epilogue(1): Macro Called From
  src/x86_win64_intel_S.i(1033): Main Line Code
src/x86_win64_intel_S.i(1033
 epilogue(5): Macro Called From
  src/x86_win64_intel_S.i(1033): Main Line Code
src/x86_win64_intel_S.i(1033) : error A2034:must be in segment block epilogue(5): Macro Called From
  src/x86_win64_intel_S.i(1033): Main Line Code
src/x86_win64_intel_S.i(1034
src/x86_win64_intel_S.i(1034) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1035
src/x86_win64_intel_S.i(1035) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1036
 epilogue(1): Macro Called From
  src/x86_win64_intel_S.i(1036): Main Line Code
src/x86_win64_intel_S.i(1036) : error A2034:must be in segment block epilogue(1): Macro Called From
  src/x86_win64_intel_S.i(1036): Main Line Code
src/x86_win64_intel_S.i(1036
 epilogue(5): Macro Called From
  src/x86_win64_intel_S.i(1036): Main Line Code
src/x86_win64_intel_S.i(1036) : error A2034:must be in segment block epilogue(5): Macro Called From
  src/x86_win64_intel_S.i(1036): Main Line Code
src/x86_win64_intel_S.i(1037
src/x86_win64_intel_S.i(1037) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1038
src/x86_win64_intel_S.i(1038) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1039
 epilogue(1): Macro Called From
  src/x86_win64_intel_S.i(1039): Main Line Code
src/x86_win64_intel_S.i(1039) : error A2034:must be in segment block epilogue(1): Macro Called From
  src/x86_win64_intel_S.i(1039): Main Line Code
src/x86_win64_intel_S.i(1039
 epilogue(5): Macro Called From
  src/x86_win64_intel_S.i(1039): Main Line Code
src/x86_win64_intel_S.i(1039) : error A2034:must be in segment block epilogue(5): Macro Called From
  src/x86_win64_intel_S.i(1039): Main Line Code
src/x86_win64_intel_S.i(1040
src/x86_win64_intel_S.i(1040) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1041
src/x86_win64_intel_S.i(1041) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1042
src/x86_win64_intel_S.i(1042) : error A2034:must be in segment blocksrc/x86_win64_intel_S.i(1043)embly
Microsoft (R) Macro Assembler Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

[8/10] Compiling C object src/ffi@sha/closures.c.obj.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 782, in build
    Meson.build(self)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 61, in build
    self.builder.exec_vs('ninja install', working_dir=ninja_build)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 614, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 646, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: libffi build failed
```

**Comment by nacho** [comment]
The other ticket was closed after retrying. Maybe a new version of meson fixed the issue? Can you retry?

**Comment by dsorber** [comment]
Sure. I just tried again and got exactly the same error.

**Comment by nacho** [comment]
Maybe you are missing to enable some of the features from visual studio when installing it?

**Comment by dsorber** [comment]
Any idea what features that might be? I was using the free version of Visual Studio. I haven't tried with 2017 yet.

**Comment by dsorber** [comment]
I just tried again with Visual Studio Community 2017 (this is the free version).  I made sure to enable Win SDK 8.1 when installing and I was able to get past the problem above.  So I think you were right.


However I now get this error:
```
The Meson build system
Version: 0.44.0
Source dir: C:\gtk-build\build\x64\release\atk
Build dir: C:\gtk-build\build\x64\release\atk-meson
Build type: native build
Project name: atk
Native C compiler: cl (msvc 19.13.26129)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "bind_textdomain_codeset": NO
Found pkg-config: C:\gtk-build\gtk\x64\release\bin\pkg-config.EXE (1.4.0)
Native dependency gobject-2.0 found: YES 2.54.2
Configuring atk.pc using configuration
Configuring config.h using configuration
Configuring atkversion.h using configuration
Native dependency glib-2.0 found: YES 2.54.2
Program glib-genmarshal found: YES (python C:\gtk-build\gtk\x64\release\bin\glib-genmarshal)
Program glib-mkenums found: YES (python C:\gtk-build\gtk\x64\release\bin\glib-mkenums)
Configuring atk.rc using configuration
Build targets in project: 13
Found ninja-1.8.2 at 'C:\gtk-build\tools\ninja\ninja.EXE'
[2/51] Generating atkmarshal_c with a custom command.
INFO: Reading ../atk/atk/atkmarshal.list...
[3/51] Generating atkmarshal_h with a custom command.
INFO: Reading ../atk/atk/atkmarshal.list...
[10/51] Compiling C object atk/atk-1.0@sha/atkhyperlink.c.obj.
FAILED: atk/atk-1.0@sha/atkhyperlink.c.obj
cl @atk/atk-1.0@sha/atkhyperlink.c.obj.rsp
C:/gtk-build/gtk/x64/release/bin/../include/glib-2.0\glib/gi18n-lib.h(23): fatal error C1083: Cannot open include file: 'libintl.h': No such file or directory
[15/51] Generating atk-enum-types.c with a meson_exe.py custom command.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()
  File "c:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 66, in build
    Meson.build(self, meson_params='-Ddisable_introspection=true -Denable_docs=false', make_tests=True)
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 56, in build
    self.builder.exec_vs('ninja', working_dir=ninja_build)
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 614, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 646, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja' returned non-zero exit status 1.
Error: atk build failed
```

**Comment by guruDanny67** [comment]
I take a look at the problem: it seems a bug in the new Visual Studio 2017: the include path set BEFORE calling the batch for the vs env (vsvarsall.bat or similar) is not keeped so the build is done without the main gtk include dir (say 'c:\gtk-build\gtk\x64\release\include') but only with the vs ones so the error.

We made in this way, adding the main include, lib & bin dir to INCLUDE, LIB & LIBPATH, PATH environment, to simplify the build and let the tools find the library & the pkg config executable. 

Probably the right thing to do for the include & lib stuff is to add, in the .pc file for glib, the dependency to the gettext library that should add the right include & lib options.

**Comment by TingPing** [comment]
> Probably the right thing to do for the include & lib stuff is to add, in the .pc file for glib, the dependency to the gettext library that should add the right include & lib options.

That sounds wrong to be, everything would be broken by default until it gets the INCLUDE by chance in a dependency.

**Comment by guruDanny67** [comment]
I'm not a pkg config expert but if we made a correct gettext.pc file and say to glib that it's a requirement, the gettext include path it's not added when we get the glib parameters with the '--cflags' ?

In this way, if we put the gettext include in a different directory, the .h file will be found anyway, as soon as we have access to the .pc file, or am I missing something?

Thanks for the reply

**Comment by TingPing** [comment]
Yes that should work but again, INCLUDE should always be there, so its a bug no matter if we fiddle with pc files.

**Comment by guruDanny67** [comment]
Sorry, I agree that's a bug (and a big one, BTW) no matter what. 

I was only clarifying myself on pkg_config, thanks!

**Comment by nacho** [comment]
@guruDanny67 pointed out in another issue that now it should be building fine with a newer visual studio 2017. Can you guys try?

**Comment by dsorber** [comment]
Sorry for not getting back to this for a while... 

I retried this yesterday and finally got through the build process using the latest version of Visual Studio 2017 Community Edition (aka the free version of VS).  I did encounter a couple of issues that I had to manually work around:

- The source for libtiff is no longer available at ftp://download.osgeo.org/pub/libtiff/ but it is available at http://download.osgeo.org/pub/libtiff/ 
-  When building gettext MSVC complained that the `memmove()` and `memchr()` functions could not be declared because they already existed as intrinsics.  As a work around I went into the source and ifdefed out the function declarations which allowed the build to succeed. 

Now that the build completed I realize that this script has built `.lib` static libraries, is there any way for the script to build `.dll` shared libraries (I don't see any script option nor do I know enough about MSVC configuration...)?

**Comment by nacho** [comment]
Thanks for letting me know about libtiff, it should be fixed. About gettext I'll have a look later on.
In relation to .lib those are the files used to either link to static libraries or to link to the dlls. You should see the dlls in bin instead

**Comment by dsorber** [comment]
Sure. I'm not sure what the best approach to the gettext issue is, maybe a patch that ifdef's out the function declarations like I did?

Re the .libs thanks for the explanation, I'm reading more on that stuff now.

**Comment by nacho** [comment]
Can you post your patch here?

**Comment by guruDanny67** [comment]
If thsi can help, it seems the error appears only when building with full
vs 2017 (without any --vs-ver set, I normally use the vs2017 but telling
it's the 2015 version with --vs-ver 14 because a lot of projects doesn't
have, yet, the vs2017 solutions), using the solution under build\win32\vs15
(i.e. using the vs141 tools).

The solution in vs14 & vs15 are pretty the same, only the tools and the sdk
version seem different

With best regards

2018-05-18 13:50 GMT+02:00 David Sorber <notifications@github.com>:

**Comment by dsorber** [comment]
Someone else created an issue for this (#260) so let's continue this there.
