### ISSUE TITLE
cmake error when building win-iconv

### ISSUE THREAD

**Issue by lazka** [wingtk/gvsbuild#236]
```
C:\gtk-build\github\gvsbuild>C:\Python36\python.exe build.py build --vs-ver=14 gtk3
Building project ninja
Building project meson
Building project cmake
Building project win-iconv
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/gtk-build/build/Win32/release/win-iconv-cmake/CMakeFiles/CMakeOutput.log".
See also "C:/gtk-build/build/Win32/release/win-iconv-cmake/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 1349, in build
    CmakeProject.build(self, use_ninja=True, cmake_params='-DBUILD_TEST=1', make_tests=True)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 98, in build
    self.builder.exec_vs(cmd, working_dir=work_dir)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 614, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 646, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX="C:\gtk-build\build\Win32\release\win-iconv-rel" -DGTK_DIR="C:\gtk-build\gtk\Win
32\release" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TEST=1 -BC:\gtk-build\build\Win32\release\win-iconv-cmake -HC:\gtk-build\build\Win32\release\win-iconv' re
turned non-zero exit status 1.
Error: win-iconv build failed
```

**Comment by nacho** [comment]
seems to me that you do not have visual studio 15 installed?

**Comment by lazka** [comment]
I've installed the "Visual C++ Build Tools 2015", but I haven't selected all components when installing, I'll try getting everything included.

**Comment by lazka** [comment]
Hm, didn't help. I don't know muchabout msvc, so I might be missing something obvious.

**Comment by nacho** [comment]
can you run the script in verbose and see if something outstands?

**Comment by sgeto** [comment]
try runnin it from a VS developer command prompt instead of cmd.

**Comment by lazka** [comment]
Small detour, with 2017 build tools it gets further (I had to adjust the vcvars32 path to `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars32.bat`), but finally fails with

```
Build targets in project: 13
Found ninja-1.8.2 at 'C:\gtk-build\tools\ninja\ninja.EXE'
[2/51] Generating atkmarshal_c with a custom command.
INFO: Reading ../atk/atk/atkmarshal.list...
[3/51] Generating atkmarshal_h with a custom command.
INFO: Reading ../atk/atk/atkmarshal.list...
[10/51] Compiling C object atk/atk-1.0@sha/atkhyperlink.c.obj.
FAILED: atk/atk-1.0@sha/atkhyperlink.c.obj
cl @atk/atk-1.0@sha/atkhyperlink.c.obj.rsp
C:/gtk-build/gtk/Win32/release/include/glib-2.0\glib/gi18n-lib.h(23): fatal error C1083: Cannot open include file: 'libintl.h': No such file or directory
[15/51] Generating atk-enum-types.c with a meson_exe.py custom command.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 326, in build
    self.__build_one(p)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 405, in __build_one
    proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 66, in build
    Meson.build(self, meson_params='-Ddisable_introspection=true -Denable_docs=false', make_tests=True)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 56, in build
    self.builder.exec_vs('ninja', working_dir=ninja_build)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 615, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 647, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja' returned non-zero exit status 1.
Error: atk build failed
```

Thought I'd mention it since there are some 2017 recently.

**Comment by lazka** [comment]
Installing full VS2015 helped. That's what I get for trying to safe disk space :/

Sorry for the noise :(

**Comment by nacho** [comment]
FWIW if you are starting with msvc I would suggest you to use 2017 since that is the last stable version. Good that you fixed your setup though.
