### ISSUE TITLE
Build fails cannot open include file 'libintl.h'

### ISSUE THREAD

**Issue by huwpascoe** [wingtk/gvsbuild#257]
Managed to workaround by manually copying `gtk-build\gtk\x64\release\include\libintl.h` into various directories through trial and error but otherwise broken.

**Comment by Adriatic1** [comment]
I got the same issue here, Windows 10 64-bit, build started with:
python.exe build.py build gtksourceview3 gtk3 adwaita-icon-theme --platform x64 --vs-ver 15 --win-sdk-ver 10.0.16299.0 --vs-install-path "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community"

The error output:
Configuring libglib-2.0.so.0.5600.0-gdb.py using configuration
Configuring gobject.rc using configuration
WARNING: The variable(s) 'LT_CURRENT_MINUS_AGE' in the input file gobject\gobject.rc.in are not present in the given configuration data
Configuring glib-genmarshal using configuration
Configuring glib-mkenums using configuration
Configuring libgobject-2.0.so.0.5600.0-gdb.py using configuration
Configuring gthread.rc using configuration
WARNING: The variable(s) 'LT_CURRENT_MINUS_AGE' in the input file gthread\gthread.rc.in are not present in the given configuration data
Configuring gmoduleconf.h using configuration
Configuring gmodule.rc using configuration
WARNING: The variable(s) 'LT_CURRENT_MINUS_AGE' in the input file gmodule\gmodule.rc.in are not present in the given configuration data
Configuring gnetworking.h using configuration
Configuring gdbus-codegen using configuration
Configuring config.py using configuration
Configuring __init__.py using configuration
Configuring codegen.py using configuration
Configuring codegen_main.py using configuration
Configuring codegen_docbook.py using configuration
Configuring dbustypes.py using configuration
Configuring parser.py using configuration
Configuring utils.py using configuration
Library shlwapi found: YES
Library dnsapi found: YES
Configuring gio.rc using configuration
WARNING: The variable(s) 'LT_CURRENT_MINUS_AGE' in the input file gio\gio.rc.in are not present in the given configuration data
Dependency libelf found: NO
Configuring gobject-2.0.pc using configuration
Configuring glib-2.0.pc using configuration
WARNING: The variable(s) 'CARBON_LIBS', 'COCOA_LIBS', 'GLIB_EXTRA_CFLAGS', 'G_LIBS_EXTRA', 'G_THREAD_LIBS', 'ICONV_LIBS', 'PCRE_LIBS', 'PCRE_REQUIRES' in the input file glib-2.0.pc.in are not present in the given configuration data
Configuring gthread-2.0.pc using configuration
WARNING: The variable(s) 'G_THREAD_CFLAGS', 'G_THREAD_LIBS' in the input file gthread-2.0.pc.in are not present in the given configuration data
Configuring gmodule-2.0.pc using configuration
WARNING: The variable(s) 'G_MODULE_LDFLAGS', 'G_MODULE_LIBS', 'G_MODULE_SUPPORTED', 'G_THREAD_CFLAGS', 'G_THREAD_LIBS' in the input file gmodule-2.0.pc.in are not present in the given configuration data
Configuring gmodule-export-2.0.pc using configuration
WARNING: The variable(s) 'G_MODULE_LDFLAGS', 'G_MODULE_LIBS', 'G_MODULE_SUPPORTED', 'G_THREAD_CFLAGS', 'G_THREAD_LIBS' in the input file gmodule-export-2.0.pc.in are not present in the given configuration data
Configuring gmodule-no-export-2.0.pc using configuration
WARNING: The variable(s) 'G_MODULE_LIBS', 'G_MODULE_SUPPORTED', 'G_THREAD_CFLAGS', 'G_THREAD_LIBS' in the input file gmodule-no-export-2.0.pc.in are not present in the given configuration data
Configuring gio-2.0.pc using configuration
WARNING: The variable(s) 'CARBON_LIBS', 'COCOA_LIBS', 'LIBMOUNT_LIBS', 'SELINUX_LIBS' in the input file gio-2.0.pc.in are not present in the given configuration data
Configuring gio-windows-2.0.pc using configuration
Configuring config.h using configuration
Build targets in project: 72
Found ninja-1.8.2 at 'C:\gtk-build\tools\ninja\ninja.EXE'
[31/483] Compiling C object glib/glib-2.0@sha/gbookmarkfile.c.obj.
FAILED: glib/glib-2.0@sha/gbookmarkfile.c.obj
cl @glib/glib-2.0@sha/gbookmarkfile.c.obj.rsp
c:\gtk-build\build\x64\release\glib\glib\glibintl.h(16): fatal error C1083: Cannot open include file: 'libintl.h': No such file or directory
[32/483] Compiling C object glib/gnulib/gnulib@sta/vasnprintf.c.obj.
../glib/glib/gnulib/vasnprintf.c(2423): warning C4146: unary minus operator applied to unsigned type, result still unsigned
../glib/glib/gnulib/vasnprintf.c(4629): warning C4146: unary minus operator applied to unsigned type, result still unsigned
[33/483] Compiling C object glib/glib-2.0@sha/gcharset.c.obj.
../glib/glib/gcharset.c(72): warning C4090: 'function': different 'const' qualifiers
[36/483] Compiling C object glib/pcre/pcre@sta/pcre_exec.c.obj.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()
  File "c:\gtk-build\gvsbuild\gvsbuild\projects.py", line 394, in build
    Meson.build(self, meson_params='-Dinternal_pcre=true')
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_builders.py", line 61, in build
    self.builder.exec_vs('ninja install', working_dir=ninja_build)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 614, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 646, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: glib build failed

**Comment by muntyan** [comment]
Same thing here, VS 2017, Windows 10. I worked it around by setting CFLAGS=-Ic:/gtk-build/.../include (backslashes didn't work!)

I don't get it, we do meson --prefix=c:\gtk-build\gtk\x64\release, why doesn't that add the corresponding include path? Is it a meason feature? I see gsvbuild sets INCLUDE and some other variables for meson, but they seem to have no effect. Is it perhaps because MSVC bat files override those? Could it be that it works with, say VS 2015, and not with VS 2017?

**Comment by guruDanny67** [comment]
Now with the latest vs2017 update (15.7.0) should work: they fix the
include error.


Il mar 8 mag 2018, 19:55 Yevgen Muntyan <notifications@github.com> ha
scritto:

**Comment by Adriatic1** [comment]
Tried to verify as well, but one of the download sites has been down for two days at least:

c:\gtk-build\gvsbuild>python.exe build.py build gtk3 adwaita-icon-theme gtksourceview3 --platform x64 --vs-ver 15 --win-sdk-ver 10.0.16299.0 --vs-install-path "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
Exception downloading file 'https://dl.hexchat.net/gtk-win32/src/win-iconv-0.0.8.tar.gz'
HTTP Error 521: Origin Down

**Comment by nacho** [comment]
That was fixed here https://github.com/wingtk/gvsbuild/commit/7074d70ed4639768d2f6fef94ff214897b7caf1e

**Comment by Adriatic1** [comment]
Thanks! I've missed it.
