### ISSUE TITLE
Gtksourceview3 does not build

### ISSUE THREAD

**Issue by Adriatic1** [wingtk/gvsbuild#258]
Trying to build GTK3 stack with GtkSourceView 3.x using this command:
````
python.exe build.py build gtksourceview3 gtk3 adwaita-icon-theme --platform x64 --vs-ver 15 --win-sdk-ver 10.0.16299.0 --vs-install-path "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community"

I had to pass through the issue of missing "libintl.h" (already reported).
When I solved that, gtksourceview3 fails to build with this error reported:
Building project gtksourceview3
MSBUILD : error MSB1009: Project file does not exist.
Switch: build\win32\vs15\gtksourceview.sln
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()
  File "c:\gtk-build\gvsbuild\gvsbuild\projects.py", line 646, in build
    self.exec_msbuild(r'build\win32\vs%(vs_ver)s\gtksourceview.sln')
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 76, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 71, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 614, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 646, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild build\win32\vs15\gtksourceview.sln /p:Configuration=release /nologo /p:Platform=x64 /p:PythonPath="C:\Python36" /p:PythonDir="C:\Python36"   /v:minimal /p:WindowsTargetPlatformVersion="10.0.16299.0"' returned non-zero exit status 1.
Error: gtksourceview3 build failed

Looking at the code, the project file exists in this folder:
c:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs14\
but it doesn't exist in:
c:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\
(the only file present here is "gtksourceview-version-paths.props")
Mentioning "Win32" for 64-bit build in error message above looks strange too 
("MSBUILD : error MSB1009: Project file does not exist.
Switch: build\win32\vs15\gtksourceview.sln")

I copied files from vs14 folder, and rerun the command, this time new error related to usage of older toolset (v140) instead of current one (v141).

After loading the project in VS2017 and retargeting the project it goes furthere, but compilation fails with:
 gtksourcecompletioninfo.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcecompletion
context.c(277): error C2065: 'GTK_SOURCE_TYPE_COMPLETION_ACTIVATION': undeclare
d identifier [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gt
ksourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcecompletion
info.c(505): warning C4996: 'gdk_screen_get_width': was declared deprecated [C:
\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.vcxp
roj]
  c:\gtk-build\gtk\x64\release\include\gtk-3.0\gdk\gdkscreen.h(58): note: see d
  eclaration of 'gdk_screen_get_width'
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcecompletion
info.c(506): warning C4996: 'gdk_screen_get_height': was declared deprecated [C
:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.vcx
proj]
  c:\gtk-build\gtk\x64\release\include\gtk-3.0\gdk\gdkscreen.h(60): note: see d
  eclaration of 'gdk_screen_get_height'
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcecompletion
.c(756): warning C4996: 'gdk_screen_get_width': was declared deprecated [C:\gtk
-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.vcxproj]
  c:\gtk-build\gtk\x64\release\include\gtk-3.0\gdk\gdkscreen.h(58): note: see d
  eclaration of 'gdk_screen_get_width'
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcebuffer.c(5
13): error C2065: 'GTK_SOURCE_TYPE_BRACKET_MATCH_TYPE': undeclared identifier [
C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.vc
xproj]
  gtksourcecompletionitem.c
  gtksourcecompletionproposal.c
  gtksourcecompletionprovider.c
  gtksourceencoding.c
  gtksourcefile.c
  gtksourcefileloader.c
  gtksourcefilesaver.c
  gtksourcegutter.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcefile.c(216
): error C2065: 'GTK_SOURCE_TYPE_NEWLINE_TYPE': undeclared identifier [C:\gtk-b
uild\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcefile.c(233
): error C2065: 'GTK_SOURCE_TYPE_COMPRESSION_TYPE': undeclared identifier [C:\g
tk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.vcxpro
j]
  gtksourcegutterrenderer.c
  gtksourcegutterrendererpixbuf.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcefilesaver.
c(426): error C2065: 'GTK_SOURCE_TYPE_NEWLINE_TYPE': undeclared identifier [C:\
gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.vcxpr
oj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcefilesaver.
c(444): error C2065: 'GTK_SOURCE_TYPE_COMPRESSION_TYPE': undeclared identifier
[C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.v
cxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcefilesaver.
c(462): error C2065: 'GTK_SOURCE_TYPE_FILE_SAVER_FLAGS': undeclared identifier
[C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.v
cxproj]
  gtksourcegutterrenderertext.c
  gtksourcelanguage.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcegutterrend
erer.c(491): error C4013: 'GTK_SOURCE_IS_VIEW' undefined; assuming extern retur
ning int [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksou
rceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcegutterrend
erer.c(492): error C4013: 'gtk_source_view_get_highlight_current_line' undefine
d; assuming extern returning int [C:\gtk-build\build\x64\release\gtksourceview3
\build\win32\vs15\gtksourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcegutterrend
erer.c(492): error C4013: 'GTK_SOURCE_VIEW' undefined; assuming extern returnin
g int [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksource
view.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcegutterrend
erer.c(695): error C2065: 'GTK_SOURCE_TYPE_GUTTER_RENDERER_STATE': undeclared i
dentifier [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtkso
urceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcegutterrend
erer.c(750): error C2065: 'GTK_SOURCE_TYPE_GUTTER_RENDERER_ALIGNMENT_MODE': und
eclared identifier [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\v
s15\gtksourceview.vcxproj]
  gtksourcelanguagemanager.c
  gtksourcemap.c
  gtksourcemark.c
  gtksourcemarkattributes.c
  gtksourceprintcompositor.c
  gtksourceregion.c
  gtksourcesearchcontext.c
  gtksourcesearchsettings.c
  gtksourcestyle.c
  gtksourcestylescheme.c
  gtksourcestyleschemechooser.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcesearchcont
ext.c(590): warning C4267: '=': conversion from 'size_t' to 'gint', possible lo
ss of data [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtks
ourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcesearchcont
ext.c(2538): warning C4267: '=': conversion from 'size_t' to 'gint', possible l
oss of data [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtk
sourceview.vcxproj]
  gtksourcestyleschemechooserbutton.c
  gtksourcestyleschemechooserwidget.c
  gtksourcestyleschememanager.c
  gtksourcetag.c
  gtksourceundomanager.c
  gtksourceutils.c
  gtksourceversion.c
  gtksourceview.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceutils.c(69
): warning C4267: '=': conversion from 'size_t' to 'gint', possible loss of dat
a [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview
.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceutils.c(16
7): warning C4267: '=': conversion from 'size_t' to 'gint', possible loss of da
ta [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourcevie
w.vcxproj]
  gtksourcebufferinputstream.c
  gtksourcebufferinternal.c
  gtksourcebufferoutputstream.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(491
): error C2065: 'GTK_SOURCE_TYPE_COMPLETION': undeclared identifier [C:\gtk-bui
ld\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(616
): error C2065: 'GTK_SOURCE_TYPE_SMART_HOME_END_TYPE': undeclared identifier [C
:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.vcx
proj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(654
): error C2065: 'GTK_SOURCE_TYPE_DRAW_SPACES_FLAGS': undeclared identifier [C:\
gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.vcxpr
oj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(671
): error C2065: 'GTK_SOURCE_TYPE_BACKGROUND_PATTERN_TYPE': undeclared identifie
r [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview
.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(880
): error C2065: 'GTK_SOURCE_TYPE_CHANGE_CASE_TYPE': undeclared identifier [C:\g
tk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.vcxpro
j]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(165
3): error C4013: 'gtk_source_completion_create_context' undefined; assuming ext
ern returning int [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs
15\gtksourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(165
3): error C4047: '=': 'GtkSourceCompletionContext *' differs in levels of indir
ection from 'int' [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs
15\gtksourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(165
5): error C4013: 'gtk_source_completion_show' undefined; assuming extern return
ing int [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksour
ceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(165
6): error C4013: 'gtk_source_completion_get_providers' undefined; assuming exte
rn returning int [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs1
5\gtksourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(315
6): error C4013: 'gtk_source_completion_block_interactive' undefined; assuming
extern returning int [C:\gtk-build\build\x64\release\gtksourceview3\build\win32
\vs15\gtksourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(326
1): error C4013: 'gtk_source_completion_unblock_interactive' undefined; assumin
g extern returning int [C:\gtk-build\build\x64\release\gtksourceview3\build\win
32\vs15\gtksourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(394
7): warning C4267: 'function': conversion from 'size_t' to 'gint', possible los
s of data [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtkso
urceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourceview.c(420
4): warning C4267: 'function': conversion from 'size_t' to 'gint', possible los
s of data [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtkso
urceview.vcxproj]
  gtksourcecompletioncontainer.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcebufferinpu
tstream.c(433): error C2065: 'GTK_SOURCE_TYPE_NEWLINE_TYPE': undeclared identif
ier [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourcevi
ew.vcxproj]
  gtksourcecompletionmodel.c
  gtksourcecontextengine.c
  gtksourceengine.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcecompletion
container.c(58): warning C4996: 'gdk_screen_get_width': was declared deprecated
 [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtksourceview.
vcxproj]
  c:\gtk-build\gtk\x64\release\include\gtk-3.0\gdk\gdkscreen.h(58): note: see d
  eclaration of 'gdk_screen_get_width'
  gtksourcegutterrendererlines.c
  gtksourcegutterrenderermarks.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\gtksourcecontexteng
ine.c(4545): warning C4267: '=': conversion from 'size_t' to 'gint', possible l
oss of data [C:\gtk-build\build\x64\release\gtksourceview3\build\win32\vs15\gtk
sourceview.vcxproj]
  gtksourceiter.c
  gtksourcelanguage-parser-1.c
  gtksourcelanguage-parser-2.c
  gtksourcemarkssequence.c
  gtksourcepixbufhelper.c
  gtksourceregex.c
  gtksourcespacedrawer.c
  gtksourceundomanagerdefault.c
  gtksourceview-i18n.c
  gtksourceview-init.c
  gtksourceview-utils.c
  gtksourceview-enumtypes.c
  gtksourceview-resources.c
  gtksourcecompletionwords.c
  gtksourcecompletionwordsbuffer.c
  gtksourcecompletionwordslibrary.c
  gtksourcecompletionwordsproposal.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\completion-provider
s\words\gtksourcecompletionwordslibrary.c(130): warning C4267: '=': conversion
from 'size_t' to 'gint', possible loss of data [C:\gtk-build\build\x64\release\
gtksourceview3\build\win32\vs15\gtksourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\completion-provider
s\words\gtksourcecompletionwordslibrary.c(163): warning C4267: '=': conversion
from 'size_t' to 'gint', possible loss of data [C:\gtk-build\build\x64\release\
gtksourceview3\build\win32\vs15\gtksourceview.vcxproj]
  gtksourcecompletionwordsutils.c
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\completion-provider
s\words\gtksourcecompletionwords.c(257): warning C4267: '=': conversion from 's
ize_t' to 'gint', possible loss of data [C:\gtk-build\build\x64\release\gtksour
ceview3\build\win32\vs15\gtksourceview.vcxproj]
c:\gtk-build\build\x64\release\gtksourceview3\gtksourceview\completion-provider
s\words\gtksourcecompletionwords.c(502): error C2065: 'GTK_SOURCE_TYPE_COMPLETI
ON_ACTIVATION': undeclared identifier [C:\gtk-build\build\x64\release\gtksource
view3\build\win32\vs15\gtksourceview.vcxproj]
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()
  File "c:\gtk-build\gvsbuild\gvsbuild\projects.py", line 646, in build
    self.exec_msbuild(r'build\win32\vs%(vs_ver)s\gtksourceview.sln')
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 76, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 71, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 614, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 646, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild build\win32\vs15\gtksourceview.sln /p:Configuration=release /nologo /p:Platform=x64 /p:PythonPath="C:\Python36" /p:PythonDir="C:\Python36"   /v:minimal /p:WindowsTargetPlatformVersion="10.0.16299.0"' returned non-zero exit status 1.
Error: gtksourceview3 build failed
```
Any tips here?

**Comment by Adriatic1** [comment]
Just noticed that the first part of log for the last error is relevant too:
Building project gtksourceview3
  Copying config.h from config.h.win32...
          1 file(s) copied.
  Generating gtksourceversion.h...
  Generating Enumeration sources...
  Can't exec /usr/bin/env at C:\gtk-build\build\x64\release\gtksourceview3\buil
  d\win32\vs15\\..\..\..\..\..\..\..\gtk\x64\Release\bin\glib-mkenums line 1.
  Can't exec /usr/bin/env at C:\gtk-build\build\x64\release\gtksourceview3\buil
  d\win32\vs15\\..\..\..\..\..\..\..\gtk\x64\Release\bin\glib-mkenums line 1.
  Generating GResource sources...
  XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
  gtksourcebuffer.c
  gtksourcecompletion.c
  gtksourcecompletioncontext.c
...

**Comment by guruDanny67** [comment]
Now the build of all the gtk3 stack should be correct, with vs2015 (tested with x86) and with vs2017 (tested x86 & x64).

Please let me know if it's ok.

    Thanks

**Comment by Adriatic1** [comment]
Sorry, just noticed that i forgot to close this one.
Thanks, it works fine now.
