### ISSUE TITLE
gtk3-full does not build

### ISSUE THREAD

**Issue by Adriatic1** [wingtk/gvsbuild#259]
Tried to build gtk3-full to fix some issues with missing stock icons:
c:\gtk-build\gvsbuild>python.exe build.py build gtk3 hicolor adwaita-icon-theme gtksourceview3 --platform x64 --vs-ver 15 --win-sdk-ver 10.0.16299.0 --vs-install-path "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community"

Got this error:
Building project libcroco
MSBUILD : error MSB1009: Project file does not exist.
Switch: build\win32\vs15\libcroco.sln
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()
  File "c:\gtk-build\gvsbuild\gvsbuild\projects.py", line 775, in build
    self.exec_msbuild(r'build\win32\vs%(vs_ver)s\libcroco.sln')
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 76, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 71, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 614, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 646, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild build\win32\vs15\libcroco.sln /p:Configuration=release /nologo /p:Platform=x64 /p:PythonPath="C:\Python36" /p:PythonDir="C:\Python36"   /v:minimal /p:WindowsTargetPlatformVersion="10.0.16299.0"' returned non-zero exit status 1.
Error: libcroco build failed

Indeed, .sln file for libcroco does not exist, only project file exists here:
c:\gtk-build\gvsbuild\gettext\build\win32\vs15\libcroco_rpl.vcxproj

**Comment by Adriatic1** [comment]
Copied all files from:
c:\gtk-build\build\x64\release\libcroco\build\win32\vs14\
to
c:\gtk-build\build\x64\release\libcroco\build\win32\vs15\
to get further:
Building project libcroco
c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VC
Targets\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools fo
r v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 bui
ld tools, please install v140 build tools.  Alternatively, you may upgrade to t
he current Visual Studio tools by selecting the Project menu or right-click the
 solution, and then selecting "Retarget solution". [C:\gtk-build\build\x64\rele
ase\libcroco\build\win32\vs15\croco.vcxproj]
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()

Updated toolkit manually from 140 to 141, the build passed further until:
gtk-update-icon-cache.exe: Cache file created successfully.
**Building project librsvg
MSBUILD : error MSB1009: Project file does not exist.
Switch: build\win32\vs15\librsvg.sln**
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()

... to be continued ...

**Comment by Adriatic1** [comment]
Copied content from:
c:\gtk-build\build\x64\release\librsvg\build\win32\vs14\
to
c:\gtk-build\build\x64\release\librsvg\build\win32\vs15\
repeated build command

Next failed cogl:
64\release\cogl\build\win32\vs15\cogl.vcxproj]
c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VC
Targets\Microsoft.CppBuild.targets(1202,5): warning MSB8012: TargetPath(C:\gtk-
build\build\x64\release\cogl\build\win32\vs15\Release\x64\bin\cogl.dll) does no
t match the Linker's OutputFile property value (C:\gtk-build\build\x64\release\
cogl\build\win32\vs15\Release\x64\bin\cogl-1.0.dll). This may cause your projec
t to build incorrectly. To correct this, please make sure that $(OutDir), $(Tar
getName) and $(TargetExt) property values match the value specified in %(Link.O
utputFile). [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VC
Targets\Microsoft.CppBuild.targets(1204,5): warning MSB8012: TargetName(cogl) d
oes not match the Linker's OutputFile property value (cogl-1.0). This may cause
 your project to build incorrectly. To correct this, please make sure that $(Ou
tDir), $(TargetName) and $(TargetExt) property values match the value specified
 in %(Link.OutputFile). [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\c
ogl.vcxproj]
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:ICF' specification
 [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_attribute_type_get_ty
pe [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_bitmap_error_get_type
 [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_blend_string_error_ge
t_type [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_buffer_bit_get_type [
C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_buffer_target_get_typ
e [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_color_mask_get_type [
C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_depth_test_function_g
et_type [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_feature_flags_get_typ
e [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_fog_mode_get_type [C:
\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_indices_type_get_type
 [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_material_alpha_func_g
et_type [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_material_filter_get_t
ype [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_material_layer_type_g
et_type [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_material_wrap_mode_ge
t_type [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_pixel_format_get_type
 [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_read_pixels_flags_get
_type [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_renderer_error_get_ty
pe [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_shader_type_get_type
[C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_system_error_get_type
 [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_texture_components_ge
t_type [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_texture_error_get_typ
e [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_texture_flags_get_typ
e [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_texture_type_get_type
 [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_vertices_mode_get_typ
e [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_winding_get_type [C:\
gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
cogl.def : error LNK2001: unresolved external symbol cogl_winsys_feature_get_ty
pe [C:\gtk-build\build\x64\release\cogl\build\win32\vs15\cogl.vcxproj]
C:\gtk-build\build\x64\release\cogl\build\win32\vs15\Release\x64\bin\cogl-1.0.l
ib : fatal error LNK1120: 26 unresolved externals [C:\gtk-build\build\x64\relea
se\cogl\build\win32\vs15\cogl.vcxproj]
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()

**Comment by Adriatic1** [comment]
Libcroco issue should be fixed with this commit: 
https://github.com/Adriatic1/gvsbuild/commit/0ddc00e85690fb979b37bb136f5876e3f30cd6a0
Note though that the ideal situation would be to move all these files to libcroco upstream itself.
I've copied old vs14 files and then modified the new solution to use newer SDK and set toolset 141 by default.

Can you give it a try and cherry pick it if it works for you?
I plan to make another commit for librsvg as well ...

**Comment by Adriatic1** [comment]
Similar patch for librsvg:
https://github.com/Adriatic1/gvsbuild/commit/0dfe622820f38fe826f0c4cd6372c902469da19e

**Comment by guruDanny67** [comment]
As I write in the other comment:

Now the build of all the gtk3 stack should be correct, with vs2015 (tested with x86) and with vs2017 (tested x86 & x64).

Please let me know if it's ok.

    Thanks
