### ISSUE TITLE
Error: gobject-introspection build failed about creating gir/GLib-2.0.gir

### ISSUE THREAD

**Issue by pinging2000** [wingtk/gvsbuild#269]
Hi,

  I'm having an issue to build GTK+3 with the build command "pygobject". I am using VS-2015 with Python 3.7. There is no precise information in any log files except the fact there is a failed. To me, it sounds like the "_giscanner.pyd" is not linked.

  Any idea about this issue?
  Many Thanks

 

```
[66/98] Linking target girepository/girepository-1.0-1.dll.
   Creating library girepository\\girepository-1.0.lib and object girepository\\girepository-1.0.exp
[71/98] Linking target giscanner/_giscanner.pyd.
   Creating library giscanner/_giscanner.lib and object giscanner/_giscanner.exp
[76/98] Generating gir-glib with a custom command.
FAILED: gir/GLib-2.0.gir
"D:\Python37-32\python.exe" "tools/g-ir-scanner" "--output=gir/GLib-2.0.gir" "--no-libtool" "--reparse-validate" "--add-include-path" "d:/gtk-build/build/Win32/debug/gobject-introspection-meson/gir" "--add-include-path" "d:/gtk-build/build/Win32/debug/gobject-introspection/gir" "--identifier-prefix=G" "--symbol-prefix=g" "--symbol-prefix=glib" "--c-include=glib.h" "--namespace=GLib" "--nsversion=2.0" "--library=glib-2.0" "--library=gobject-2.0" "--external-library" "--pkg=glib-2.0" "--cflags-begin" "-Id:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0" "-Id:/gtk-build/gtk/Win32/debug/bin/../lib/glib-2.0/include" "-DGLIB_COMPILATION" "-D__G_I18N_LIB_H__" "-DGETTEXT_PACKAGE=Dummy" "--cflags-end" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/gobject/glib-types.h" "d:/gtk-build/gtk/Win32/debug/bin/../lib/glib-2.0/include/glibconfig.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/galloca.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/garray.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gasyncqueue.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gatomic.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gbacktrace.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gbase64.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gbitlock.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gbookmarkfile.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gbytes.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gcharset.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gchecksum.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gconvert.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gdataset.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gdate.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gdatetime.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gdir.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/genviron.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gerror.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gfileutils.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/ggettext.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/ghash.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/ghmac.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/ghook.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/ghostutils.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gi18n-lib.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gi18n.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/giochannel.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gkeyfile.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/glist.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gmacros.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gmain.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gmappedfile.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gmarkup.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gmem.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gmessages.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gnode.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/goption.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gpattern.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gpoll.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gprimes.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gprintf.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gqsort.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gquark.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gqueue.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/grand.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/grcbox.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/grefcount.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/grefstring.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gregex.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gscanner.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gsequence.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gshell.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gslice.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gslist.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gspawn.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gstdio.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gstrfuncs.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gstring.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gstringchunk.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gtestutils.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gthread.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gthreadpool.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gtimer.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gtimezone.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gtrashstack.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gtree.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gtypes.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gunicode.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gurifuncs.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gutils.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/guuid.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gvariant.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gvarianttype.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gversion.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gversionmacros.h" "d:/gtk-build/gtk/Win32/debug/bin/../include/glib-2.0/glib/gwin32.h" "../gobject-introspection/gir/glib-2.0.c"
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\gvsbuild-master\gvsbuild\utils\builder.py", line 361, in build
    if self.__build_one(p):
  File "D:\gvsbuild-master\gvsbuild\utils\builder.py", line 477, in __build_one
    skip_deps = proj.build()
  File "D:\gvsbuild-master\gvsbuild\projects.py", line 519, in build
    Meson.build(self)
  File "D:\gvsbuild-master\gvsbuild\utils\base_builders.py", line 61, in build
    self.builder.exec_vs('ninja install', working_dir=ninja_build)
  File "D:\gvsbuild-master\gvsbuild\utils\builder.py", line 705, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "D:\gvsbuild-master\gvsbuild\utils\builder.py", line 737, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "D:\Git\IAPro2.4\OpenEV_python370\python\lib\subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
**subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: gobject-introspection build failed**
```

**Comment by pinging2000** [comment]
Hi,

  Since I saw some changes made, I built with the latest code and the build work. I changed --vs-ver=15 for --vs-ver=14 using Python 3.7

  Thanks
