### ISSUE TITLE
build failure in g-i

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#273]
I am getting the following build failure when making a build.

First thing is, why do I get g-i built by default? Is this something @guruDanny67 changed on the last commits?

```
FAILED: giscanner/giscanner@@_giscanner@sha/giscannermodule.c.obj 
cl @giscanner/giscanner@@_giscanner@sha/giscannermodule.c.obj.rsp
../gobject-introspection/giscanner/giscannermodule.c(25): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
[55/98] Generating scannerlexer with a custom command.
[56/98] Compiling C object giscanner/giscanner@@giscanner@sta/meson-generated_.._scannerparser.c.obj.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\github\gvsbuild\gvsbuild\utils\builder.py", line 361, in build
    if self.__build_one(p):
  File "C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\github\gvsbuild\gvsbuild\utils\builder.py", line 477, in __build_one
    skip_deps = proj.build()
  File "C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\github\gvsbuild\gvsbuild\projects.py", line 488, in build
    Meson.build(self)
  File "C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\github\gvsbuild\gvsbuild\utils\base_builders.py", line 61, in build
    self.builder.exec_vs('ninja install', working_dir=ninja_build)
  File "C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\github\gvsbuild\gvsbuild\utils\builder.py", line 705, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\github\gvsbuild\gvsbuild\utils\builder.py", line 737, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: gobject-introspection build failed
```

**Comment by guruDanny67** [comment]
The error is probably caused by using a virtualenved python: the solution
is to use a standard python or pass the --python-dir option with the base
(original) dir of the virtualenved python, I've done something about this
(for the libs) and now I see if I can fix it also for the include (i should
have a branch with this, somewherrr ...)

Before this rounds of commit all the gir/typelib were made when we build
gobject-introspection, using the old nmake makefiles presents in the
projects so gi depends on gdk-pixbuf, atk, pango, ..., gtk & gtk3 but, with
the updated libs, this doesn't work good anymore and there are a lot of
errors and all the gir were not built.

With meson all the projects build, if configurated, the gir/typelib (gtk &
gtk3 excluded) but they depend on gi so it's not possible to have the two
build system (atk depends on gi, gi depends on gtk that depends on atk so
you can't do the atk gir in atk and the other in gobject-introspection)

At first I move the gir creation on a new project so you have the regular
gtk stuff, gi that builds only libgirepository and g_ir_scanner and gi_gir
that builds the gir for the gtk stack, using the old nmake files but, as I
said, they don't work anymore without patching.

Is easier to make the gir using the meson build file for every single
project (is simple as adding '-Denable-introspection=true' or '-Dgir=true'
to the meson build command) and the files are updated and handled upstream
while the nmake files can disappear and are not update regularly.

So now every single project, gtk3 included even if with the old nmake,
create the gir and depends on gi.

I understand that this can be cumbersome so I started a modification to
make the gi stuff optional: the commit that add all the project after the
parsing of the command line is for this, to be able to have a
'--gi-disable' option, global for the script, to avoid the dependency so if
you only need the gtk3 stack you can build faster (but the code should be
the same, the giris something added to the build, it's not that the machine
code is made in one way or another depending on the gi presence, like for
example the -PIC option on linux where building a shared lib generates
different code to a static one).

With best reagards

    Daniele Forghieri




Il giorno gio 23 ago 2018 alle ore 15:32 Ignacio Casal Quinteiro <
notifications@github.com> ha scritto:

**Comment by nacho** [comment]
Thanks for the update on this

**Comment by guruDanny67** [comment]
BTW, one question: I see that there will be a gtk 3.24 after the 3.22: there are proposal for having also the gtk3 build with meson or this is only for the 3.9x/4.x line ?

Thanks again

**Comment by nacho** [comment]
I think they were thinking about having meson for gtk3 as well but I am not super sure tbh... I would definitely make our life easier :)

**Comment by nacho** [comment]
I think my problem right now here is that when building the stack with debug configuration is trying to find python36_d.lib which is not found because I do not have it installed. Any idea if it is possible to install the debug version of python?

**Comment by nacho** [comment]
it seems to be actually part of the normal installer of python, I just have to enable the right option.

BTW I think we should now document in the README that in order to build 32bit binaries you need python 32 bit and if you want 64bit binaries you need python 64.

**Comment by nacho** [comment]
When building the debug configuration I get the following error, any idea why it might happen?

Debug: running ['patch', '-p1', '-i', '00_glib_win_ver.patch'], cwd=C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection, path+=C:\Msys64\usr\bin
Debug: Changed path env variable to 'C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\gtk\x64\debug\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0;c:\program files\git\cmd;C:\Msys64\usr\bin'
Debug: Python library path is [C:\Python36\libs]
Debug: running C:\Python36\python.exe C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\tools\meson-0.47.1\meson.py C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection-meson --prefix C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\gtk\x64\debug --buildtype debug -Dpython=C:\Python36\python.exe -Dcairo-libname=cairo-gobject.dll, cwd=C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection, path+=None
Debug: running ninja install, cwd=C:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection-meson, path+=None[1/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/chm.c.obj.
[2/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/cmph_structs.c.obj.
[3/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/chd.c.obj.
[4/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/compressed_seq.c.obj.
[5/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/buffer_manager.c.obj.
[6/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/compressed_rank.c.obj.

[7/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/chd_ph.c.obj.
[8/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/cmph.c.obj.
[9/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/vstack.c.obj.
[10/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/jenkins_hash.c.obj.
[11/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/select.c.obj.
[12/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/graph.c.obj.
[13/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/miller_rabin.c.obj.
[14/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/fch.c.obj.
[15/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/fch_buckets.c.obj.
[16/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/hash.c.obj.

[17/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/vqueue.c.obj.
[18/98] Compiling C object girepository/girepository@@girepository-internals@sta/giroffsets.c.obj.
[19/98] Compiling C object girepository/girepository@@girepository-internals@sta/girnode.c.obj.
[20/98] Compiling C object girepository/girepository@@girepository-internals@sta/girmodule.c.obj.
[21/98] Compiling C object girepository/girepository@@girepository-gthash@sta/gthash.c.obj.
[22/98] Linking static target girepository/libgirepository-gthash.a.
[23/98] Compiling C object girepository/cmph/girepository@cmph@@cmph-bdz-test@exe/.._cmph-bdz-test.c.obj.
[24/98] Compiling C object girepository/girepository@@girepository-1.0@sha/gienuminfo.c.obj.

[25/98] Compiling C object girepository/girepository@@girepository-1.0@sha/gifieldinfo.c.obj.
[26/98] Compiling C object girepository/girepository@@girepository-1.0@sha/gibaseinfo.c.obj.
[27/98] Compiling C object girepository/girepository@@girepository-internals@sta/girwriter.c.obj.
[28/98] Compiling C object girepository/girepository@@girepository-1.0@sha/giarginfo.c.obj.
[29/98] Compiling C object girepository/girepository@@girepository-1.0@sha/gicallableinfo.c.obj.
c:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection\girepository\gicallableinfo.c(169) : warning C4715: 'g_callable_info_is_method': not all control paths return a value
c:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection\girepository\gicallableinfo.c(131) : warning C4715: 'g_callable_info_can_throw_gerror': not all control paths return a value
[30/98] Compiling C object girepository/girepository@@girepository-1.0@sha/giconstantinfo.c.obj.

[31/98] Compiling C object girepository/girepository@@girepository-1.0@sha/gisignalinfo.c.obj.
[32/98] Compiling C object girepository/girepository@@girepository-1.0@sha/gdump.c.obj.
[33/98] Compiling C object girepository/girepository@@girepository-1.0@sha/gifunctioninfo.c.obj.
[34/98] Compiling C object girepository/girepository@@girepository-1.0@sha/giregisteredtypeinfo.c.obj.
[35/98] Compiling C object girepository/girepository@@girepository-internals@sta/girparser.c.obj.
[36/98] Linking static target girepository/libgirepository-internals.a.
[37/98] Compiling C object girepository/girepository@@girepository-1.0@sha/gipropertyinfo.c.obj.

[38/98] Compiling C object girepository/girepository@@girepository-1.0@sha/giinterfaceinfo.c.obj.
[39/98] Compiling C object girepository/girepository@@girepository-1.0@sha/girepository.c.obj.
[40/98] Compiling C object girepository/girepository@@girepository-1.0@sha/giobjectinfo.c.obj.
[41/98] Compiling C object girepository/girepository@@girepository-1.0@sha/girffi.c.obj.
[42/98] Compiling C object girepository/girepository@@girepository-1.0@sha/gitypeinfo.c.obj.
[43/98] Compiling C object girepository/girepository@@girepository-1.0@sha/giunioninfo.c.obj.
[44/98] Compiling C object girepository/girepository@@girepository-1.0@sha/ginvoke.c.obj.
[45/98] Compiling C object girepository/girepository@@girepository-1.0@sha/gistructinfo.c.obj.
[46/98] Compiling C object girepository/girepository@@girepository-1.0@sha/gitypelib.c.obj.
[47/98] Compiling C object girepository/girepository@@girepository-1.0@sha/givfuncinfo.c.obj.
c:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection\girepository\givfuncinfo.c(203) : warning C4715: 'g_vfunc_info_get_invoker': not all control paths return a value

[48/98] Compiling C object girepository/girepository@@gthash-test@exe/gthash-test.c.obj.
[49/98] Generating scannerlexer with a custom command.
[50/98] Generating scannerparser with a custom command.
../gobject-introspection/giscanner/scannerparser.y: warning: 7 shift/reduce conflicts [-Wconflicts-sr]
[51/98] Compiling C object tools/tools@@g-ir-generate@exe/generate.c.obj.
[52/98] Compiling C object tools/tools@@g-ir-compiler@exe/compiler.c.obj.
[53/98] Compiling C object giscanner/giscanner@@giscanner@sta/meson-generated_.._scannerlexer.c.obj.
[54/98] Compiling C object giscanner/giscanner@@giscanner@sta/meson-generated_.._scannerparser.c.obj.
[55/98] Compiling C object giscanner/giscanner@@giscanner@sta/sourcescanner.c.obj.
[56/98] Compiling C object tools/tools@@g-ir-inspect@exe/g-ir-inspect.c.obj.
[57/98] Linking static target giscanner/libgiscanner.a.
[58/98] Compiling C object examples/examples@@glib-print@exe/glib-print.c.obj.
[59/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/bdz.c.obj.
[60/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/buffer_entry.c.obj.

[61/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/brz.c.obj.
c:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection\girepository\cmph\brz.c(813): warning C4311: 'type cast': pointer truncation from 'cmph_uint8 *' to 'cmph_uint32'
c:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection\girepository\cmph\brz.c(934): warning C4312: 'type cast': conversion from 'cmph_uint32' to 'cmph_uint8 *' of greater size
c:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection\girepository\cmph\brz.c(998): warning C4312: 'type cast': conversion from 'cmph_uint32' to 'cmph_uint8 *' of greater size
c:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection\girepository\cmph\brz.c(1033) : warning C4715: 'brz_search_packed': not all control paths return a value
[62/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/bmz8.c.obj.
[63/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/bdz_ph.c.obj.
[64/98] Compiling C object girepository/cmph/girepository@cmph@@cmph@sta/bmz.c.obj.
[65/98] Linking static target girepository/cmph/libcmph.a.
[66/98] Compiling C object giscanner/giscanner@@_giscanner@sha/giscannermodule.c.obj.
c:\cygdrive\c\jenkins\workspace\dcv-deps-build\label\windows-vs2017\gvsbuild\build\x64\debug\gobject-introspection\giscanner\giscannermodule.c(52): warning C4141: 'dllexport': used more than once
[67/98] Linking target girepository/cmph/cmph-bdz-test.exe.
[68/98] Linking target girepository/gthash-test.exe.
[69/98] Linking target giscanner/_giscanner.pyd.
   Creating library giscanner/_giscanner.lib and object giscanner/_giscanner.exp
[70/98] Linking target girepository/girepository-1.0-1.dll.
   Creating library girepository\\girepository-1.0.lib and object girepository\\girepository-1.0.exp
[71/98] Generating symbol file girepository/girepository@@girepository-1.0@sha/girepository-1.0-1.dll.symbols.

[72/98] Linking target tools/g-ir-generate.exe.
[73/98] Linking target tools/g-ir-compiler.exe.
[74/98] Linking target examples/glib-print.exe.
[75/98] Linking target tools/g-ir-inspect.exe.

[76/98] Generating gir-glib with a custom command.
FAILED: gir/GLib-2.0.gir 
"C:/Python36/python.exe" "tools/g-ir-scanner" "--output=gir/GLib-2.0.gir" "--no-libtool" "--reparse-validate" "--add-include-path" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/build/x64/debug/gobject-introspection-meson/gir" "--add-include-path" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/build/x64/debug/gobject-introspection/gir" "--identifier-prefix=G" "--symbol-prefix=g" "--symbol-prefix=glib" "--c-include=glib.h" "--namespace=GLib" "--nsversion=2.0" "--library=glib-2.0" "--library=gobject-2.0" "--external-library" "--pkg=glib-2.0" "--cflags-begin" "-IC:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0" "-IC:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/lib/glib-2.0/include" "-DGLIB_COMPILATION" "-D__G_I18N_LIB_H__" "-DGETTEXT_PACKAGE=Dummy" "--cflags-end" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/gobject/glib-types.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/lib/glib-2.0/include/glibconfig.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/galloca.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/garray.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gasyncqueue.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gatomic.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gbacktrace.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gbase64.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gbitlock.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gbookmarkfile.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gbytes.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gcharset.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gchecksum.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gconvert.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gdataset.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gdate.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gdatetime.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gdir.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/genviron.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gerror.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gfileutils.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/ggettext.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/ghash.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/ghmac.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/ghook.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/ghostutils.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gi18n-lib.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gi18n.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/giochannel.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gkeyfile.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/glist.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gmacros.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gmain.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gmappedfile.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gmarkup.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gmem.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gmessages.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gnode.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/goption.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gpattern.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gpoll.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gprimes.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gprintf.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gqsort.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gquark.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gqueue.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/grand.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gregex.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gscanner.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gsequence.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gshell.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gslice.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gslist.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gspawn.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gstdio.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gstrfuncs.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gstring.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gstringchunk.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gtestutils.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gthread.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gthreadpool.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gtimer.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gtimezone.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gtrashstack.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gtree.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gtypes.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gunicode.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gurifuncs.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gutils.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/guuid.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gvariant.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gvarianttype.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gversion.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gversionmacros.h" "C:/cygdrive/c/jenkins/workspace/dcv-deps-build/label/windows-vs2017/gvsbuild/gtk/x64/debug/include/glib-2.0/glib/gwin32.h" "../gobject-introspection/gir/glib-2.0.c"
Fatal Python error: PyThreadState_Get: no current thread

**Comment by guruDanny67** [comment]
I saw it, not for the script but for the build. You can use your regular
python to launch the script and pass the --python-dir xxx-w64 to build for
x64.

For example I use this to build the .egg/.whl for pycairo and pygobject for
python 3.5 while using the opython 3.7 for the script, something linke:
c:\dev\py370'\python build.py build .... --python-dir c:\dev\py354

I think we should add a doc dir and put some additional note in there.



Il giorno lun 27 ago 2018 alle ore 14:27 Ignacio Casal Quinteiro <
notifications@github.com> ha scritto:

**Comment by danyeaw** [comment]
I think this is now resolved.
