### ISSUE TITLE
build glib

### ISSUE THREAD

**Issue by black13** [wingtk/gvsbuild#278]
```
C:\gtk-build\github\gvsbuild>c:\Python36\python.exe .\build.py build --no-deps g
lib
Traceback (most recent call last):
  File ".\build.py", line 50, in <module>
    args.func(args)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\parser.py", line 122, in do_
build
    builder = Builder(opts)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 78, in __i
nit__
    self.__check_vs(opts)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 270, in __
check_vs
    raise Exception("'%s' could not be found. Please check you have Visual Studi
o installed at '%s' and that it supports the target platform '%s'." % (vcvars_ba
t, opts.vs_install_path, opts.platform))
Exception: 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\Auxiliary\Bui
ld\vcvars32.bat' could not be found. Please check you have Visual Studio install
ed at 'C:\Program Files (x86)\Microsoft Visual Studio 12.0' and that it supports
 the target platform 'Win32'.
```

**Comment by black13** [comment]
I was able to address this problem by using a .pro file with the following entry:
-- vs17.pro --
--vs-ver
15
--win-sdk
8.1
-c
debug
-----
and running the command
c:\Python36\python.exe .\build.py build @vs17.pro  glib

**Comment by danyeaw** [comment]
It sounds like you resolved your issue and this issue is stale.
