### ISSUE TITLE
glib (2.58.1) build failed

### ISSUE THREAD

**Issue by intity** [wingtk/gvsbuild#285]
Command line input:
```
python .\build.py build --vs-ver 15 -p x64 --vs-install-path "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community" gtk3
```

Command line output:
```
...
Building project glib (2.58.1)
(Stripping trailing CRs from patch; use --binary to disable.)
patching file glib/gwin32.c
Hunk #1 succeeded at 268 (offset 19 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file gio/gsocket.c
The Meson build system
Version: 0.47.1
Source dir: C:\gtk-build\build\x64\release\glib
Build dir: C:\gtk-build\build\x64\release\glib-meson
Build type: native build
Project name: glib
Project version: 2.58.1
Native C compiler: cl (msvc 19.15.26729)
Native C++ compiler: cl (msvc 19.15.26729)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports arguments /utf-8: YES
Compiler for C supports arguments -fno-strict-aliasing: NO
Checking if "GNU C visibility attributes test" compiles: NO
Has header "alloca.h": NO
Has header "crt_externs.h": NO
Has header "dirent.h": NO
Has header "float.h": YES
Has header "fstab.h": NO
Has header "grp.h": NO
Has header "inttypes.h": YES
Has header "limits.h": YES
Has header "linux/magic.h": NO
Has header "locale.h": YES
Has header "mach/mach_time.h": NO
Has header "memory.h": YES
Has header "mntent.h": NO
Has header "poll.h": NO
Has header "pwd.h": NO
Has header "sched.h": NO
Has header "stdint.h": YES
Has header "stdlib.h": YES
Has header "string.h": YES
Has header "strings.h": NO
Has header "sys/auxv.h": NO
Has header "sys/event.h": NO
Has header "sys/filio.h": NO
Has header "sys/inotify.h": NO
Has header "sys/mkdev.h": NO
Has header "sys/mntctl.h": NO
Has header "sys/mnttab.h": NO
Has header "sys/mount.h": NO
Has header "sys/param.h": NO
Has header "sys/resource.h": NO
Has header "sys/select.h": NO
Has header "sys/statfs.h": NO
Has header "sys/stat.h": YES
Has header "sys/statvfs.h": NO
Has header "sys/sysctl.h": NO
Has header "sys/time.h": NO
Has header "sys/times.h": NO
Has header "sys/types.h": YES
Has header "sys/uio.h": NO
Has header "sys/vfs.h": NO
Has header "sys/vfstab.h": NO
Has header "sys/vmount.h": NO
Has header "sys/wait.h": NO
Has header "termios.h": NO
Has header "unistd.h": NO
Has header "values.h": NO
Has header "xlocale.h": NO
Checking if "malloc.h" compiles: YES
Has header "linux/netlink.h": NO
Header <locale.h> has symbol "LC_MESSAGES": NO
Checking whether type "struct stat" has member "st_mtimensec" : NO
Checking whether type "struct stat" has member "st_mtim.tv_nsec" : NO
Checking whether type "struct stat" has member "st_atimensec" : NO
Checking whether type "struct stat" has member "st_atim.tv_nsec" : NO
Checking whether type "struct stat" has member "st_ctimensec" : NO
Checking whether type "struct stat" has member "st_ctim.tv_nsec" : NO
Checking whether type "struct stat" has member "st_birthtime" : NO
Checking whether type "struct stat" has member "st_birthtimensec" : NO
Checking whether type "struct stat" has member "st_birthtim" : NO
Checking whether type "struct stat" has member "st_birthtim.tv_nsec" : NO
Checking whether type "struct stat" has member "st_blksize" : NO
Checking whether type "struct stat" has member "st_blocks" : NO
Checking whether type "struct statfs" has member "f_fstypename" : NO
Checking whether type "struct statfs" has member "f_bavail" : NO
Checking whether type "struct dirent" has member "d_type" : NO
Checking whether type "struct statvfs" has member "f_basetype" : NO
Checking whether type "struct statvfs" has member "f_fstypename" : NO
Checking whether type "struct tm" has member "tm_gmtoff" : NO
Checking whether type "struct tm" has member "__tm_gmtoff" : NO
Library iphlpapi found: YES
Checking for function "if_nametoindex" : YES
Checking for function "if_indextoname" : YES
Checking for function "alloca" : NO
Checking for function "endmntent" : NO
Checking for function "endservent" : NO
Checking for function "fallocate" : NO
Checking for function "fchmod" : NO
Checking for function "fchown" : NO
Checking for function "fdwalk" : NO
Checking for function "fsync" : NO
Checking for function "getc_unlocked" : NO
Checking for function "getfsstat" : NO
Checking for function "getgrgid_r" : NO
Checking for function "getmntent_r" : NO
Checking for function "getpwuid_r" : NO
Checking for function "getresuid" : NO
Checking for function "getvfsstat" : NO
Checking for function "gmtime_r" : NO
Checking for function "hasmntopt" : NO
Checking for function "inotify_init1" : NO
Checking for function "issetugid" : NO
Checking for function "kevent" : NO
Checking for function "kqueue" : NO
Checking for function "lchmod" : NO
Checking for function "lchown" : NO
Checking for function "link" : NO
Checking for function "localtime_r" : NO
Checking for function "lstat" : NO
Checking for function "mbrtowc" : YES
Checking for function "memalign" : NO
Checking for function "mmap" : NO
Checking for function "newlocale" : NO
Checking for function "pipe2" : NO
Checking for function "poll" : NO
Checking for function "prlimit" : NO
Checking for function "readlink" : NO
Checking for function "recvmmsg" : NO
Checking for function "sendmmsg" : NO
Checking for function "setenv" : NO
Checking for function "setmntent" : NO
Checking for function "strerror_r" : NO
Checking for function "strnlen" : YES
Checking for function "strsignal" : NO
Checking for function "strtod_l" : NO
Checking for function "strtoll_l" : NO
Checking for function "strtoull_l" : NO
Checking for function "symlink" : NO
Checking for function "timegm" : NO
Checking for function "unsetenv" : NO
Checking for function "uselocale" : NO
Checking for function "utimes" : NO
Checking for function "valloc" : NO
Checking for function "vasprintf" : NO
Checking for function "vsnprintf" : NO
Checking for function "wcrtomb" : YES
Checking for function "wcslen" : YES
Checking for function "wcsnlen" : YES
Checking for function "sysctlbyname" : NO
Checking for function "_NSGetEnviron" : NO
Checking for function "splice" : NO
Checking for function "stpcpy" : NO
Checking for function "posix_memalign" : NO
Checking for function "posix_spawn" : NO
Checking for function "snprintf" : NO
Header <stdio.h> has symbol "snprintf": YES
Checking for function "strcasecmp" : NO
Checking for function "_stricmp" : YES
Checking for function "strncasecmp" : NO
Checking for function "_strnicmp" : YES
Header <sys/sysmacros.h> has symbol "major": NO
Header <sys/mkdev.h> has symbol "major": NO
Header <sys/types.h> has symbol "major": NO
Header <dlfcn.h> has symbol "RTLD_LAZY": NO
Header <dlfcn.h> has symbol "RTLD_NOW": NO
Header <dlfcn.h> has symbol "RTLD_GLOBAL": NO
Message: Checking whether to use statfs or statvfs .. neither
Checking if "futex(2) system call" links: NO
Checking if "eventfd(2) system call" links: NO
Checking if "clock_gettime" links: NO
Checking if "clock_gettime in librt" links: NO
Checking if "open() option O_DIRECTORY" compiles: NO
Checking if "nl_langinfo and CODESET" links: NO
Checking if "nl_langinfo (PM_STR)" links: NO
Checking if "nl_langinfo (_NL_CTYPE_OUTDIGITn_MB)" links: NO
Checking if "nl_langinfo (ALTMON_n)" links: NO
Checking if "nl_langinfo (_NL_ALTMON_n)" links: NO
Checking if "signed" compiles: YES
Header <stddef.h> has symbol "ptrdiff_t": YES
Checking if "sig_atomic_t" links: YES
Checking if "long long" compiles: YES
Checking if "long double" compiles: YES
Header <stddef.h> has symbol "wchar_t": YES
Header <wchar.h> has symbol "wint_t": YES
Checking if "uintmax_t in inttypes.h" compiles: YES
Checking if "uintmax_t in stdint.h" compiles: YES
Checking for size of "char": 1
Checking for size of "short": 2
Checking for size of "int": 4
Checking for size of "void*": 8
Checking for size of "long": 4
Checking for size of "long long": 8
Checking for size of "size_t": 8
Checking for size of "SSIZE_T": 8
Checking for alignment of "char" : 1
Checking for alignment of "short" : 2
Checking for alignment of "int" : 4
Checking for alignment of "void*" : 8
Checking for alignment of "long" : 4
Checking for alignment of "long long" : 8
Checking for alignment of "size_t" : 8
Checking if "__va_copy check" compiles: NO
Checking if "va_copy check" compiles: NO
Checking if "va_lists can be copied as values" runs: YES
Checking if "ISO C99 varargs macros in C" compiles: YES
Checking if "ISO C99 varargs macros in C++" compiles: YES
Checking if "GNUC varargs macros" compiles: NO
Has header "alloca.h": NO
Has header "sys/poll.h": NO
Has header "sys/types.h": YES
Has header "winsock2.h": YES
Computing int of "AF_UNIX": 1
Computing int of "AF_INET": 2
Computing int of "AF_INET6": 23
Computing int of "MSG_OOB": 1
Computing int of "MSG_PEEK": 2
Computing int of "MSG_DONTROUTE": 4
Checking if "stack grows check" runs: NO (1)
Library m found: NO
Found pkg-config: C:\gtk-build\gtk\x64\release\bin\pkg-config.EXE (1.4.0)
Native dependency libffi found: YES 3.2.1
Native dependency zlib found: YES 1.2.11
Checking for function "ngettext" : NO
Library intl found: YES
Program xgettext found: YES (C:\gtk-build\gtk\x64\release\bin\xgettext.EXE)
Library ws2_32 found: YES
Checking if "OpenBSD strlcpy/strlcat" runs: DID NOT COMPILE
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\mesonmain.py", line 351, in run
    app.generate()
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\mesonmain.py", line 117, in generate
    self._generate(env)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\mesonmain.py", line 146, in _generate
    intr.run()
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\interpreter.py", line 3675, in run
    super().run()
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\interpreterbase.py", line 377, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\interpreterbase.py", line 401, in evaluate_codeblock
    raise e
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\interpreterbase.py", line 395, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\interpreterbase.py", line 408, in evaluate_statement
    return self.assignment(cur)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\interpreterbase.py", line 937, in assignment
    value = self.evaluate_statement(node.value)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\interpreterbase.py", line 410, in evaluate_statement
    return self.method_call(cur)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\interpreterbase.py", line 732, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\interpreter.py", line 1567, in method_call
    value = fn(self.interpreter, state, args, kwargs)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\interpreterbase.py", line 162, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\modules\python.py", line 474, in find_installation
    pythonpath = self._get_win_pythonpath(name_or_path)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\modules\python.py", line 446, in _get_win_pythonpath
    _, stdout, _ = mesonlib.Popen_safe(cmd)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\mesonlib.py", line 839, in Popen_safe
    return Popen_safe_legacy(args, write=write, stdout=stdout, stderr=stderr, **kwargs)
  File "C:\gtk-build\tools\meson-0.47.1\mesonbuild\mesonlib.py", line 847, in Popen_safe_legacy
    stdout=stdout, stderr=stderr, **kwargs)
  File "C:\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 363, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 483, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 465, in build
    Meson.build(self, meson_params='-Dinternal_pcre=true')
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 67, in build
    self.exec_vs(cmd)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 98, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 708, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 740, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python36\python.exe C:\gtk-build\tools\meson-0.47.1\meson.py C:\gtk-build\build\x64\release\glib C:\gtk-build\build\x64\release\glib-meson --prefix C:\gtk-build\gtk\x64\release --buildtype release -Dinternal_pcre=true' returned non-zero exit status 2.
Error: glib build failed

C:\gtk-build\github\gvsbuild>
```

**Comment by guruDanny67** [comment]
It happens to me also but I don't understand, completely, what's happen.
I was fighting with the 8.1 windows sdk (from one day to another teh systema cannot found the winsock2.h include, probably from caused bt a vs2017 update) and I resolve installing, as a standalone package from internet, the full window 8.1 sdk.
You can also try to activate, from the vs installation, the 15.7 version (the one before the current) to see if this resolve yours issues.

With best regards

**Comment by gnieboer** [comment]
Can confirm issue with windows 10 + MSVC 2015, same exact error.  Fresh Python36/msys64 installs, using custom paths.  I'll experiment with the platforms and SDKs and report back.

**Comment by gnieboer** [comment]
Update: strlcpy was a red herring.  The real cause was running a custom python distribution that wasn't on the PATH, and so the find_installation failed.  Manually specifying the location of python.exe fixed that issue.     There were some later issues with `dirname $<` calls in the makefile that required manual creation of some subdirs, but after that glib built.

**Comment by accel2k** [comment]
Check that you have python launcher py.exe installed. It is usually located in the root folder of Windows.

**Comment by danyeaw** [comment]
I am getting this same error with the exact same setup it sounds like. I tried to specify where my python version is installed with --python-dir C:\Python37, but that didn't fix the problem for me. Did anyone else find a solution for this glib build error?

**Comment by guruDanny67** [comment]
Trying to build today and get the same error at work but compile correctly
at home.

If helps, after the check for strlcpy/strlcat the script look for bash
(that's not found at home, on my PC).

It can be something related to the Window Linux Subsystem ?

Il giorno mer 19 dic 2018 alle ore 20:30 Dan Yeaw <notifications@github.com>
ha scritto:

**Comment by danyeaw** [comment]
Well I do have bash as part of msys64. I do not have Windows Subsystem for Linux.

**Comment by accel2k** [comment]
Setting path to python with --python-dir is not enough, because meson uses python launcher (py.exe) to launch subprocesses (e.g. meson/mesonbuild/modules/python.py:445). Python launcher MUST be installed and added to PATH environment variable.

**Comment by danyeaw** [comment]
@accel2k Thanks, that fixed it for me! ❤️ 

I'll submit a PR today to update the README to add [pylauncher](https://bitbucket.org/vinay.sajip/pylauncher/downloads/) as one of the installation steps and then I think we can close this issue. It isn't part of the normal Python install for windows, and this is the first time I have heard of it despite there being [PEP](https://www.python.org/dev/peps/pep-0397/).

**Comment by intity** [comment]
@danyeaw you're right, installing python37 solves this problem.

**Comment by guruDanny67** [comment]
I open a PR on mesonbuild to continue the build, without raising an exception, if the py.exe is not found.

Hope it gets merged or we can keep that mod on our local meson copy (I don't want to install the py launcher at work, we use different 2.6, 2.7 and 3.x version so I don't have any python on the path and I active the needed one on the shell I'm using).

Other than this with this change we can simply install python locally (on c:\gtk-build\python) without touching the main environment and this can be valuable.

**Comment by guruDanny67** [comment]
My PR is been accepted so for the next release there is no need to install the pylauncher

**Comment by danyeaw** [comment]
Thanks everyone for your troubleshooting efforts so far!

Maybe this is a new issue, but I am still getting a very similar error:
1. With and without pylauncher
2. With and without being in a virtualenv
3. With and without specifying the --python-dir
4. With mesonbuild 0.49.0 and with mesonbuild 0.49.2 which was released 3 days ago and should contain @guruDanny67's merged PR to correct the issues with pylauncher

```
RuntimeError: Tried to install something that isn't a file:'C:\\gtk-build\\build\\x64\\release\\glib\\glib\\gtester-report'
Traceback (most recent call last):
  File "C:\Users\DYEAW\Projects\gvsbuild\gvsbuild\utils\builder.py", line 458, in build
    if self.__build_one(p):
  File "C:\Users\DYEAW\Projects\gvsbuild\gvsbuild\utils\builder.py", line 580, in __build_one
    skip_deps = proj.build()
  File "C:\Users\DYEAW\Projects\gvsbuild\gvsbuild\projects.py", line 445, in build
    Meson.build(self, meson_params='-Dinternal_pcre=true')
  File "C:\Users\DYEAW\Projects\gvsbuild\gvsbuild\utils\base_builders.py", line 78, in build
    self.builder.exec_ninja(params='install', working_dir=ninja_build)
  File "C:\Users\DYEAW\Projects\gvsbuild\gvsbuild\utils\builder.py", line 818, in exec_ninja
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\Users\DYEAW\Projects\gvsbuild\gvsbuild\utils\builder.py", line 847, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: glib build failed
```
C:\gtk-build\build\x64\release\glib does not contain gtester-report

Anyone have any further ideas?

**Comment by guruDanny67** [comment]
The 0.49.2 meson release doesn't have my PR, we have to wait for the 0.50 release :(

The gtester-report is a python3 script (without .py extension) created by meson during the glib preparation and is copied to the gtk bin dir if everything is ok.

You can see if it's present in the build/x64/release/glib.meson/glib (in the source tarball is present only the gtester-report.in).

Hope this helps

**Comment by danyeaw** [comment]
@guruDanny67 I do not have a gtester-report file in C:\gtk-build\build\x64\release\glib.meson\glib

**Comment by danyeaw** [comment]
So I realized that gvsbuild was pulling in meson-0.47.1 (instead of 0.49.2) which had been previously downloaded in my gtk-build directory. Is this expected that it doesn't update the versions automatically?

After deleting my gtk-build directory, I got my first successful gvsbuild 🎉

**Comment by guruDanny67** [comment]
There is a file in the extracted dir (.wingtk-extracted-file) that contains the tar/zip file used, if something changes the script should force the extraction of the new file (say if ninja goes from 1.7.2 to 1.8.2).

For meson the tarfile is extracted in a directory with the name (e.g. meson-0.49.2) so this should not be a problem, apart from having a couple of version of meson.

**Comment by danyeaw** [comment]
We are now using meson 0.57.1, and this should no longer be an issue.
