### ISSUE TITLE
meson cannot find the compiler

### ISSUE THREAD

**Issue by behrisch** [wingtk/gvsbuild#307]
I already tried to add the visual studio bin dir to the path and also to set the visual studio version explicitly in the startup of the script, with the same result. I am using Visual Studio Professional 2013 This is the log:
```
C:\gtk-build\github\gvsbuild>c:\python36\python .\build.py build -p x64 gtk3
Cleaning up the build environment
Checking msys tool
Checking Msvc tool
Downloading packages
Building project ninja (1.8.2)
Building project meson (0.49.0)
Building project pkg-config (git/pkgconf-1.5.4)
(git) Updating directory C:\gtk-build\build\x64\release\pkgconf
Removing 0001-vs2013.patch
Removing 0001-vs2013.patch.patch-applied
HEAD is now at 74133ed... pkgconf 1.5.4.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file libpkgconf/bsdstubs.c
(Stripping trailing CRs from patch; use --binary to disable.)
patching file libpkgconf/libpkgconf.h
The Meson build system
Version: 0.49.0
Source dir: C:\gtk-build\build\x64\release\pkgconf
Build dir: C:\gtk-build\build\x64\release\pkgconf-meson
Build type: native build
Project name: pkgconf
Project version: 1.4.0

meson.build:1:0: ERROR:  Unknown compiler(s): ['cl', 'cc', 'gcc', 'clang', 'clan
g-cl']
The follow exceptions were encountered:
Running "cl /?" gave "[WinError 2] Das System kann die angegebene Datei nicht fi
nden"
Running "cc --version" gave "[WinError 2] Das System kann die angegebene Datei n
icht finden"
Running "gcc --version" gave "[WinError 2] Das System kann die angegebene Datei
nicht finden"
Running "clang --version" gave "[WinError 2] Das System kann die angegebene Date
i nicht finden"
Running "clang-cl /?" gave "[WinError 2] Das System kann die angegebene Datei ni
cht finden"

A full log can be found at C:\gtk-build\build\x64\release\pkgconf-meson\meson-lo
gs\meson-log.txt
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 458, in bu
ild
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 580, in __
build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 1543, in build
    Meson.build(self)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 68,
in build
    self.exec_vs(cmd)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 106,
in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_
path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 807, in ex
ec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_p
ath, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 847, in __
execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "c:\python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'c:\python36\python.exe C:\gtk-build\tool
s\meson-0.49.0\meson.py C:\gtk-build\build\x64\release\pkgconf C:\gtk-build\buil
d\x64\release\pkgconf-meson --prefix C:\gtk-build\gtk\x64\release -Dtests=false
--buildtype release' returned non-zero exit status 1.
Error: pkg-config build failed
```

**Comment by guruDanny67** [comment]
It can be a misconfigured visual studio installation.

Try to update the script: the only change is the log of the command used to activate the msvc environment (something like 'c:\program files (x86)\Microsoft\Visual studio 2017\Professional\tools\vcvar64.bat').

Then run the script with the -d or -v option (before the build command) and look at this command and try to run it in a command prompt to see what's happening, if this give errors or something.

Hope this help, with best regards
    Daniele Forghieri

**Comment by behrisch** [comment]
Thank you. The problem seems to be that this visual studio batch script relies heavily on "reg.exe" to query the windows registry. Unfortunately our IT department does not allow the usage of reg.

**Comment by behrisch** [comment]
I got a step further now on a different machine which allows reg.
