### ISSUE TITLE
Build fails due to space in path

### ISSUE THREAD

**Issue by software4hire** [wingtk/gvsbuild#308]
Using visual studio 2015

python .\build.py -v -d build -p x64 gtk3 --vs-install-path "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0"

Build is failing on space in path "'C:\Program' is not recognized as an internal or external command"

Output:
....
patching file libpkgconf/bsdstubs.c
patching file libpkgconf/libpkgconf.h
Generating meson directory
Debug: running C:\Program Files\Python36\python.exe C:\gtk-build\tools\meson-0.49.0\meson.py C:\gtk-build\build\x64\release\pkgconf C:\gtk-build\build\x64\release\pkgconf-meson --prefix C:\gtk-build\gtk\x64\release -Dtests=false --buildtype release, cwd=C:\gtk-build\build\x64\release\pkgconf, path+=None
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\temp\gvsbuild\gvsbuild-master\gvsbuild\utils\builder.py", line 459, in build
    if self.__build_one(p):
  File "C:\temp\gvsbuild\gvsbuild-master\gvsbuild\utils\builder.py", line 581, in __build_one
    skip_deps = proj.build()
  File "C:\temp\gvsbuild\gvsbuild-master\gvsbuild\projects.py", line 1543, in build
    Meson.build(self)
  File "C:\temp\gvsbuild\gvsbuild-master\gvsbuild\utils\base_builders.py", line 68, in build
    self.exec_vs(cmd)
  File "C:\temp\gvsbuild\gvsbuild-master\gvsbuild\utils\base_project.py", line 106, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\temp\gvsbuild\gvsbuild-master\gvsbuild\utils\builder.py", line 808, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\temp\gvsbuild\gvsbuild-master\gvsbuild\utils\builder.py", line 848, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Program Files\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Program Files\Python36\python.exe C:\gtk-build\tools\meson-0.49.0\meson.py C:\gtk-build\build\x64\release\pkgconf C:\gtk-build\build\x64\release\pkgconf-meson --prefix C:\gtk-build\gtk\x64\release -Dtests=false --buildtype release' returned non-zero exit status 1.
Error: pkg-config build failed

Any suggestions ?

Thanks!

**Comment by software4hire** [comment]
Also tried specifying python path using:  --python-dir "C:\Program Files\Python36" did not work

**Comment by software4hire** [comment]
Reinstalled python to C:\python36 got me past this problem.

**Comment by software4hire** [comment]
Re-installed python to C:\python36 got me past this step.
