### ISSUE TITLE
build fails with git

### ISSUE THREAD

**Issue by pquiring** [wingtk/gvsbuild#309]
Scripts could not find VS so I had to use --vs-ver option.

Scripts did not check for git in MSYS2 so I had to install it manually.

But now I get this error:

```
Cleaning up the build environment
Checking msys tool
Checking Msvc tool
Downloading packages
Building project ninja (1.8.2)
Building project meson (0.49.0)
Building project pkg-config (git/pkgconf-1.5.4)
(git) Cloning https://github.com/pkgconf/pkgconf.git to C:\gtk-build\build\x64\release\pkgconf
Cloning into '/c/gtk-build/build/x64/release/pkgconf-tmp'...
fatal: BUG: disabling cancellation: Invalid argument
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 459, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 553, in __build_one
    proj.prepare_build_dir()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 198, in prepare_build_dir
    self.unpack()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_expanders.py", line 221, in unpack
    self.builder.exec_msys('git clone %s %s-tmp' % (self.repo_url, self.build_dir))
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 838, in exec_msys
    self.__execute(args, working_dir=working_dir, add_path=os.path.join(self.opts.msys_dir, 'usr', 'bin'))
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 848, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git clone https://github.com/pkgconf/pkgconf.git C:\gtk-build\build\x64\release\pkgconf-tmp' returned non-zero exit status 128.
Error: pkg-config build failed

```

My command line : \Python36\python.exe .\build.py build -p x64 gtk3-full --vs-ver 16

**Comment by pquiring** [comment]
Found this bug : https://github.com/msys2/MINGW-packages/issues/3351
which someone says to keep msys2.exe running in another window and then git works.
Now I get this error:

```
The Meson build system
Version: 0.49.0
Source dir: C:\gtk-build\build\x64\release\pkgconf
Build dir: C:\gtk-build\build\x64\release\pkgconf-meson
Build type: native build
Project name: pkgconf
Project version: 1.4.0
Native C compiler: cl (msvc 19.20.27404)
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.49.0\mesonbuild\mesonmain.py", line 111, in run
    return options.run_func(options)
  File "C:\gtk-build\tools\meson-0.49.0\mesonbuild\msetup.py", line 217, in run
    app.generate()
  File "C:\gtk-build\tools\meson-0.49.0\mesonbuild\msetup.py", line 148, in generate
    self._generate(env)
  File "C:\gtk-build\tools\meson-0.49.0\mesonbuild\msetup.py", line 165, in _generate
    intr = interpreter.Interpreter(b)
  File "C:\gtk-build\tools\meson-0.49.0\mesonbuild\interpreter.py", line 1944, in __init__
    self.build.environment.machines.detect_build(self.coredata.compilers)
  File "C:\gtk-build\tools\meson-0.49.0\mesonbuild\environment.py", line 1338, in detect_build
    self.build = MachineInfo.detect(compilers)
  File "C:\gtk-build\tools\meson-0.49.0\mesonbuild\environment.py", line 1221, in detect
    detect_cpu_family(compilers) if compilers is not None else None,
  File "C:\gtk-build\tools\meson-0.49.0\mesonbuild\environment.py", line 231, in detect_cpu_family
    trial = detect_windows_arch(compilers)
  File "C:\gtk-build\tools\meson-0.49.0\mesonbuild\environment.py", line 185, in detect_windows_arch
    if float(compiler.get_toolset_version()) < 10.0:
TypeError: float() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 459, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 581, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 1543, in build
    Meson.build(self)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 68, in build
    self.exec_vs(cmd)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 106, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 808, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 848, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python36\python.exe C:\gtk-build\tools\meson-0.49.0\meson.py C:\gtk-build\build\x64\release\pkgconf C:\gtk-build\build\x64\release\pkgconf-meson --prefix C:\gtk-build\gtk\x64\release -Dtests=false --buildtype release' returned non-zero exit status 2.
Error: pkg-config build failed

```

**Comment by pquiring** [comment]
I tried again with --vs-ver=15 and it seems to be working now.  I guess VS2019 is not supported by meson yet.  
Just needed to have msys2.exe running in another Window to fix that git problem.
Thanks,

**Comment by guruDanny67** [comment]
Now with meson 0.50 the vs2019 preview should work, I don't know if for all the projects but a lot are ok.

I think also that you should install git for windows to avoid this problem. 

We should probably update the docs to say that you need git (it may be obvious because you clone the repository to have the script but is better one note more than one less).

**Comment by danyeaw** [comment]
The README now has instructions to install Git for Windows, I think this can be closed.
