### ISSUE TITLE
libffi build failure for platform x64

### ISSUE THREAD

**Issue by jensgoe** [wingtk/gvsbuild#322]
building for platform x64 fails for libffi dependency:

```txt
Building project libffi (git/meson-1.14)
(git) Updating directory C:\gtk-build\build\x64\release\libffi
Removing 001-rename-debug-to-ffi-debug.patch
Removing 001-rename-debug-to-ffi-debug.patch.patch-applied
Already on 'meson-1.14'
Your branch is up to date with 'origin/meson-1.14'.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file meson.build
(Stripping trailing CRs from patch; use --binary to disable.)
patching file meson_options.txt
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/meson.build
[0/1] Regenerating build files.
The Meson build system
Version: 0.50.0
Source dir: C:\gtk-build\build\x64\release\libffi
Build dir: C:\gtk-build\build\x64\release\libffi-meson
Build type: native build
Project name: libffi
Project version: 3.2.1
Native C compiler: cl (msvc 19.16.27024.1)
Build machine cpu family: x86
Build machine cpu: x86
Message: host cpu: x86
Message: host cpu_family: x86
Message: host system: windows
Checking if "ASM .cfi" compiles: NO
Checking if "ASM x86 PCREL" compiles: NO
Checking if "ASM .ascii" compiles: NO
Checking if "ASM .string" compiles: NO
Checking for size of "size_t" : 8
Checking for size of "long double" : 8
Checking for size of "double" : 8
Checking for function "mmap" : NO
Checking if "mmap anonymous" compiles: NO
Checking for function "alloca" : NO
Checking for function "memcpy" : YES
Checking for function "mkostemp" : NO
Has header "alloca.h" : NO
Has header "inttypes.h" : YES
Has header "stdint.h" : YES
Program msvcc.sh found: YES (sh C:\gtk-build\build\x64\release\libffi\msvcc.sh)
Configuring libffi.pc using configuration
meson.build:200: WARNING: The variable(s) 'toolexeclibdir' in the input file 'libffi.pc.in' are not present in the given configuration data.
Program cl found: YES (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.EXE)
Program ml found: NO
Program ml64 found: YES (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\ml64.EXE)
Configuring ffi-x86.h using configuration
include\meson.build:2: WARNING: The variable(s) 'VERSION' in the input file 'include\ffi.h.in' are not present in the given configuration data.
Configuring ffitarget-x86.h using configuration
include\meson.build:9: WARNING: Got an empty configuration_data() object and found no substitutions in the input file 'ffitarget.h'. If you want to copy a file to the build dir, use the 'copy:' keyword argument added in 0.47.0
Configuring ffitarget.h using configuration
Configuring ffi.h using configuration
Configuring fficonfig.h using configuration
Build targets in project: 3
Option buildtype is: release [default: debugoptimized]
Found ninja-1.8.2 at 'C:\gtk-build\tools\ninja-1.8.2\ninja.EXE'
[1/10] Compiling C object src/25a6634@@ffi@sha/x86_ffiw64.c.obj.
FAILED: src/25a6634@@ffi@sha/x86_ffiw64.c.obj
cl @src/25a6634@@ffi@sha/x86_ffiw64.c.obj.rsp
include\ffi.h(10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "ffi-x86_64.h": No such file or directory
[2/10] Compiling C object src/25a6634@@ffi@sha/java_raw_api.c.obj.
FAILED: src/25a6634@@ffi@sha/java_raw_api.c.obj
cl @src/25a6634@@ffi@sha/java_raw_api.c.obj.rsp
include\ffi.h(10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "ffi-x86_64.h": No such file or directory
[3/10] Compiling C object src/25a6634@@ffi@sha/closures.c.obj.
FAILED: src/25a6634@@ffi@sha/closures.c.obj
cl @src/25a6634@@ffi@sha/closures.c.obj.rsp
include\ffi.h(10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "ffi-x86_64.h": No such file or directory
[4/10] Compiling C object src/25a6634@@ffi@sha/raw_api.c.obj.
FAILED: src/25a6634@@ffi@sha/raw_api.c.obj
cl @src/25a6634@@ffi@sha/raw_api.c.obj.rsp
include\ffi.h(10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "ffi-x86_64.h": No such file or directory
[5/10] Compiling C object src/25a6634@@ffi@sha/types.c.obj.
FAILED: src/25a6634@@ffi@sha/types.c.obj
cl @src/25a6634@@ffi@sha/types.c.obj.rsp
include\ffi.h(10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "ffi-x86_64.h": No such file or directory
[6/10] Compiling C object src/25a6634@@ffi@sha/prep_cif.c.obj.
FAILED: src/25a6634@@ffi@sha/prep_cif.c.obj
cl @src/25a6634@@ffi@sha/prep_cif.c.obj.rsp
include\ffi.h(10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "ffi-x86_64.h": No such file or directory
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 477, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 599, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 973, in build
    Meson.build(self)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 80, in build
    self.builder.exec_ninja(params='install', working_dir=ninja_build)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 850, in exec_ninja
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 879, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 347, in check_call
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: libffi build failed
```

building for x86 works

**Comment by jensgoe** [comment]
The used command was:
`python build.py build --enable-gi --vs-ver 15 -p x64 gtk3`

**Comment by Voskrese** [comment]
port meson no problem
https://gitlab.freedesktop.org/gstreamer/meson-ports/libffi

**Comment by Voskrese** [comment]
@nacho 

`-p x64`

`E:\tools\tools\python\python3\python.exe .\build.py build -c debug --python-dir E:\tools\tools\python\python3 --vs-ver 15 --msys-dir I:\msys2 -p x64 --use-env --enable-gi gobject-introspection`

```
Ветка «meson-1.14» отслеживает внешнюю ветку «meson-1.14» из «origin» перемещением.
patching file meson.build
patching file meson_options.txt
patching file src/meson.build
The Meson build system
Version: 0.50.0
Source dir: C:\gtk-build\build\x64\debug\libffi
Build dir: C:\gtk-build\build\x64\debug\libffi-meson
Build type: native build
Project name: libffi
Project version: 3.2.1
Native C compiler: cl (msvc 19.16.27032.1)
Build machine cpu family: x86
Build machine cpu: x86
Message: host cpu: x86
Message: host cpu_family: x86
Message: host system: windows
Checking if "ASM .cfi" compiles: NO
Checking if "ASM x86 PCREL" compiles: NO
Checking if "ASM .ascii" compiles: NO
Checking if "ASM .string" compiles: NO
Checking for size of "size_t" : 8
Checking for size of "long double" : 8
Checking for size of "double" : 8
```

```
Build machine cpu family: x86
Build machine cpu: x86
Message: host cpu: x86
Message: host cpu_family: x86
```

error

**Comment by accel2k** [comment]
Hi. This is the same error - https://github.com/mesonbuild/meson/pull/6265/commits/b5d8f758fa6e455157789ef578b21b767b06508e. As a workaround remove russian language pack for Visual Studio and install english one. This is worked for me. Meson upgrade to 0.53.x is needed.

**Comment by Voskrese** [comment]
fixed it, you can safely close it

**Comment by Zueuk** [comment]
Had the same problem, removed the russian language pack - now it fails on `libxml2` with a huge python error that does not seem to say anything useful...
