### ISSUE TITLE
glib build failed

### ISSUE THREAD

**Issue by dx12346789** [wingtk/gvsbuild#363]
Unable to locate program input point iconv on dynamic link library F: \ gtk-win32-uild \ GTK \ Win32 \ release \ bin \ intl.dll

```
Building project glib (2.64.2)
[3/222] Generating test_resources2.c with a meson_exe.py custom command.
FAILED: gio/tests/test_resources2.c
"F:/gtk-win32-build/tools/pythonx86.3.7.7/tools/python.exe" "F:/gtk-win32-build/tools/meson-0.52.0/meson.py" "--internal" "exe" "--unpickle" "F:/gtk-win32-build/build/Win32/release/glib/_gvsbuild-meson/meson-private/meson_exe_glib-compile-resources_336885c244668b32b6ad0dbb1478494419a36d69.dat"
[4/222] Generating test.gresource with a meson_exe.py custom command.
FAILED: gio/tests/test.gresource
"F:/gtk-win32-build/tools/pythonx86.3.7.7/tools/python.exe" "F:/gtk-win32-build/tools/meson-0.52.0/meson.py" "--internal" "exe" "--unpickle" "F:/gtk-win32-build/build/Win32/release/glib/_gvsbuild-meson/meson-private/meson_exe_glib-compile-resources_61ce2ff1f3c5c023bf5af9a175d21ec0efa64fd2.dat"
[5/222] Generating plugin-resources.c with a meson_exe.py custom command.
FAILED: gio/tests/plugin-resources.c
"F:/gtk-win32-build/tools/pythonx86.3.7.7/tools/python.exe" "F:/gtk-win32-build/tools/meson-0.52.0/meson.py" "--internal" "exe" "--unpickle" "F:/gtk-win32-build/build/Win32/release/glib/_gvsbuild-meson/meson-private/meson_exe_glib-compile-resources_6c3698083c4b5d1dc370f325876cc40a2ed25554.dat"
[6/222] Generating test_resources.c with a meson_exe.py custom command.
FAILED: gio/tests/test_resources.c
"F:/gtk-win32-build/tools/pythonx86.3.7.7/tools/python.exe" "F:/gtk-win32-build/tools/meson-0.52.0/meson.py" "--internal" "exe" "--unpickle" "F:/gtk-win32-build/build/Win32/release/glib/_gvsbuild-meson/meson-private/meson_exe_glib-compile-resources_294f8469cc7b4b6ffcb211e352a909a50f64cb5c.dat"
[7/222] Generating test_resources2.h with a meson_exe.py custom command.
FAILED: gio/tests/test_resources2.h
"F:/gtk-win32-build/tools/pythonx86.3.7.7/tools/python.exe" "F:/gtk-win32-build/tools/meson-0.52.0/meson.py" "--internal" "exe" "--unpickle" "F:/gtk-win32-build/build/Win32/release/glib/_gvsbuild-meson/meson-private/meson_exe_glib-compile-resources_958089117da65c06f016b68e4953922ea006b067.dat"
[8/222] Generating digit_test_resources.h with a meson_exe.py custom command.
FAILED: gio/tests/digit_test_resources.h
"F:/gtk-win32-build/tools/pythonx86.3.7.7/tools/python.exe" "F:/gtk-win32-build/tools/meson-0.52.0/meson.py" "--internal" "exe" "--unpickle" "F:/gtk-win32-build/build/Win32/release/glib/_gvsbuild-meson/meson-private/meson_exe_glib-compile-resources_4372eefcec9ca41519a4e80bd1aa554d5cf71daf.dat"
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "F:\gvsbuild-master\gvsbuild-master\gvsbuild\utils\builder.py", line 480, in build
    if self.__build_one(p):
  File "F:\gvsbuild-master\gvsbuild-master\gvsbuild\utils\builder.py", line 606, in __build_one
    skip_deps = proj.build()
  File "F:\gvsbuild-master\gvsbuild-master\gvsbuild\projects.py", line 468, in build
    Meson.build(self, meson_params='-Dinternal_pcre=true')
  File "F:\gvsbuild-master\gvsbuild-master\gvsbuild\utils\base_builders.py", line 76, in build
    self.builder.exec_ninja(params='install', working_dir=ninja_build)
  File "F:\gvsbuild-master\gvsbuild-master\gvsbuild\utils\builder.py", line 882, in exec_ninja
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "F:\gvsbuild-master\gvsbuild-master\gvsbuild\utils\builder.py", line 922, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: glib build failed
```

**Comment by dx12346789** [comment]
I modified the file encoding with vs2013 : Unicode (UTF-8 with signature) code page 65001
