### ISSUE TITLE
libcroco fails to build with VS 2015

### ISSUE THREAD

**Issue by jendrikseipp** [wingtk/gvsbuild#366]
For the following setup 

```
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VER: "14"
      PLATFORM: "x86"
      PYTHON: C:\Python36\python.exe
```

I get the error messages

```
Building project libcroco (0.6.13)
Checking for 'C:\gtk-build\build\Win32\release\libcroco\build\win32\vs14\libcroco.sln'
Checking for 'C:\gtk-build\build\Win32\release\libcroco\build\win32\vs2015\libcroco.sln'
Checking for 'C:\gtk-build\build\Win32\release\libcroco\build\win32\vs12\libcroco.sln'
Checking for 'C:\gtk-build\build\Win32\release\libcroco\build\win32\vs2013\libcroco.sln'
* Removing libcroco dependents ...
* > Removing librsvg for libcroco ...
* Removing librsvg dependents ...
* > Removing adwaita-icon-theme for librsvg ...
* Removing adwaita-icon-theme dependents ...
```
and 

```
Error: Solution file 'libcroco.sln' for project 'libcroco' not found!
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 480, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 606, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 1056, in build
    self.exec_msbuild_gen(r'build\win32', 'libcroco.sln')
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 230, in exec_msbuild_gen
    log.error_exit("Solution file '%s' for project '%s' not found!" % (sln_file, self.name, ))
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\simple_ui.py", line 271, in error_exit
    sys.exit(1)
SystemExit: 1
```

Do you have any advice on how to fix this?

**Comment by guruDanny67** [comment]
The new version moves the window builds file from build\win32 to win32 so the scripts doesn't find the solution because in the old dir there is only the vs15 version (vs2017) and the vs2019 is made from that.

I'm working on a patch to fix the issue

**Comment by guruDanny67** [comment]
I put a commit that should fix the problem. If it's ok close the issue, thanks.

**Comment by jendrikseipp** [comment]
Your commit fixed the issue, thank you very much!
