### ISSUE TITLE
Fail to build harfbuzz as part of building gtk

### ISSUE THREAD

**Issue by evanrinehart** [wingtk/gvsbuild#369]
I need gtk2 for windows so issued the command `py .\build.py build -p x64 gtk`. Things went smoothly until harfbuzz came up.

```
Building project harfbuzz (2.6.4)
-- The C compiler identification is MSVC 18.0.40629.0
-- The CXX compiler identification is MSVC 18.0.40629.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/gtk-build/tools/python.3.7.7/tools/python.exe (found version "3.7.7")
-- Looking for atexit
-- Looking for atexit - found
-- Looking for mprotect
-- Looking for mprotect - not found
-- Looking for sysconf
-- Looking for sysconf - not found
-- Looking for getpagesize
-- Looking for getpagesize - not found
-- Looking for mmap
-- Looking for mmap - not found
-- Looking for isatty
-- Looking for isatty - found
-- Looking for newlocale
-- Looking for newlocale - not found
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Looking for roundf
-- Looking for roundf - found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - not found
-- Looking for xlocale.h
-- Looking for xlocale.h - not found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Found Freetype: C:/gtk-build/gtk/x64/release/lib/freetype.lib (found version "2.9.0")
-- Looking for FT_Get_Var_Blend_Coordinates
-- Looking for FT_Get_Var_Blend_Coordinates - found
-- Looking for FT_Set_Var_Blend_Coordinates
-- Looking for FT_Set_Var_Blend_Coordinates - found
-- Looking for FT_Done_MM_Var
-- Looking for FT_Done_MM_Var - found
-- Found PkgConfig: C:/gtk-build/gtk/x64/release/bin/pkg-config.exe (found version "1.4.0")
-- Could NOT find Perl (missing:  PERL_EXECUTABLE)
C:/gtk-build/gtk/x64/release/bin/glib-mkenums is a Python script.
Building introspection files on Windows requires BUILD_SHARED_LIBS to be enabled.
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    GTK_DIR


-- Build files have been written to: C:/gtk-build/build/x64/release/harfbuzz/_gvsbuild-cmake
[1/95] Building CXX object CMakeFiles\harfbuzz.dir\src\harfbuzz.cc.obj
FAILED: CMakeFiles/harfbuzz.dir/src/harfbuzz.cc.obj
C:\PROGRA~2\MICROS~2.0\VC\bin\amd64\cl.exe   /nologo /TP -DHAVE_ATEXIT -DHAVE_FREETYPE=1 -DHAVE_FT_DONE_MM_VAR -DHAVE_FT_GET_VAR_BLEND_COORDINATES -DHAVE_FT_SET_VAR_BLEND_COORDINATES -DHAVE_GLIB -DHAVE_ISATTY -DHAVE_ROUNDF -DHAVE_STDBOOL_H -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -Isrc -I..\src -IC:\gtk-build\gtk\x64\release\include\freetype2 -IC:\gtk-build\gtk\x64\release\lib\glib-2.0\include -IC:\gtk-build\gtk\x64\release\include\glib-2.0 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /Zi /O2 /Ob1 /DNDEBUG   -wd4244 -wd4267 /showIncludes /FoCMakeFiles\harfbuzz.dir\src\harfbuzz.cc.obj /FdCMakeFiles\harfbuzz.dir\ /FS -c C:\gtk-build\build\x64\release\harfbuzz\src\harfbuzz.cc
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(47) : error C2146: syntax error : missing ';' before identifier 'T'
        c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(47) : see reference to class template instantiation 'hb_integral_constant<T,v>' being compiled
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(47) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(83) : error C2146: syntax error : missing ';' before identifier 'T'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(83) : error C2238: unexpected token(s) preceding ';'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(93) : error C2143: syntax error : missing ';' before '<end Parse>'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(93) : error C2988: unrecognizable template declaration/definitionc:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(93) : error C2059: syntax error : '<end Parse>'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(94) : error C2143: syntax error : missing ';' before '}'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(94) : error C2238: unexpected token(s) preceding ';'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(141) : error C2144: syntax error : 'bool' should be preceded by ';'
        c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(156) : see reference to class template instantiation 'hb_is_convertible<From,To>' being compiled
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(141) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(142) : error C2144: syntax error : 'bool' should be preceded by ';'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(142) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(142) : error C2086: 'int hb_is_convertible<From,To>::constexpr' : redefinition
        c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(141) : see declaration of 'hb_is_convertible<From,To>::constexpr'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(143) : error C2144: syntax error : 'bool' should be preceded by ';'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(143) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(143) : error C2086: 'int hb_is_convertible<From,To>::constexpr' : redefinition
        c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(141) : see declaration of 'hb_is_convertible<From,To>::constexpr'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(144) : error C2144: syntax error : 'bool' should be preceded by ';'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(144) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(144) : error C2086: 'int hb_is_convertible<From,To>::constexpr' : redefinition
        c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(141) : see declaration of 'hb_is_convertible<From,To>::constexpr'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(146) : error C2327: 'hb_is_convertible<From,To>::to_void' : is not a type name, static, or enumerator
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(146) : error C2065: 'to_void' : undeclared identifier
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(153) : error C2144: syntax error : 'bool' should be preceded by ';'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(153) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(153) : error C2086: 'int hb_is_convertible<From,To>::constexpr' : redefinition
        c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(141) : see declaration of 'hb_is_convertible<From,To>::constexpr'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(155) : error C2327: 'hb_is_convertible<From,To>::from_void' : is not a type name, static, or enumerator
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(155) : error C2065: 'from_void' : undeclared identifier
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(174) : error C2143: syntax error : missing ';' before '<template-id>'
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(174) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(174) : error C2065: 'T' : undeclared identifier
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(174) : error C2065: 't' : undeclared identifier
c:\gtk-build\build\x64\release\harfbuzz\src\hb-meta.hh(174) : error C2143: syntax error : missing ';' before '<end Parse>'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 487, in build
    if self.__build_one(p):
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 613, in __build_one
    skip_deps = proj.build()
  File "c:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 901, in build
    CmakeProject.build(self, cmake_params='-DHB_HAVE_FREETYPE=ON -DHB_HAVE_GLIB=ON -DHB_HAVE_GOBJECT=ON', use_ninja=True)
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 120, in build
    self.builder.exec_ninja(params='install', working_dir=work_dir)
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 897, in exec_ninja
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 937, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: harfbuzz build failed
```

I looked at the c++ files implicated in the "syntax error". I see no obvious missing semi-colons but there is significant preprocessing going on leading up to this point.

**Comment by guruDanny67** [comment]
It seems you are using visual studio 2013 and this gives you the error on harfbuzz.

If you can upgrade your visual studio to at least the 2015 version it will work (I tested with the 32 bit version), otherwise you need to use an older harfbuzz version.

With best regards

**Comment by evanrinehart** [comment]
Ah yes. I actually downgraded from 2019 because of this error message at the beginning of the build script:

```
c:\gtk-build\github\gvsbuild>py build.py build gtk
Cleaning up the build environment
Checking msys tool
Checking Msvc tool
Error:
  'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\Auxiliary\Build\vcvars32.bat' could not be found.
  Please check you have Visual Studio installed at 'C:\Program Files (x86)\Microsoft Visual Studio 12.0'
  and that it supports the target platform 'Win32'.
```

where 12.0 corresponds to visual studio 2013. I just tried your suggestion and installed visual studio 2015, which corresponds to 'C:\Program Files (x86)\Microsoft Visual Studio 14.0', but the script still refuses to run, giving the above message. Simply renaming that directory to 'Microsoft Visual Studio 12.0' in an attempt to fake things out failed. Indeed 'VC\Auxiliary\Build\vcvars32.bat' is not a thing in VS 2015 / 14.0.

So far the most success I've had here was with Visual Studio 2013 as prescribed by the latest build script.

**Comment by petersasi** [comment]
I still use 2019 just symlink / copy the bat file into the other location - built for me flawlessly.

**Comment by evanrinehart** [comment]
Good call with the plan to symlink "C:\Program Files (x86)\Microsoft Visual Studio 12.0" to the location of VS 2019. The build script accepts this and gets through several dependency packages successfully. However it quickly barfs when building gettext:

```
c:\gtk-build\github\gvsbuild>py build.py build gtk
Cleaning up the build environment
Checking msys tool
Checking Msvc tool
Downloading packages
Building project nuget (5.4.0)
Building project python ()
Building project ninja (1.8.2)
Building project meson (0.52.0)
(git) Updating directory C:\gtk-build\src\git-exp\pkg-config
HEAD is now at 74133ed pkgconf 1.5.4.
Building project pkg-config (git/pkgconf-1.5.4)
[0/1] Installing files.
Installing pkgconf-3.dll to C:\gtk-build\gtk\Win32\release\bin
Installing pkgconf-3.pdb to C:\gtk-build\gtk\Win32\release\bin
Installing pkgconf.lib to C:\gtk-build\gtk\Win32\release\lib
Installing pkgconf.pdb to C:\gtk-build\gtk\Win32\release\lib
Installing pkgconf.exe to C:\gtk-build\gtk\Win32\release\bin
Installing pkgconf.pdb to C:\gtk-build\gtk\Win32\release\bin
Installing C:\gtk-build\build\Win32\release\pkgconf\libpkgconf\libpkgconf.h to C:\gtk-build\gtk\Win32\release\include\libpkgconf
Installing C:\gtk-build\build\Win32\release\pkgconf\libpkgconf\stdinc.h to C:\gtk-build\gtk\Win32\release\include\libpkgconf
Installing C:\gtk-build\build\Win32\release\pkgconf\libpkgconf\iter.h to C:\gtk-build\gtk\Win32\release\include\libpkgconf
Installing C:\gtk-build\build\Win32\release\pkgconf\libpkgconf\bsdstubs.h to C:\gtk-build\gtk\Win32\release\include\libpkgconf
Installing C:\gtk-build\build\Win32\release\pkgconf\libpkgconf\libpkgconf-api.h to C:\gtk-build\gtk\Win32\release\include\libpkgconf
Installing C:\gtk-build\build\Win32\release\pkgconf\man/pkgconf.1 to C:\gtk-build\gtk\Win32\release\share/man\man1
Installing C:\gtk-build\build\Win32\release\pkgconf\man/pkg.m4.7 to C:\gtk-build\gtk\Win32\release\share/man\man7
Installing C:\gtk-build\build\Win32\release\pkgconf\man/pc.5 to C:\gtk-build\gtk\Win32\release\share/man\man5
Installing C:\gtk-build\build\Win32\release\pkgconf\man/pkgconf-personality.5 to C:\gtk-build\gtk\Win32\release\share/man\man5
Installing C:\gtk-build\build\Win32\release\pkgconf\pkg.m4 to C:\gtk-build\gtk\Win32\release\share/aclocal
        1 file(s) copied.
Building project cmake (3.7.2)
Building project win-iconv (0.0.8)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/gtk-build/build/Win32/release/win-iconv/_gvsbuild-cmake
ninja: no work to do.
[0/1] Running tests...
Test project C:/gtk-build/build/Win32/release/win-iconv/_gvsbuild-cmake
    Start 1: win_iconv_test
1/1 Test #1: win_iconv_test ...................   Passed    0.06 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.07 sec
[0/1] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/lib/iconv.lib
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/bin/iconv.dll
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/bin/win_iconv.exe
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/include/iconv.h
Building project gettext (0.19.7)
Checking for 'C:\gtk-build\build\Win32\release\gettext\build\win32\vs12\gettext.sln'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(390,5): error
MSB8020: The build tools for Visual Studio 2013 (Platform Toolset = 'v120') cannot be found. To build using the v120 bu
ild tools, please install Visual Studio 2013 build tools.  Alternatively, you may upgrade to the current Visual Studio
tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\gtk-build\
build\Win32\release\gettext\build\win32\vs12\grt.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(390,5): error
MSB8020: The build tools for Visual Studio 2013 (Platform Toolset = 'v120') cannot be found. To build using the v120 bu
ild tools, please install Visual Studio 2013 build tools.  Alternatively, you may upgrade to the current Visual Studio
tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\gtk-build\
build\Win32\release\gettext\build\win32\vs12\asprintf.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(390,5): error
MSB8020: The build tools for Visual Studio 2013 (Platform Toolset = 'v120') cannot be found. To build using the v120 bu
ild tools, please install Visual Studio 2013 build tools.  Alternatively, you may upgrade to the current Visual Studio
tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\gtk-build\
build\Win32\release\gettext\build\win32\vs12\gnu.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(390,5): error
MSB8020: The build tools for Visual Studio 2013 (Platform Toolset = 'v120') cannot be found. To build using the v120 bu
ild tools, please install Visual Studio 2013 build tools.  Alternatively, you may upgrade to the current Visual Studio
tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\gtk-build\
build\Win32\release\gettext\build\win32\vs12\glib_rpl.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(390,5): error
MSB8020: The build tools for Visual Studio 2013 (Platform Toolset = 'v120') cannot be found. To build using the v120 bu
ild tools, please install Visual Studio 2013 build tools.  Alternatively, you may upgrade to the current Visual Studio
tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\gtk-build\
build\Win32\release\gettext\build\win32\vs12\libxml_rpl.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(390,5): error
MSB8020: The build tools for Visual Studio 2013 (Platform Toolset = 'v120') cannot be found. To build using the v120 bu
ild tools, please install Visual Studio 2013 build tools.  Alternatively, you may upgrade to the current Visual Studio
tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\gtk-build\
build\Win32\release\gettext\build\win32\vs12\grep.vcxproj]
Traceback (most recent call last):
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 487, in build
    if self.__build_one(p):
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 613, in __build_one
    skip_deps = proj.build()
  File "c:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 471, in build
    self.exec_msbuild_gen(r'build\win32', 'gettext.sln')
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 231, in exec_msbuild_gen
    self.exec_msbuild(cmd, configuration, add_path)
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 114, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 109, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 860, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 937, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild build\win32\vs12\gettext.sln /p:Configuration=release /nologo /p:Platform=Win32 /v:minimal /p:WindowsTargetPlatformVersion="10.0.18362.0"' returned non-zero exit status 1.
Error: gettext build failed
```

The solution file for gettext seems to want Visual Studio 2013 build tools (v120). Now, internet tells me to simply install Visual Studio 2013. However that will want to install files to "C:\Program Files (x86)\Microsoft Visual Studio 12.0" which is now symlinked.

Whether that will just work, work if I install to a different location, or simply screw everything up, at least it seems we established this issue with the build script is not just me.

**Comment by guruDanny67** [comment]
You need to say to the script which version of Visual Studio you're using, with the --vs-ver option: this helps the script locate the correct compiler & tools and use the right solution for the compiler.

The script is mainly correct: install (a recent) Visual Studio version you like (e.g. vs2019), install it in the default location, and simply give the script the version you install (for vs 2019 is 16): that's all, folks :)

If you symlink the vs2015 on the vs2013 install directory the script is still looking for the vs2013 tools (v120) and so some projects (the ones that use the vs solution) are not built because the vs2015 tools are version v140.

**Comment by guruDanny67** [comment]
I improve (a little) the documentation to make clear that you may need to specify vs_ver and how to get the full help.

I hope this helps also future users.
