### ISSUE TITLE
Build the GTK+ stack! Need Help with Microsoft Visual Studio 2013 Version Details for command?

### ISSUE THREAD

**Issue by charleswri631** [wingtk/gvsbuild#401]
Question regarding building the python commands to run and build the necessary files to use GTK3 with Microsoft Visual Studio 2013 and make GUI or Graphics with the C Programming language!

What should I type so that I can prepare Microsoft Visual Studio 2013 to use GTK3 so that I can program with C Code and do graphics or make GUI interfaces? 

STEP 4 gives the procedure to do this activity although there are many versions of Microsoft Visual Studio 2013, 2015, 2017, 2019. For example.  And also to mention the two version types 32bit or 64bit.

Step_4 - Now start a command-line window as a regular user. Go to the _gvsbuild_ directory and start building with the script. For example, to build 32-bit GTK+ 3 and its dependencies with Visual Studio 2013 (the default), run:

    ```
    cd C:\gtk-build\github\gvsbuild
    python .\build.py build gtk3
    ```

    To build the 64-bit version, run:

    ```
    cd C:\gtk-build\github\gvsbuild
    python .\build.py build -p x64 gtk3
    ```

    To build the 64-bit version with the Visual Studio 2017 (version 15) you need also to tell the script the visual studio version, run:

    ```
    cd C:\gtk-build\github\gvsbuild
    python .\build.py build -p x64 --vs-ver 15 gtk3
    ```

    For more information about the possible commands run:

    ```
    python .\build.py --help
    ```

    To get detailed help on the build command run:

    ```
    python .\build.py build --help
    ```

    Is possible to set some parameters from a file, e.g. vs2015-release.pro, putting the @ character before the file name. The file contains the option, one per line, separated by a carriage return:

    ```
    --vs-ver
    14
    --win-sdk
    8.1
    -c
    release
    ```

    Even if the format is not the easier to write or read in this way we eliminate the problem of escaping spaces is file names and directories. Then you can use it:

    ```
    python .\build.py build @vs2015-release.pro gtk3-full
    ```
-------------------------------------------------------------------------------------------------------------------------------------------
When the procedure above is complete the STACK will be complete!

When the script is done, your GTK+ stack will be found under _C:\gtk-build\gtk_. Enjoy!
-------------------------------------------------------------------------------------------------------------------------------------------
Below is my screen shot for my version of Microsoft Visual Studio 2013!

![version-2013](https://user-images.githubusercontent.com/65590698/100352027-5fa4f200-2fba-11eb-9855-be8be70f5978.png)

Microsoft Visual Studio Professional 2013
Version 12.0.21005.1 REL
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

Microsoft Office Developer Tools for Visual Studio 2013 ENU   06177-004-0447006-02534
Microsoft Office Developer Tools for Visual Studio 2013 ENU

Team Explorer for Visual Studio 2013   06177-004-0447006-02534
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06177-004-0447006-02534
Microsoft Visual Basic 2013

Visual C# 2013   06177-004-0447006-02534
Microsoft Visual C# 2013

Visual C++ 2013   06177-004-0447006-02534
Microsoft Visual C++ 2013

Visual F# 2013   06177-004-0447006-02534
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06177-004-0447006-02534
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.0.11001.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.0
Provides common services for use by Azure Mobile Services and Windows Azure Tools.

Microsoft Web Developer Tools 2013   2.0.40926.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Windows Azure Web Sites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Windows Azure

NuGet Package Manager   2.7.40911.287
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   12.0.30919.1
Microsoft SQL Server Data Tools

Windows Azure Mobile Services Tools   1.0
Windows Azure Mobile Services Tools

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Also I do not see were it would say 32bit or 64bit version of windows! It usually will say 32 or 64! I will find out while I wait for a response on where or how to get the command to build the GTK+ stack for my version of Microsoft Visual Studio 2013!

**Comment by charleswri631** [comment]
My version I believe with great assumption although I still can not be certain is that I have a 32bit Version of Microsoft Visual Studio 2013. I assume because I did here many mention that there was only a 32bit version of Microsoft Visual Studio 2013.

**Comment by guruDanny67** [comment]
The visual studio 2013 is a little bit old (in computer science 6 years are ages) and you should use a newer one (2017 or, better, 2019: also the community versions are ok).

To try with the 2013 you should follow the instrunction: install a suitable python and then launch the scripts and see what's happen.

The parameter you need to pass are the vs version (--vs-ver 12) and the installation dir of the visual studio suite (--vs-install-path xxxx) and a project to see if it runs.

You can start with libpng (a simple lib) and, if it works, continue with alla the stack.

**Comment by charleswri631** [comment]
Could you give one full example with the exact type that needs to be typed in Command Prompt that starts with the word python. Also if you could give me a link to get any files needed before I type the information into command prompt which needs to start with the word python. My install directory is C:\Program Files (x86)\Microsoft Visual Studio 12.0\ so you mentioned that the command would need to be _COMMAND PROMPT>_"**python .\build.py build  -p x64  --vs-ver 12 --vs-install-path C:\Program Files (x86)\Microsoft Visual Studio 12.0\**" and I think I am missing a project if you could just provide me with one full example and a project which has a location from where I could download the project I would appreciate your help on trying to turn me into a computer guru that maybe one day I may be a person just like you helping people on the web at www.github.com ! It noticed that there is a x64 and a -p on there command string although I believe that I have a 32bit version and I think that x64 would be a 64 bit version do I need to change that to x86 and what would be the purpose for the  "-p" part of this command string and should I type the word "build" also into the command which is before the "-p". Would there be a location where it would have a documentation regarding the question That I am asking at the current moment. The building the stack a very in depth documentation?

**Comment by charleswri631** [comment]
If you would happen to know where I would be able to get a very detailed document or file which contains information regarding my issue I would truly appreciate any type of link which would provide very in depth information regrading this type of python build with any version of Microsoft Visual Studio it would be great that why I do not need to ask so many questions here and waste your time! Sorry for any time you may have wasted as is with this comment question or any previous comment question!

**Comment by guruDanny67** [comment]
First of all you need the python language: you can download it from www.python.org, There is a download button, select All Release, then in the second box click on Python 3.7.9 (dated Aug, 17, 2020) to get to all the packages (in the bottom of the page).

Select and download 'Window x86 embeddable zip file' and, at the end of the download extract it in c:\gtk-build\py

Now you have the needed python, so follow the instruction: go in a shell, change dir to c:\gtk-build\github\gvsbuild and type 

c:\gtk-build\py\python --version

I everything is ok you should get a 'Python 3.7.9' response.

Now you can start building some projects (the projects are downloaded with the build script so you don't need to fetch them from outside, is the script that get what it needs).

So to build your first project you can type:

c:\gtk-build\py\python.exe build.py build -p x86 --vs-ver 12 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio 12.0" zlib

if it builds then youy can procede with more projects and add it at the end of the command line: to build the gtk3 stack you can type:

c:\gtk-build\py\python.exe build.py build -p x86 --vs-ver 12 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio 12.0" gtk3

and so on.

Hope this helps, wuth best regards

    guruDanny67

**Comment by charleswri631** [comment]
It does work when I run that command you provided from the CMD PROMPT at the directory c:\gtk-build\github\gvsbuild\    location

**Comment by charleswri631** [comment]
After I run that command will I be able to use the GTK stack api to build from Microsoft Visual Studio 2013 GUI Interface and compile from that GUI Interface? Or do I need to compile from the command prompt. Also I did run the command you told me to run although I did not see a program start after it finished. All I was able to see was three items which were built but only a listed at the end of command prompt after the command finished doing what it needed to do!

**Comment by charleswri631** [comment]
How would I run the program to see what it looks like after I do that command you provided. It did work although I did not see any programs run at the end!

**Comment by charleswri631** [comment]
I also found the Win32 Folder in the GTK folder located at C:\gtk-build\gtk\Win32  this Win32 Folder has the files I would need to include at the top of my C file that I create in Microsoft Visual Studio 2013 I would assume I would need to include it with quotes "" instead of <> greater than and less than signs also I would need to tell the Microsoft Visual Studio 2013 GUI where to find these include header files in the Win32 folder located in the GTK location. Great so all I would need to do Is use only what I installed with your command and if I would like to use any other API's I would install them the same way I did this API. where would I find information that is related to this API I just installed with your command?

**Comment by charleswri631** [comment]
https://developer.gnome.org/gtk3/stable/ I would assume this would be the GTK3 API and what would be the location of what is usable in the API with the Install command I put in COMMAND PROMPT which was spoken about in this entire comment section from top to bottom. The command I use which was COMMAND PROMPT = C:\gtk-build\github\gvsbuild> python .\build -p x86 --vs-ver 12 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio 12.0" zlib

**Comment by charleswri631** [comment]
This first command works

**Comment by charleswri631** [comment]
This first command works although the second command c:\gtk-build\github\gvsbuild> .\build.py build -p x86 --vs-ver 12 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio 12.0" gtk3

The second command gives me some type of issue!

Gives me some type of issue?
DOWN BELOW IS THE ISSUE!

Cleaning up the build environment
Checking msys tool
Checking Msvc tool
Downloading packages
Building project nuget (5.4.0)
Building project python ()
Building project ninja (1.8.2)
Building project meson (0.55.0)
(git) Cloning https://github.com/pkgconf/pkgconf.git to C:\gtk-build\src\git-exp\pkg-config
'git' is not recognized as an internal or external command,
operable program or batch file.
pkg-config:Exception Command 'git clone https://github.com/pkgconf/pkgconf.git C:\gtk-build\src\git-exp\pkg-config' returned non-zero exit status 1.
Removing the destination dir ...
(git) Cloning https://github.com/pkgconf/pkgconf.git to C:\gtk-build\src\git-exp\pkg-config
'git' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_expanders.py", line 350, in update_build_dir
    rt = self._update_dir()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_expanders.py", line 329, in _update_dir
    self.builder.exec_msys('git clone %s %s' % (self.repo_url, dest))
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 921, in exec_msys
    self.__execute(args, working_dir=working_dir, add_path=os.path.join(self.opts.msys_dir, 'usr', 'bin'))
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 942, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\W3-Developer\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git clone https://github.com/pkgconf/pkgconf.git C:\gtk-build\src\git-exp\pkg-config' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 492, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 576, in __build_one
    proj.prepare_build_dir()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 302, in prepare_build_dir
    self.unpack()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_expanders.py", line 301, in unpack
    self.update_build_dir()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_expanders.py", line 354, in update_build_dir
    rt = self._update_dir(remove_dest=True)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_expanders.py", line 329, in _update_dir
    self.builder.exec_msys('git clone %s %s' % (self.repo_url, dest))
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 921, in exec_msys
    self.__execute(args, working_dir=working_dir, add_path=os.path.join(self.opts.msys_dir, 'usr', 'bin'))
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 942, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\W3-Developer\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git clone https://github.com/pkgconf/pkgconf.git C:\gtk-build\src\git-exp\pkg-config' returned non-zero exit status 1.
Error: pkg-config build failed

**Comment by charleswri631** [comment]
Any ideas on what I must have not completed before running the second command?

**Comment by guruDanny67** [comment]
Sorry, you also need to install git to fetch some of the projects (we
assume that, having the script & the patches, you also have git installed
but it's not always the case) so go for it and install it in a path with
the name git in it so it's kept when we launch the scripts

Il giorno gio 3 dic 2020 alle ore 02:11 Charles Victor Wright <
notifications@github.com> ha scritto:

**Comment by charleswri631** [comment]
I installed GIT that went well and than the second command was working after I typed it in. It was working for a long time. It looks like it was installing many files. It looks as well it might have almost been finished installing but just at the end before it did finish I received this error!

**Comment by charleswri631** [comment]
fcarch.c
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1186,5): warning MSB8012: TargetPath(
C:\gtk-build\build\Win32\release\fontconfig\Release\fc-arch.exe) does not match the Linker's OutputFile property value
(C:\gtk-build\build\Win32\release\fontconfig\fc-arch\fc-arch.exe). This may cause your project to build incorrectly. To
 correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specifie
d in %(Link.OutputFile). [C:\gtk-build\build\Win32\release\fontconfig\fc-arch.vcxproj]
  fc-arch.vcxproj -> C:\gtk-build\build\Win32\release\fontconfig\Release\fc-arch.exe
  The system cannot find the file specified.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(381,5): warning MSB8028: The intermed
iate directory (Release\) contains files shared from another project (fc-arch.vcxproj).  This can lead to incorrect cle
an and rebuild behavior. [C:\gtk-build\build\Win32\release\fontconfig\fc-case.vcxproj]
  fc-case.c
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1186,5): warning MSB8012: TargetPath(
C:\gtk-build\build\Win32\release\fontconfig\Release\fc-case.exe) does not match the Linker's OutputFile property value
(C:\gtk-build\build\Win32\release\fontconfig\fc-case\fc-case.exe). This may cause your project to build incorrectly. To
 correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specifie
d in %(Link.OutputFile). [C:\gtk-build\build\Win32\release\fontconfig\fc-case.vcxproj]
  fc-case.vcxproj -> C:\gtk-build\build\Win32\release\fontconfig\Release\fc-case.exe
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(381,5): warning MSB8028: The intermed
iate directory (Release\) contains files shared from another project (fc-arch.vcxproj, fc-case.vcxproj).  This can lead
 to incorrect clean and rebuild behavior. [C:\gtk-build\build\Win32\release\fontconfig\fc-lang.vcxproj]
  fc-lang.c
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1186,5): warning MSB8012: TargetPath(
C:\gtk-build\build\Win32\release\fontconfig\Release\fc-lang.exe) does not match the Linker's OutputFile property value
(C:\gtk-build\build\Win32\release\fontconfig\fc-lang\fc-lang.exe). This may cause your project to build incorrectly. To
 correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specifie
d in %(Link.OutputFile). [C:\gtk-build\build\Win32\release\fontconfig\fc-lang.vcxproj]
     Creating library Release\fc-lang.lib and object Release\fc-lang.exp
  fc-lang.vcxproj -> C:\gtk-build\build\Win32\release\fontconfig\Release\fc-lang.exe
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(381,5): warning MSB8028: The intermed
iate directory (Release\) contains files shared from another project (fc-arch.vcxproj, fc-case.vcxproj, fc-lang.vcxproj
).  This can lead to incorrect clean and rebuild behavior. [C:\gtk-build\build\Win32\release\fontconfig\fontconfig.vcxp
roj]
  dirent.c
  fcatomic.c
  fccache.c
src\fccache.c(56): warning C4101: 'target' : unreferenced local variable [C:\gtk-build\build\Win32\release\fontconfig\f
ontconfig.vcxproj]
src\fccache.c(848): warning C4018: '>' : signed/unsigned mismatch [C:\gtk-build\build\Win32\release\fontconfig\fontconf
ig.vcxproj]
src\fccache.c(854): warning C4018: '>' : signed/unsigned mismatch [C:\gtk-build\build\Win32\release\fontconfig\fontconf
ig.vcxproj]
src\fccache.c(865): warning C4018: '>' : signed/unsigned mismatch [C:\gtk-build\build\Win32\release\fontconfig\fontconf
ig.vcxproj]
src\fccache.c(874): warning C4018: '>' : signed/unsigned mismatch [C:\gtk-build\build\Win32\release\fontconfig\fontconf
ig.vcxproj]
src\fccache.c(880): warning C4018: '>' : signed/unsigned mismatch [C:\gtk-build\build\Win32\release\fontconfig\fontconf
ig.vcxproj]
src\fccache.c(897): warning C4018: '>' : signed/unsigned mismatch [C:\gtk-build\build\Win32\release\fontconfig\fontconf
ig.vcxproj]
  fccfg.c
src\fccfg.c(2259): error C2275: 'FcChar8' : illegal use of this type as an expression [C:\gtk-build\build\Win32\release
\fontconfig\fontconfig.vcxproj]
          C:\gtk-build\build\Win32\release\fontconfig\fontconfig/fontconfig.h(43) : see declaration of 'FcChar8'
src\fccfg.c(2259): error C2065: 'path' : undeclared identifier [C:\gtk-build\build\Win32\release\fontconfig\fontconfig.
vcxproj]
src\fccfg.c(2261): error C2065: 'path' : undeclared identifier [C:\gtk-build\build\Win32\release\fontconfig\fontconfig.
vcxproj]
src\fccfg.c(2264): error C2065: 'path' : undeclared identifier [C:\gtk-build\build\Win32\release\fontconfig\fontconfig.
vcxproj]
src\fccfg.c(2264): warning C4047: 'function' : 'const FcChar8 *' differs in levels of indirection from 'int' [C:\gtk-bu
ild\build\Win32\release\fontconfig\fontconfig.vcxproj]
src\fccfg.c(2264): warning C4024: 'FcStrCanonFilename' : different types for formal and actual parameter 1 [C:\gtk-buil
d\build\Win32\release\fontconfig\fontconfig.vcxproj]
src\fccfg.c(2265): error C2065: 'path' : undeclared identifier [C:\gtk-build\build\Win32\release\fontconfig\fontconfig.
vcxproj]
src\fccfg.c(2265): warning C4047: 'function' : 'FcChar8 *' differs in levels of indirection from 'int' [C:\gtk-build\bu
ild\Win32\release\fontconfig\fontconfig.vcxproj]
src\fccfg.c(2265): warning C4024: 'FcStrFree' : different types for formal and actual parameter 1 [C:\gtk-build\build\W
in32\release\fontconfig\fontconfig.vcxproj]
  fccharset.c
  fccompat.c
src\fccompat.c(99): warning C4018: '<' : signed/unsigned mismatch [C:\gtk-build\build\Win32\release\fontconfig\fontconf
ig.vcxproj]
  fcdbg.c
  fcdefault.c
  fcdir.c
  fcformat.c
  fcfreetype.c
  fcfs.c
  fchash.c
  fcinit.c
  fclang.c
  fclist.c
  fcmatch.c
  fcmatrix.c
  fcname.c
  fcobjs.c
src\fcobjs.c(33): fatal error C1083: Cannot open include file: 'fcobjshash.h': No such file or directory [C:\gtk-build\
build\Win32\release\fontconfig\fontconfig.vcxproj]
  Generating Code...
  Compiling...
  fcpat.c
src\fcpat.c(420): warning C4018: '<' : signed/unsigned mismatch [C:\gtk-build\build\Win32\release\fontconfig\fontconfig
.vcxproj]
  fcptrlist.c
  fcserialize.c
  fcstat.c
  fcstr.c
  fcxml.c
  ftglue.c
  fcrange.c
  fcweight.c
  Generating Code...
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 492, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 618, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 359, in build
    self.exec_msbuild('fontconfig.sln /t:build')
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 114, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 109, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 865, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 942, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\W3-Developer\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild fontconfig.sln /t:build /p:Configuration=release /nologo /p:Platform=Win32 /p:PythonPath="C:\gtk-build\tools\pythonx86.3.7.7\tools" /p:PythonDir="C:\gtk-build\tools\pythonx86.3.7.7\tools" /v:minimal' returned non-zero exit status 1.
Error: fontconfig build failed

**Comment by charleswri631** [comment]
Error: fontconfig build failed

**Comment by charleswri631** [comment]
This was the last line something about a fontconfig directory for Microsoft Visual Studio 2013!

**Comment by charleswri631** [comment]
It was doing lots of installing before this error occur. It was at least for 5 min installing before this error occur!

**Comment by charleswri631** [comment]
I was almost sure it was about to finish installing than this error occur!

**Comment by charleswri631** [comment]
Any suggestions?

**Comment by charleswri631** [comment]
Just making a post just to show that I am much aware of this blog comment and awaiting a response to the final part of this entire blog comment. For the suggestion of the Error!

**Comment by charleswri631** [comment]
Just leaving a message to show that I am eager to hear from you when you get an opportunity to send me a response! Truly appreciate all your help! Thank You!

**Comment by charleswri631** [comment]
Building project fontconfig (2.13.1)
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(381,5): warning MSB8028: The intermed
iate directory (Release\) contains files shared from another project (fc-case.vcxproj, fc-lang.vcxproj, fontconfig.vcxp
roj).  This can lead to incorrect clean and rebuild behavior. [C:\gtk-build\build\Win32\release\fontconfig\fc-arch.vcxp
roj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1186,5): warning MSB8012: TargetPath(
C:\gtk-build\build\Win32\release\fontconfig\Release\fc-arch.exe) does not match the Linker's OutputFile property value
(C:\gtk-build\build\Win32\release\fontconfig\fc-arch\fc-arch.exe). This may cause your project to build incorrectly. To
 correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specifie
d in %(Link.OutputFile). [C:\gtk-build\build\Win32\release\fontconfig\fc-arch.vcxproj]
  fc-arch.vcxproj -> C:\gtk-build\build\Win32\release\fontconfig\Release\fc-arch.exe
  The system cannot find the file specified.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(381,5): warning MSB8028: The intermed
iate directory (Release\) contains files shared from another project (fc-arch.vcxproj, fc-lang.vcxproj, fontconfig.vcxp
roj).  This can lead to incorrect clean and rebuild behavior. [C:\gtk-build\build\Win32\release\fontconfig\fc-case.vcxp
roj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1186,5): warning MSB8012: TargetPath(
C:\gtk-build\build\Win32\release\fontconfig\Release\fc-case.exe) does not match the Linker's OutputFile property value
(C:\gtk-build\build\Win32\release\fontconfig\fc-case\fc-case.exe). This may cause your project to build incorrectly. To
 correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specifie
d in %(Link.OutputFile). [C:\gtk-build\build\Win32\release\fontconfig\fc-case.vcxproj]
  fc-case.vcxproj -> C:\gtk-build\build\Win32\release\fontconfig\Release\fc-case.exe
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(381,5): warning MSB8028: The intermed
iate directory (Release\) contains files shared from another project (fc-arch.vcxproj, fc-case.vcxproj, fontconfig.vcxp
roj).  This can lead to incorrect clean and rebuild behavior. [C:\gtk-build\build\Win32\release\fontconfig\fc-lang.vcxp
roj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1186,5): warning MSB8012: TargetPath(
C:\gtk-build\build\Win32\release\fontconfig\Release\fc-lang.exe) does not match the Linker's OutputFile property value
(C:\gtk-build\build\Win32\release\fontconfig\fc-lang\fc-lang.exe). This may cause your project to build incorrectly. To
 correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specifie
d in %(Link.OutputFile). [C:\gtk-build\build\Win32\release\fontconfig\fc-lang.vcxproj]
  fc-lang.vcxproj -> C:\gtk-build\build\Win32\release\fontconfig\Release\fc-lang.exe
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(381,5): warning MSB8028: The intermed
iate directory (Release\) contains files shared from another project (fc-arch.vcxproj, fc-case.vcxproj, fc-lang.vcxproj
).  This can lead to incorrect clean and rebuild behavior. [C:\gtk-build\build\Win32\release\fontconfig\fontconfig.vcxp
roj]
  dirent.c
  fccfg.c
src\fccfg.c(2259): error C2275: 'FcChar8' : illegal use of this type as an expression [C:\gtk-build\build\Win32\release
\fontconfig\fontconfig.vcxproj]
          C:\gtk-build\build\Win32\release\fontconfig\fontconfig/fontconfig.h(43) : see declaration of 'FcChar8'
src\fccfg.c(2259): error C2065: 'path' : undeclared identifier [C:\gtk-build\build\Win32\release\fontconfig\fontconfig.
vcxproj]
src\fccfg.c(2261): error C2065: 'path' : undeclared identifier [C:\gtk-build\build\Win32\release\fontconfig\fontconfig.
vcxproj]
src\fccfg.c(2264): error C2065: 'path' : undeclared identifier [C:\gtk-build\build\Win32\release\fontconfig\fontconfig.
vcxproj]
src\fccfg.c(2264): warning C4047: 'function' : 'const FcChar8 *' differs in levels of indirection from 'int' [C:\gtk-bu
ild\build\Win32\release\fontconfig\fontconfig.vcxproj]
src\fccfg.c(2264): warning C4024: 'FcStrCanonFilename' : different types for formal and actual parameter 1 [C:\gtk-buil
d\build\Win32\release\fontconfig\fontconfig.vcxproj]
src\fccfg.c(2265): error C2065: 'path' : undeclared identifier [C:\gtk-build\build\Win32\release\fontconfig\fontconfig.
vcxproj]
src\fccfg.c(2265): warning C4047: 'function' : 'FcChar8 *' differs in levels of indirection from 'int' [C:\gtk-build\bu
ild\Win32\release\fontconfig\fontconfig.vcxproj]
src\fccfg.c(2265): warning C4024: 'FcStrFree' : different types for formal and actual parameter 1 [C:\gtk-build\build\W
in32\release\fontconfig\fontconfig.vcxproj]
  fccharset.c
  fcobjs.c
src\fcobjs.c(33): fatal error C1083: Cannot open include file: 'fcobjshash.h': No such file or directory [C:\gtk-build\
build\Win32\release\fontconfig\fontconfig.vcxproj]
  Generating Code...
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 492, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 618, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 359, in build
    self.exec_msbuild('fontconfig.sln /t:build')
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 114, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 109, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 865, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 942, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\W3-Developer\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild fontconfig.sln /t:build /p:Configuration=release /nologo /p:Platform=Win32 /p:PythonPath="C:\gtk-build\tools\pythonx86.3.7.7\tools" /p:PythonDir="C:\gtk-build\tools\pythonx86.3.7.7\tools" /v:minimal' returned non-zero exit status 1.
Error: fontconfig build failed

C:\gtk-build\github\gvsbuild>

**Comment by charleswri631** [comment]
Building project fontconfig (2.13.1)
Building project fontconfig (2.13.1) gives me an error!

**Comment by charleswri631** [comment]
Revert "fontconfig: update to version 2.13.1" Does it have anything to do with the Revert? Does this have anything to do with a faulty file in the installation or some type of misconfiguration with Visual Studio 2013?

**Comment by charleswri631** [comment]
Now start a command-line window as a regular user. Go to the gvsbuild directory and start building with the script. For example, to build 32-bit GTK+ 3 and its dependencies with Visual Studio 2013 (the default), run:

cd C:\gtk-build\github\gvsbuild
python .\build.py build gtk3

To build the 64-bit version, run:

cd C:\gtk-build\github\gvsbuild
python .\build.py build -p x64 gtk3

**Comment by charleswri631** [comment]
These are the two commands I have trouble with! I double checked the msys2 installation and confirmed that I did run the following commands from the msys2 console:

Until further rerun not required may run more than twice:
pacman -Syy
pacman -Syuu

Install GTK3 with msys2 and two packages install with msys2
pacman -S mingw-w64-x86_64-gtk3
pacman -S mingw-w64-x86_64-toolchain base-devel

I do not know if I installed everything required so that I can run from command prompt the final two command prompt commands so that these command work. These two command prompt commands are for 64bit and 32bit which cause an error while installing called:
Error: fontconfig build failed!

Final two commands from command prompt:
python .\build.py build gtk3
python .\build.py build -p x64 gtk3

**Comment by charleswri631** [comment]
Still eager for a suggestion! Truly appreciate any help you could give. Meanwhile I will check other locations on the web to see what I could find regarding the issue!

**Comment by charleswri631** [comment]
https://github.com/wingtk/gvsbuild/issues/426

**Comment by charleswri631** [comment]
I simply install Visual Studio 2019 Professional.
