### ISSUE TITLE
msgfmt missing charset-1.dll

### ISSUE THREAD

**Issue by M0n7y5** [wingtk/gvsbuild#410]
Hi,
when i tried to compile it using this command :
`python .\build.py build -p x64 gtk3 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional" --win-sdk-ver 10.0.18362.0 --vs-ver 16`

I got this error:

![obrazek](https://user-images.githubusercontent.com/17201053/105867845-d2037400-5ff5-11eb-8161-7ba35be185c7.png)

```python3
Running custom install script 'C:\\gtk-build\\tools\\python.3.7.7\\tools\\python.exe C:\\gtk-build\\tools\\meson-fd6585ecc41e1c731224cac08a3f6ef6f49ab184\\meson.py --internal gettext install --subdir=po --localedir=share/locale --pkgname=glib20'
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-fd6585ecc41e1c731224cac08a3f6ef6f49ab184\meson.py", line 29, in <module>
    sys.exit(mesonmain.main())
  File "C:\gtk-build\tools\meson-fd6585ecc41e1c731224cac08a3f6ef6f49ab184\mesonbuild\mesonmain.py", line 240, in main
    return run(sys.argv[1:], launcher)
  File "C:\gtk-build\tools\meson-fd6585ecc41e1c731224cac08a3f6ef6f49ab184\mesonbuild\mesonmain.py", line 229, in run
    return run_script_command(args[1], args[2:])
  File "C:\gtk-build\tools\meson-fd6585ecc41e1c731224cac08a3f6ef6f49ab184\mesonbuild\mesonmain.py", line 177, in run_script_command
    return module.run(script_args)
  File "C:\gtk-build\tools\meson-fd6585ecc41e1c731224cac08a3f6ef6f49ab184\mesonbuild\scripts\gettext.py", line 118, in run
    if gen_gmo(src_sub, bld_sub, langs) != 0:
  File "C:\gtk-build\tools\meson-fd6585ecc41e1c731224cac08a3f6ef6f49ab184\mesonbuild\scripts\gettext.py", line 67, in gen_gmo
    '-o', os.path.join(bld_sub, l + '.gmo')])
  File "C:\gtk-build\tools\python.3.7.7\tools\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msgfmt', 'C:\\gtk-build\\build\\x64\\release\\glib\\po\\af.po', '-o', 'C:\\gtk-build\\build\\x64\\release\\glib\\_gvsbuild-meson\\po\\af.gmo']' returned non-zero exit status 3221225781.
FAILED: install script 'C:\gtk-build\tools\python.3.7.7\tools\python.exe C:\gtk-build\tools\meson-fd6585ecc41e1c731224cac08a3f6ef6f49ab184\meson.py --internal gettext install --subdir=po --localedir=share/locale --pkgname=glib20' exit code 1, stopped
FAILED: meson-install
"C:\gtk-build\tools\python.3.7.7\tools\python.exe" "C:\gtk-build\tools\meson-fd6585ecc41e1c731224cac08a3f6ef6f49ab184\meson.py" "install" "--no-rebuild"
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\bezAV\gvsbuild\gvsbuild\utils\builder.py", line 492, in build
    if self.__build_one(p):
  File "C:\bezAV\gvsbuild\gvsbuild\utils\builder.py", line 618, in __build_one
    skip_deps = proj.build()
  File "C:\bezAV\gvsbuild\gvsbuild\projects.py", line 491, in build
    Meson.build(self, meson_params='-Dinternal_pcre=true')
  File "C:\bezAV\gvsbuild\gvsbuild\utils\base_builders.py", line 76, in build
    self.builder.exec_ninja(params='install', working_dir=ninja_build)
  File "C:\bezAV\gvsbuild\gvsbuild\utils\builder.py", line 902, in exec_ninja
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\bezAV\gvsbuild\gvsbuild\utils\builder.py", line 942, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: glib build failed
```

**Comment by danyeaw** [comment]
@M0n7y5 Is this still an issue for you?

**Comment by danyeaw** [comment]
I didn't hear back from you on this, please reopen this or open a new issue if this is still a problem.
