### ISSUE TITLE
Windows build problem with 'clutter'

### ISSUE THREAD

**Issue by Linoprit** [wingtk/gvsbuild#427]
Hi, 
the Windows build seems broken. It stops when building the package 'clutter'.  There are many undefined symbols, all starting with CLUTTER_TYPE_*.
When I look into the sources, there is to see, that the files clutter-enum-types.c and .h are empty. The corresponding .in files are present. It seems, the where not processed.
Obviously the enums are built with some perl-scripts, as to see in gen-enums.bat. I tried to start it manually, but this results in several warnings, like WARNING: No file "../../clutterclutter-zoom-action.h" found.

That's how I start the build:
c:\Python39-32\python.exe .\build.py build --python-dir "c:\python39-32" --same-python --build-dir "E:\99_Installation\GTK\gtk-build" --vs-ver 15 gtk3-full --msys-dir e:\tools\msys64

Tanks

EDIT:
In the file gen-enums.bat, there are missing slashes. Search and replace 'clutterclutter' with 'clutter/clutter'
Then, the batch-file works.

There's also a bug in clutter-stage.c, 3799. A void function returns a value. Just remove the 'return'.

Now the build dies with an error in post-install. 'Ninja returns non zero value'... Can not say which Module causes the problem.

**Comment by Linoprit** [comment]
EDIT:
In the file gen-enums.bat, there are missing slashes. Search and replace 'clutterclutter' with 'clutter/clutter'
Then, the batch-file works.

**Comment by Linoprit** [comment]
EDIT:
There's also a bug in  clutter-stage.c, 3799. A void function returns a value. Just remove the 'return'.
Now the build dies with an error in post-install. 'Ninja returns non zero value'... Can not say which Module causes the problem.

**Comment by Linoprit** [comment]
------

Build targets in project: 50
WARNING: Project specifies a minimum meson_version '>= 0.48.0' but uses features which were added in newer versions:
 * 0.49.0: {'/ with string arguments'}
 * 0.51.0: {'dep.get_variable'}
 * 0.54.0: {'internal arg in dep.get_variable'}

Option buildtype is: debug [default: debugoptimized]
Found ninja-1.8.2 at E:\99_Installation\GTK\gtk-build\tools\ninja-1.8.2\ninja.EXE
ninja: fatal: CreateProcess: Falscher Parameter.om command (wrapped by meson to capture output)

Traceback (most recent call last):
  File "E:\99_Installation\GTK\gvsbuild\gvsbuild\utils\builder.py", line 493, in build
    if self.__build_one(p):
  File "E:\99_Installation\GTK\gvsbuild\gvsbuild\utils\builder.py", line 624, in __build_one
    skip_deps = proj.build()
  File "E:\99_Installation\GTK\gvsbuild\gvsbuild\projects.py", line 881, in build
    Meson.build(self, meson_params='-Dtests=false -Ddemos=false -Dexamples=false')
  File "E:\99_Installation\GTK\gvsbuild\gvsbuild\utils\base_builders.py", line 76, in build
    self.builder.exec_ninja(params='install', working_dir=ninja_build)
  File "E:\99_Installation\GTK\gvsbuild\gvsbuild\utils\builder.py", line 908, in exec_ninja
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "E:\99_Installation\GTK\gvsbuild\gvsbuild\utils\builder.py", line 948, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "c:\Local_Files\Python39-32\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: gtk3 build failed

**Comment by Linoprit** [comment]
ok. After using a shorter target dir and building the debug target the build worked so far. => --build-dir "E:\99_Installation\GTK\gtk-build" -c debug

**Comment by Linoprit** [comment]
Final: The problem with clutter-stage.c, line 3799 remains, but is handable. Maybe the problems arised, because the build-dir path was too long.
