### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by zhmmmm** [wingtk/gvsbuild#432]
# python ./build.py build --vs-ver 16 --win-sdk 10 -c release gtk3
Traceback (most recent call last):
  File "/c/gtk-build/github/gvsbuild/./build.py", line 48, in <module>
    args.func(args)
  File "/c/gtk-build/github/gvsbuild/gvsbuild/utils/parser.py", line 164, in do_build
    builder = Builder(opts)
  File "/c/gtk-build/github/gvsbuild/gvsbuild/utils/builder.py", line 49, in __init__
    script_title('* Setup')
  File "/c/gtk-build/github/gvsbuild/gvsbuild/utils/simple_ui.py", line 42, in script_title
    ctypes.windll.kernel32.GetConsoleTitleW(buf, 256)
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by lazka** [comment]
You are using a cygwin based Python instead of the Windows one.

**Comment by zhmmmm** [comment]
oh thank
