### ISSUE TITLE
OSError: [WinError 145] The directory is not empty: 'C:\\gtk-build\\build\\x64\\debug\\libxml2\\_gvsbuild-meson\\meson-private\\tmp0nff47ki'

### ISSUE THREAD

**Issue by Zueuk** [wingtk/gvsbuild#437]
```
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\mesonlib\universal.py", line 1568, in cleanup
    super().cleanup()
  File "C:\Python36\lib\tempfile.py", line 811, in cleanup
    _shutil.rmtree(self.name)
  File "C:\Python36\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python36\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python36\lib\shutil.py", line 391, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:\\gtk-build\\build\\x64\\debug\\libxml2\\_gvsbuild-meson\\meson-private\\tmp0nff47ki'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\mesonlib\universal.py", line 1562, in __exit__
    super().__exit__(exc, value, tb)
  File "C:\Python36\lib\tempfile.py", line 807, in __exit__
    self.cleanup()
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\mesonlib\universal.py", line 1570, in cleanup
    windows_proof_rmtree(self.name)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\mesonlib\universal.py", line 1525, in windows_proof_rmtree
    _make_tree_writable(f)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\mesonlib\universal.py", line 1515, in _make_tree_writable
    os.chmod(fpath, os.stat(fpath).st_mode | stat.S_IWRITE | stat.S_IREAD)
PermissionError: [WinError 5] Access is denied: 'C:\\gtk-build\\build\\x64\\debug\\libxml2\\_gvsbuild-meson\\meson-private\\tmp0nff47ki\\output.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\mesonmain.py", line 132, in run
    return options.run_func(options)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\msetup.py", line 275, in run
    app.generate()
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\msetup.py", line 183, in generate
    self._generate(env)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\msetup.py", line 222, in _generate
    intr.run()
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreter.py", line 4798, in run
    super().run()
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 641, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 666, in evaluate_codeblock
    raise e
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 659, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 674, in evaluate_statement
    self.assignment(cur)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 1341, in assignment
    value = self.evaluate_statement(node.value)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 672, in evaluate_statement
    return self.function_call(cur)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 1031, in function_call
    return func(node, func_args, kwargs)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 515, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 515, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 515, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 3 more times]
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 210, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreterbase.py", line 229, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreter.py", line 3765, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\interpreter.py", line 3859, in dependency_impl
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\dependencies\base.py", line 2432, in find_external_dependency
    d = c()
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\dependencies\base.py", line 645, in __init__
    self._set_libs()
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\dependencies\base.py", line 906, in _set_libs
    self.link_args, self.raw_link_args = self._search_libs(out, out_raw)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\dependencies\base.py", line 831, in _search_libs
    libpaths, libtype)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\compilers\mixins\clike.py", line 1139, in find_library
    return self._find_library_impl(libname, env, extra_dirs, code, libtype)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\compilers\mixins\clike.py", line 1128, in _find_library_impl
    value = self._find_library_real(libname, env, extra_dirs, code, libtype)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\compilers\mixins\clike.py", line 1101, in _find_library_real
    if self.output_is_64bit(env):
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\compilers\mixins\clike.py", line 1075, in output_is_64bit
    return self.sizeof('void *', '', env) == 8
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\compilers\mixins\clike.py", line 614, in sizeof
    dependencies=dependencies)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\compilers\mixins\clike.py", line 489, in run
    return compilers.RunResult(False)
  File "C:\Python36\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\compilers\compilers.py", line 1190, in _build_wrapper
    yield r
  File "C:\Python36\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\compilers\compilers.py", line 797, in compile
    yield result
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\mesonlib\universal.py", line 1564, in __exit__
    windows_proof_rmtree(self.name)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\mesonlib\universal.py", line 1525, in windows_proof_rmtree
    _make_tree_writable(f)
  File "C:\gtk-build\tools\meson-0.57.1\mesonbuild\mesonlib\universal.py", line 1515, in _make_tree_writable
    os.chmod(fpath, os.stat(fpath).st_mode | stat.S_IWRITE | stat.S_IREAD)
PermissionError: [WinError 5] Access is denied: 'C:\\gtk-build\\build\\x64\\debug\\libxml2\\_gvsbuild-meson\\meson-private\\tmp0nff47ki\\output.exe'
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 493, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 624, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 1500, in build
    Meson.build(self)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 66, in build
    self.exec_vs(cmd, add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 110, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 871, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 948, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python36\python.exe C:\gtk-build\tools\meson-0.57.1\meson.py C:\gtk-build\build\x64\debug\libxml2 C:\gtk-build\build\x64\debug\libxml2\_gvsbuild-meson --prefix C:\gtk-build\gtk\x64\debug --buildtype debug' returned non-zero exit status 2.
Error: libxml2 build failed
```

**Comment by Zueuk** [comment]
Turned out to be some Python problem, that (apparently) has been fixed in newer language versions that do not run on Windows 7.

Fixed it by retrying `super().cleanup()` after a few milliseconds... Building `gtk3-full` still does not work though, now for some other reason(s), including expired certificates.

**Comment by danyeaw** [comment]
@Zueuk Windows 7 was end of life 2 years ago, and Python 3.6 is also end of life. Sorry, but I don't think we can support this anymore. Happy to accept a PR if you come up with a fix. 👍
