### ISSUE TITLE
Build failed on gettext

### ISSUE THREAD

**Issue by RaiZiStyle** [wingtk/gvsbuild#455]
Build failed to find gettext.sln
I'm trying to build gtk for Visual Studio. Any idea why it's missing ? 
I have run the build like so : **python .\build.py build -p x64 --vs-ver 19 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community" gtk3**
```
[0/1] Installing files.
Installing pkgconf-3.dll to C:\gtk-build\gtk\x64\release\bin
Installing pkgconf.lib to C:\gtk-build\gtk\x64\release\lib
Installing pkgconf-3.pdb to C:\gtk-build\gtk\x64\release\bin
Installing pkgconf.exe to C:\gtk-build\gtk\x64\release\bin
Installing pkgconf.pdb to C:\gtk-build\gtk\x64\release\bin
Installing C:\gtk-build\build\x64\release\pkgconf\libpkgconf\libpkgconf.h to C:\gtk-build\gtk\x64\release\include\libpkgconf
Installing C:\gtk-build\build\x64\release\pkgconf\libpkgconf\stdinc.h to C:\gtk-build\gtk\x64\release\include\libpkgconf
Installing C:\gtk-build\build\x64\release\pkgconf\libpkgconf\iter.h to C:\gtk-build\gtk\x64\release\include\libpkgconf
Installing C:\gtk-build\build\x64\release\pkgconf\libpkgconf\bsdstubs.h to C:\gtk-build\gtk\x64\release\include\libpkgconf
Installing C:\gtk-build\build\x64\release\pkgconf\libpkgconf\libpkgconf-api.h to C:\gtk-build\gtk\x64\release\include\libpkgconf
Installing C:\gtk-build\build\x64\release\pkgconf\man/pkgconf.1 to C:\gtk-build\gtk\x64\release\share/man\man1
Installing C:\gtk-build\build\x64\release\pkgconf\man/pkg.m4.7 to C:\gtk-build\gtk\x64\release\share/man\man7
Installing C:\gtk-build\build\x64\release\pkgconf\man/pc.5 to C:\gtk-build\gtk\x64\release\share/man\man5
Installing C:\gtk-build\build\x64\release\pkgconf\man/pkgconf-personality.5 to C:\gtk-build\gtk\x64\release\share/man\man5
Installing C:\gtk-build\build\x64\release\pkgconf\pkg.m4 to C:\gtk-build\gtk\x64\release\share/aclocal
        1 fichier(s) copié(s).
-- Configuring done
-- Generating done
-- Build files have been written to: C:/gtk-build/build/x64/release/win-iconv/_gvsbuild-cmake
ninja: no work to do.
[0/1] Running tests...
Test project C:/gtk-build/build/x64/release/win-iconv/_gvsbuild-cmake
    Start 1: win_iconv_test
1/1 Test #1: win_iconv_test ...................   Passed    0.15 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.16 sec
[0/1] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/lib/iconv.lib
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/bin/iconv.dll
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/bin/win_iconv.exe
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/include/iconv.h
Cleaning up the build environment
Checking msys tool
Checking Msvc tool
Downloading packages
Building project nuget (5.4.0)
Building project python ()
Building project ninja (1.8.2)
Building project meson (0.57.1)
(git) Updating directory C:\gtk-build\src\git-exp\pkg-config
(git) Exporting directory C:\gtk-build\build\x64\release\pkgconf
Building project pkg-config (git/pkgconf-1.5.4)
Building project cmake (3.20.0)
(tar) Exporting win-iconv
Building project win-iconv (0.0.8)
(tar) Exporting gettext
Building project gettext (0.19.7)
Checking for 'C:\gtk-build\build\x64\release\gettext\build\win32\vs19\gettext.sln'
Checking for 'C:\gtk-build\build\x64\release\gettext\build\win32\ms-cl-19\gettext.sln'
CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell CMake that the project does not need compatibility with older versions.
Error: Solution file 'gettext.sln' for project 'gettext' not found!
Traceback (most recent call last):
    File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 493, in build
        if self.__build_one(p):
    File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 624, in __build_one 
        skip_deps = proj.build()
    File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 485, in build
        self.exec_msbuild_gen(r'build\win32', 'gettext.sln')
    File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 231, in exec_msbuild_gen
        log.error_exit("Solution file '%s' for project '%s' not found!" % (sln_file, self.name, ))
    File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\simple_ui.py", line 281, in error_exit
        sys.exit(1)
SystemExit: 1
Error: gettext build failed
```

**Comment by danyeaw** [comment]
@RaiZiStyle I think you'll want to use `--vs-ver=16" for Visual Studio 2019. Also, do you have the Visual Studio Build Tools installed? I normally install them with `choco install visualstudio2019-workload-vctools`.

**Comment by Akandesh** [comment]
> @RaiZiStyle I think you'll want to use `--vs-ver=16" for Visual Studio 2019. Also, do you have the Visual Studio Build Tools installed? I normally install them with `choco install visualstudio2019-workload-vctools`.

Thank you, I had same issue and this was the cause.
