### ISSUE TITLE
meson.build:2002:2: ERROR: Subproject exists but has no meson.build file

### ISSUE THREAD

**Issue by xingyun86** [wingtk/gvsbuild#477]
I use windows 10 x64: visual studio 2019 
I found this building problem：none meson.build in pcre-8.31/
```
Looking for a fallback subproject for the dependency libpcre

meson.build:2002:2: ERROR: Subproject exists but has no meson.build file

A full log can be found at C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-logs\meson-log.txt
Traceback (most recent call last):
  File "E:\gtk3build\gvsbuild-master\gvsbuild\utils\builder.py", line 589, in build
    if self.__build_one(p):
  File "E:\gtk3build\gvsbuild-master\gvsbuild\utils\builder.py", line 743, in __build_one
    skip_deps = proj.build()
  File "E:\gtk3build\gvsbuild-master\gvsbuild\projects.py", line 572, in build
    Meson.build(self)
  File "E:\gtk3build\gvsbuild-master\gvsbuild\utils\base_builders.py", line 78, in build
    self.exec_vs(cmd, add_path=add_path)
  File "E:\gtk3build\gvsbuild-master\gvsbuild\utils\base_project.py", line 109, in exec_vs
    cmd, working_dir=self._get_working_dir(), add_path=add_path
  File "E:\gtk3build\gvsbuild-master\gvsbuild\utils\builder.py", line 1048, in exec_vs
    env=self.vs_env,
  File "E:\gtk3build\gvsbuild-master\gvsbuild\utils\builder.py", line 1152, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "D:\DevelopmentEnvironment\Softwares\Python37x64\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\gtk-build\tools\python.3.10.0\tools\python.exe C:\gtk-build\tools\meson-0.57.1\meson.py C:\gtk-build\build\x64\release\glib C:\gtk-build\build\x64\release\glib\_gvsbuild-meson --prefix C:\gtk-build\gtk\x64\release --buildtype debugoptimized' returned non-zero exit status 1.
Error: glib build failed
```

**Comment by danyeaw** [comment]
@xingyun86 Thanks for the issue report. What command are you using to try to build the project?

**Comment by xingyun86** [comment]
> @xingyun86 Thanks for the issue report. What command are you using to try to build the project?

python .\build.py build -p=x64 --vs-ver=16 --msys-dir=D:\msys64 --gtk3-ver=3.24 gtk3

**Comment by danyeaw** [comment]
This seems related to #463.

What if you add the build option: `--from-scratch`? This is very similar to the build options that are passing on CI except you are using the D:\ for your msys-dir location.

**Comment by xingyun86** [comment]
> 
--from-scratch, I found it in gvsbuild/utils/parser.py:422. But I never modified it。Now my command is：

python .\build.py build -p=x64 --vs-ver=16 --msys-dir=D:\msys64 --gtk3-ver=3.24 gtk3

How I repair it？

**Comment by danyeaw** [comment]
`python .\build.py build -p=x64 --from-scratch --vs-ver=16 --msys-dir=D:\msys64 --gtk3-ver=3.24 gtk3`

**Comment by xingyun86** [comment]
> `python .\build.py build -p=x64 --from-scratch --vs-ver=16 --msys-dir=D:\msys64 --gtk3-ver=3.24 gtk3`

ok。Thanks very much！
