### ISSUE TITLE
Script can't download PCRE

### ISSUE THREAD

**Issue by Megadash452** [wingtk/gvsbuild#500]
I tried running the script with the following command: `python .\build.py build -p=x64 --vs-ver=16 --msys-dir=C:\msys64 gtk4`
and I get this error: `meson.build:2001:2: ERROR: could not get https://sourceforge.net/projects/pcre/files/pcre/8.37/pcre-8.37.tar.bz2 is the internet available?`

This is the same problem another user had [here](https://github.com/wingtk/gvsbuild/issues/453#issue-1028629150). The solution there is to download a certificate for PCRE from https://ftp.pcre.org/, but the link leads to a dead website. If someone knows where I can find the certificate.

The source forge file for PCRE still exists and I can download it manually.

Here is the error in more detail:
```
Run-time dependency libpcre found: NO (tried pkgconfig and cmake)
Library pcre found: NO
Run-time dependency libpcre found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libpcre
Downloading pcre source from https://sourceforge.net/projects/pcre/files/pcre/8.37/pcre-8.37.tar.bz2
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
A fallback URL could be specified using source_fallback_url key in the wrap file

meson.build:2001:2: ERROR: could not get https://sourceforge.net/projects/pcre/files/pcre/8.37/pcre-8.37.tar.bz2 is the internet available?

A full log can be found at C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-logs\meson-log.txt
Traceback (most recent call last):
  File "C:\Users\marti\source\repos\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 589, in build
    if self.__build_one(p):
  File "C:\Users\marti\source\repos\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 743, in __build_one
    skip_deps = proj.build()
  File "C:\Users\marti\source\repos\gtk-build\github\gvsbuild\gvsbuild\projects\glib.py", line 39, in build
    Meson.build(self)
  File "C:\Users\marti\source\repos\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 78, in build
    self.exec_vs(cmd, add_path=add_path)
  File "C:\Users\marti\source\repos\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 108, in exec_vs
    self.builder.exec_vs(
  File "C:\Users\marti\source\repos\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 1044, in exec_vs
    self.__execute(
  File "C:\Users\marti\source\repos\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 1152, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\gtk-build\tools\python.3.10.2\tools\python.exe C:\gtk-build\tools\meson-0.59.4\meson.py C:\gtk-build\build\x64\release\glib C:\gtk-build\build\x64\release\glib\_gvsbuild-meson --prefix C:\gtk-build\gtk\x64\release --buildtype debugoptimized' returned non-zero exit status 1.
Error: glib build failed
```

**Comment by bigvzhang** [comment]
I am also same problem. The site is not accessible.
