### ISSUE TITLE
lz4 build with vs2022 isn't possible

### ISSUE THREAD

**Issue by iAnyKey** [wingtk/gvsbuild#520]
topic.

The most recent supported toolchain for building `lz4` is VisualStudio 2017.

If on tries to build it using vs17 (default) (e.g. `python ./build.py build --build-dir=$pwd\\..\\gtk -p=x64 --vs-ver=17 --msys-dir="$pwd\\..\\msys64" lz4 && cd ..` it results in a error:

```
(tar) Exporting lz4
Building project lz4 (1.9.3)
Checking for 'C:\flan2\build\gvsbuild\\..\\gtk\build\x64\release\lz4\visual\vs17\lz4.sln'
Checking for 'C:\flan2\build\gvsbuild\\..\\gtk\build\x64\release\lz4\visual\vs2022\lz4.sln'
Error: Solution file 'lz4.sln' for project 'lz4' not found!
Traceback (most recent call last):
  File "C:\flan2\build\gvsbuild\gvsbuild\utils\builder.py", line 600, in build
    if self.__build_one(p):
  File "C:\flan2\build\gvsbuild\gvsbuild\utils\builder.py", line 754, in __build_one
    skip_deps = proj.build()
  File "C:\flan2\build\gvsbuild\gvsbuild\projects\lz4.py", line 34, in build
    self.exec_msbuild_gen(r"visual", "lz4.sln")
  File "C:\flan2\build\gvsbuild\gvsbuild\utils\base_project.py", line 324, in exec_msbuild_gen
    log.error_exit(
  File "C:\flan2\build\gvsbuild\gvsbuild\utils\simple_ui.py", line 312, in error_exit
    sys.exit(1)
SystemExit: 1
Error: lz4 build failed
```

**Comment by danyeaw** [comment]
Thanks @iAnyKey for the bug report. Lz4 supports meson, probably we should try to move from the visual studio solution file to using meson: https://github.com/lz4/lz4/tree/v1.9.3/contrib/meson
