### ISSUE TITLE
openssl build fails

### ISSUE THREAD

**Issue by danyeaw** [wingtk/gvsbuild#524]
I noticed this when updating libsoup in #523.

```
PS C:\gtk-build\github\gvsbuild> python .\build.py build -p=x64 --vs-ver=17 --vs-install-path="C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools" --msys-dir=C:\tools\msys64 openssl                        
Cleaning up the build environment
Checking msys tool
Checking Msvc tool
Downloading packages
Building project nuget (5.4.0)
Building project python ()
Building project perl (5.20.0)
Building project nasm (2.15.05)
Building project msys2 ()
(tar) Exporting openssl
Building project openssl (1.1.1n)
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 600, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 754, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects\openssl.py", line 58, in build
    self.exec_vs(
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 108, in exec_vs
    self.builder.exec_vs(
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 1055, in exec_vs
    self.__execute(
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 1163, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\gtk-build\tools\perl-5.20.0\x64\bin\perl.exe Configure VC-WIN64A no-ssl2 no-ssl3 no-comp --openssldir=C:\gtk-build\gtk\x64\release/etc/ssl --prefix=C:\gtk-build\gtk\x64\release' returned non-zero exit status 3221225781.
Error: openssl build failed
```

**Comment by nacho** [comment]
strange, something missing in your env? It seems to build fine on our builder

**Comment by lazka** [comment]
Likely vcredist2013 missing. I had to install it for the GNOME CI runner because of a similar error.

**Comment by danyeaw** [comment]
@lazka That was it, thanks! I updated the README and this issue is closed by https://github.com/wingtk/gvsbuild/commit/a3e4fea9dcd77c3bb7a1256c167438ad9dd7338d.
