### ISSUE TITLE
Quiche build fails with patch command not found error

### ISSUE THREAD

**Issue by danyeaw** [wingtk/gvsbuild#557]
```
HEAD is now at 09688f3 0.4.0
Fetch submodule(s)
Submodule 'boringssl' (https://github.com/google/boringssl.git) registered for path 'deps/boringssl'
Cloning into 'C:/gtk-build/src/git-exp/quiche/deps/boringssl'...
Submodule path 'deps/boringssl': checked out '239634da1be4e6c7e06f0fc28a1f5437bd6f5906'
Creating zip file C:\gtk-build\src\git\quiche-0_4_0 with 6521 files
Copying files from C:\gtk-build\github\gvsbuild\patches\quiche to C:\gtk-build\build\x64\release\quiche
Copying files from C:\gtk-build\github\gvsbuild\patches\quiche to C:\gtk-build\build\x64\release\quiche
(git) Exporting directory C:\gtk-build\build\x64\release\quiche
(git) Exporting quiche-0_4_0.zip
(git) Exporting fix_boringssl_build.patch
Building project quiche (git/0.4.0)
Applying patch fix_boringssl_build.patch
'patch' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 566, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 701, in __build_one
    proj.patch()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 355, in patch
    self.builder.exec_msys(
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 1059, in exec_msys
    self.__execute(
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 1094, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['patch', '-p1', '-i', 'fix_boringssl_build.patch']' returned non-zero exit status 1.
Error: quiche build failed
```

**Comment by danyeaw** [comment]
Fixed by a63f9b29816d0a511c9b6785f2fcb0e73a4b8dd2.
