### ISSUE TITLE
Build fails with unexpected error

### ISSUE THREAD

**Issue by xodix** [wingtk/gvsbuild#617]
## Command
(.venv) PS D:\CODE\rust\gtk\gvsbuild> gvsbuild build openssl

## Output
Cleaning up the build environment
Checking msys tool
Using C:\tools\msys64 for msys installation
Checking Msvc tool
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\CODE\rust\gtk\gvsbuild\.venv\Scripts\gvsbuild.exe\__main__.py", line 7, in <module>
  File "d:\code\rust\gtk\gvsbuild\.venv\lib\site-packages\gvsbuild\main.py", line 45, in build
    args.func(args)
  File "d:\code\rust\gtk\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\parser.py", line 162, in do_build
    builder = Builder(opts)
  File "d:\code\rust\gtk\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 126, in __init__
    self.__check_vs(opts)
  File "d:\code\rust\gtk\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 413, in __check_vs
    self.__dump_vs_loc()
  File "d:\code\rust\gtk\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 333, in __dump_vs_loc
    vs_installs = json.load(fi)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 596: character maps to <undefined>

**Comment by danyeaw** [comment]
@xodix Thanks for submitting the issue!

I can't reproduce this, however, it looks like we may need to specify an encoding to open the json file that vswhere is returning:

In the gvsbuild\utils\builder.py file, could you please change the vswhere command to specify that it outputs as utf-8 and the open command to use the utf-8 encoding?

```
        cmd = f'"{vswhere}" -all -prerelease -products * -format json -utf8 >{json_file}'
        self.exec_cmd(cmd)

        try:
            with open(json_file, encoding="utf-8") as fi:
                vs_installs = json.load(fi)
        except (IOError, OSError) as e:
            log.log(f"Exception reading vswhere result file ({e})")
```

If that fixes it for you, we would love to have a contribution from you to help fix it.

**Comment by xodix** [comment]
Modyfing the file helped with that step. However another error occured.

## Command
(.venv) PS D:\CODE\rust\gtk\gvsbuild> gvsbuild build gtk4

## Output
Cleaning up the build environment
Checking msys tool
Using C:\tools\msys64 for msys installation
Checking Msvc tool

Visual Studio installation(s) found:
    Visual Studio Community 2019 @ D:\visualStudioFiles

Using Visual Studio at None
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\CODE\rust\gtk\gvsbuild\.venv\Scripts\gvsbuild.exe\__main__.py", line 7, in <module>
  File "d:\code\rust\gtk\gvsbuild\.venv\lib\site-packages\gvsbuild\main.py", line 45, in build
    args.func(args)
  File "d:\code\rust\gtk\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\parser.py", line 162, in do_build
    builder = Builder(opts)
  File "d:\code\rust\gtk\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 126, in __init__
    self.__check_vs(opts)
  File "d:\code\rust\gtk\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 418, in __check_vs
    output = self.__check_good_vs_install(opts, opts.vs_install_path, True)
  File "d:\code\rust\gtk\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 364, in __check_good_vs_install
    vcvars_bat = os.path.join(vs_path, "VC", "bin", "amd64", "vcvars64.bat")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by xodix** [comment]
Should I create another issue for that?

**Comment by danyeaw** [comment]
Could you fork to the repo, create a new branch, and commit your change above? If not, I could also push it to a branch for you to test out.

This is a related problem, since it found your VS installation but then said `Using Visual Studio at None`. So the vs_path is set to None which shouldn't happen.
