### ISSUE TITLE
Unicode Decode Error when running build

### ISSUE THREAD

**Issue by new-divos** [wingtk/gvsbuild#624]
When I tried to build GTK library on Windows 10 using python 3.10.2 I got an error:

Cleaning up the build environment
Checking msys tool
Using C:\tools\msys64 for msys installation
Checking Msvc tool
Traceback (most recent call last):
  File "C:\Users\divos\.pyenv\pyenv-win\versions\3.10.2\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\divos\.pyenv\pyenv-win\versions\3.10.2\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\gtk-build\github\gvsbuild\.venv\Scripts\gvsbuild.exe\__main__.py", line 7, in <module>
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\main.py", line 45, in build
    args.func(args)
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\parser.py", line 162, in do_build
    builder = Builder(opts)
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 126, in __init__
    self.__check_vs(opts)
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 415, in __check_vs
    self.__dump_vs_loc()
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 335, in __dump_vs_loc
    vs_installs = json.load(fi)
  File "C:\Users\divos\.pyenv\pyenv-win\versions\3.10.2\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\divos\.pyenv\pyenv-win\versions\3.10.2\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 3095: invalid start byte

**Comment by danyeaw** [comment]
Hi @new-divos, we recently resolved a similar error with #618. Is this the latest version of gvsbuild?

**Comment by Trofimm** [comment]
I have the same thing. I do it according to the instructions for Windows 10.

Checking Msvc tool
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\gtk-build\github\gvsbuild\.venv\Scripts\gvsbuild.exe\__main__.py", line 7, in <module>
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\main.py", line 45, in build
    args.func(args)
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\parser.py", line 162, in do_build
    builder = Builder(opts)
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 126, in __init__
    self.__check_vs(opts)
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 415, in __check_vs
    self.__dump_vs_loc()
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 335, in __dump_vs_loc
    vs_installs = json.load(fi)
  File "C:\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaf in position 707: invalid start byte

**Comment by danyeaw** [comment]
What does `git rev-parse HEAD` display?

**Comment by Trofimm** [comment]
C:\gtk-build\github\gvsbuild>git rev-parse HEAD
fd7a2ac7a2fdd34cabaeb4fc638ea7faa22e5a3c

**Comment by danyeaw** [comment]
@new-divos and @Trofimm, I submitted PR #627 to fix this. Instead of saving the output of the vswhere command to a json file, it directly loads the output. If you want to give it a spin and see if it fixes the errors you were having, that would be greatly appreciated.

**Comment by Trofimm** [comment]
It works, thanks! ) I'm waiting for the assembly to be completed, I hope everything will come together...

**Comment by Trofimm** [comment]
It seems to have compiled.

Project(s) built:
    nuget                     (1.560 s)
    python                    (35.737 s)
    ninja                     (1.547 s)
    meson                     (10.016 s)
    pkg-config                (12.789 s)
    cmake                     (9.879 s)
    nasm                      (1.595 s)
    libjpeg-turbo             (32.568 s)
    libtiff-4                 (40.413 s)
    win-iconv                 (7.208 s)
    gettext                   (102.632 s)
    libffi                    (14.935 s)
    zlib                      (6.722 s)
    glib                      (121.309 s)
    libpng                    (11.827 s)
    gdk-pixbuf                (33.050 s)
    freetype                  (20.377 s)
    libxml2                   (38.069 s)
    fontconfig                (41.639 s)
    pixman                    (18.550 s)
    cairo                     (106.059 s)
    harfbuzz                  (67.555 s)
    fribidi                   (15.431 s)
    pango                     (32.335 s)
    libepoxy                  (22.347 s)
    graphene                  (15.433 s)
    gtk4                      (113.595 s)

**Comment by new-divos** [comment]
The same error. I can't understand what should I do

**Comment by Trofimm** [comment]
> The same error. I can't understand what should I do

Перейдите на ветку vswhere-no-file, где пофикшен этот баг или дождитесь пока они сольют её в мастер. Она стоит в очереди в пул реквестах.

**Comment by new-divos** [comment]
The new error:

Argument cannot be null or empty
Имя параметра: primarySources
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 531, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 624, in __build_one
    proj.prepare_build_dir()
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\base_project.py", line 390, in prepare_build_dir
    self.unpack()
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\tools.py", line 325, in unpack
    self.mark_deps = self.setup(True)
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\tools.py", line 298, in setup
    subprocess.check_call(cmd, shell=True)
  File "C:\Users\divos\.pyenv\pyenv-win\versions\3.10.5\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\gtk-build\tools\nuget-6.2.1\nuget.exe install python -Version 3.10.5 -OutputDirectory C:\gtk-build\tools' returned non-zero exit status 1.
Error: python build failed

**Comment by danyeaw** [comment]
@new-divos Since the original issue has been resolved, could you please open a new issue for the nuget error you are getting now?

This sounds like the same issue that was in https://github.com/wingtk/gvsbuild/issues/622. We may need to add a check that the nuget is setup properly, and run `C:\gtk-build\tools\nuget-6.2.1\nuget.exe source add -name .nuget -Source https://api.nuget.org/v3/index.json` if the feeds are empty.
