### ISSUE TITLE
Python install failed with "TypeError: __init__() got an unexpected keyword argument 'text'"

### ISSUE THREAD

**Issue by alphahui** [wingtk/gvsbuild#648]
I am currenty following this guide (https://fortran-lang.discourse.group/t/trying-to-get-gtk-fortran-to-work-in-vs2019-with-intel-fortran-compiler/747/21?page=2) to install gtk fortran (with the step of "pacman –S –needed base-devel mingw-w64-x86_64-toolchain switched to "pacman –S --needed base-devel mingw-w64-x86_64-toolchain” as -needed is not valid when entered). When I go to the step of Run “python build.py build –p x64 --vs-ver 16 gtk3”. I would recieve the following crash:

C:\gtk-build\github\gvsbuild>python build.py build -p x64 --vs-ver 16 gtk3
Running build.py directly is now deprecated, please run `pip install .`
Cleaning up the build environment
Checking msys tool
Using C:\Msys64 for msys installation
Checking Msvc tool
Traceback (most recent call last):
  File "build.py", line 38, in <module>
    build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\main.py", line 45, in build
    args.func(args)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\parser.py", line 162, in do_build
    builder = Builder(opts)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 126, in __init__
    self.__check_vs(opts)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 409, in __check_vs
    self.__dump_vs_loc()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 327, in __dump_vs_loc
    capture_output=True,
  File "C:\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'

Not sure why. Thank you for any reply!

**Comment by danyeaw** [comment]
Hi @alphahui, those installation steps are out of date. Please follow the steps in the README :+1:
