### ISSUE TITLE
build gtk3 - Error: glib build failed

### ISSUE THREAD

**Issue by evandromelos** [wingtk/gvsbuild#731]
Hey guys I'm having this problem when I run `gvsbuild build gtk3`
I've followed all the install steps and got this error.
Terminal log bellow:

```
Cleaning up the build environment
Checking msys tool
Using C:\tools\msys64 for msys installation
Checking Msvc tool

Visual Studio installation(s) found:
    Visual Studio Build Tools 2022 @ C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools

Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\xavero\.local\bin\gvsbuild.exe\__main__.py", line 7, in <module>
  File "C:\Users\xavero\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\main.py", line 45, in build
    args.func(args)
  File "C:\Users\xavero\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\parser.py", line 162, in do_build
    builder = Builder(opts)
              ^^^^^^^^^^^^^
  File "C:\Users\xavero\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 126, in __init__
    self.__check_vs(opts)
  File "C:\Users\xavero\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 412, in __check_vs
    output = self.__check_good_vs_install(opts, opts.vs_install_path, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xavero\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 381, in __check_good_vs_install
    return subprocess.check_output(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 465, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 1192, in communicate
    stdout = self.stdout.read()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\encodings\cp1252.py", line 22, in decode
    def decode(self, input, final=False):

KeyboardInterrupt
PS C:\Users\xavero> gvsbuild build gtk3
Cleaning up the build environment
Checking msys tool
Using C:\tools\msys64 for msys installation
Checking Msvc tool

Visual Studio installation(s) found:
    Visual Studio Build Tools 2022 @ C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools

Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
Downloading packages
Building project nuget (6.3.0)
Building project python ()
Building project ninja (1.11.0)
Building project meson (0.63.2)
(tar) Exporting pkg-config
Building project pkg-config (1.8.0)
[0/1] Installing files.Installing pkgconf-3.dll to C:\gtk-build\gtk\x64\release\bin
Installing pkgconf.lib to C:\gtk-build\gtk\x64\release\lib
Installing pkgconf-3.pdb to C:\gtk-build\gtk\x64\release\bin
Installing pkgconf.exe to C:\gtk-build\gtk\x64\release\bin
Installing pkgconf.pdb to C:\gtk-build\gtk\x64\release\bin
Installing C:\gtk-build\build\x64\release\pkgconf\libpkgconf\libpkgconf.h to C:\gtk-build\gtk\x64\release\include\pkgconf/libpkgconf
Installing C:\gtk-build\build\x64\release\pkgconf\libpkgconf\stdinc.h to C:\gtk-build\gtk\x64\release\include\pkgconf/libpkgconf
Installing C:\gtk-build\build\x64\release\pkgconf\libpkgconf\iter.h to C:\gtk-build\gtk\x64\release\include\pkgconf/libpkgconf
Installing C:\gtk-build\build\x64\release\pkgconf\libpkgconf\bsdstubs.h to C:\gtk-build\gtk\x64\release\include\pkgconf/libpkgconf
Installing C:\gtk-build\build\x64\release\pkgconf\libpkgconf\libpkgconf-api.h to C:\gtk-build\gtk\x64\release\include\pkgconf/libpkgconf
Installing C:\gtk-build\build\x64\release\pkgconf\man/pkgconf.1 to C:\gtk-build\gtk\x64\release\share/man\man1
Installing C:\gtk-build\build\x64\release\pkgconf\man/pkg.m4.7 to C:\gtk-build\gtk\x64\release\share/man\man7
Installing C:\gtk-build\build\x64\release\pkgconf\man/pc.5 to C:\gtk-build\gtk\x64\release\share/man\man5
Installing C:\gtk-build\build\x64\release\pkgconf\man/pkgconf-personality.5 to C:\gtk-build\gtk\x64\release\share/man\man5
Installing C:\gtk-build\build\x64\release\pkgconf\_gvsbuild-meson\meson-private\libpkgconf.pc to C:\gtk-build\gtk\x64\release\lib\pkgconfig
Installing C:\gtk-build\build\x64\release\pkgconf\pkg.m4 to C:\gtk-build\gtk\x64\release\share/aclocal
Installing C:\gtk-build\build\x64\release\pkgconf\AUTHORS to C:\gtk-build\gtk\x64\release\share/doc/pkgconf
Installing C:\gtk-build\build\x64\release\pkgconf\README.md to C:\gtk-build\gtk\x64\release\share/doc/pkgconf

        1 file(s) copied.
Building project cmake (3.24.2)
(tar) Exporting win-iconv
Building project win-iconv (0.0.8)
CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done
-- Generating done
-- Build files have been written to: C:/gtk-build/build/x64/release/win-iconv/_gvsbuild-cmake
ninja: no work to do.
[0/1] Running tests...Test project C:/gtk-build/build/x64/release/win-iconv/_gvsbuild-cmake
    Start 1: win_iconv_test
1/1 Test #1: win_iconv_test ...................   Passed    0.03 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.03 sec

[0/1] Install the project...-- Install configuration: "RelWithDebInfo"
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/lib/iconv.lib
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/bin/iconv.dll
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/bin/win_iconv.exe
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/include/iconv.h

(tar) Exporting gettext
Building project gettext (0.21)
(git) Updating directory C:\gtk-build\src\git-exp\libffi
HEAD is now at f0215d1 meson: Fix libffi.map generation when cross-compiling
(git) Exporting directory C:\gtk-build\build\x64\release\libffi
Building project libffi (git/meson-3.2.9999.4)
[0/1] Installing files.Installing src\ffi-7.dll to C:\gtk-build\gtk\x64\release\bin
Installing src\ffi.lib to C:\gtk-build\gtk\x64\release\lib
Installing src\ffi-7.pdb to C:\gtk-build\gtk\x64\release\bin
Installing C:\gtk-build\build\x64\release\libffi\man/ffi.3 to C:\gtk-build\gtk\x64\release\share/man\man3
Installing C:\gtk-build\build\x64\release\libffi\man/ffi_call.3 to C:\gtk-build\gtk\x64\release\share/man\man3
Installing C:\gtk-build\build\x64\release\libffi\man/ffi_prep_cif.3 to C:\gtk-build\gtk\x64\release\share/man\man3
Installing C:\gtk-build\build\x64\release\libffi\man/ffi_prep_cif_var.3 to C:\gtk-build\gtk\x64\release\share/man\man3
Installing C:\gtk-build\build\x64\release\libffi\_gvsbuild-meson\include\ffi-x86_64.h to C:\gtk-build\gtk\x64\release\include
Installing C:\gtk-build\build\x64\release\libffi\_gvsbuild-meson\include\ffitarget-x86_64.h to C:\gtk-build\gtk\x64\release\include
Installing C:\gtk-build\build\x64\release\libffi\_gvsbuild-meson\include\ffitarget.h to C:\gtk-build\gtk\x64\release\include
Installing C:\gtk-build\build\x64\release\libffi\_gvsbuild-meson\include\ffi.h to C:\gtk-build\gtk\x64\release\include
Installing C:\gtk-build\build\x64\release\libffi\_gvsbuild-meson\meson-private\libffi.pc to C:\gtk-build\gtk\x64\release\lib\pkgconfig

(tar) Exporting zlib
Building project zlib (1.2.13)
(tar) Exporting glib
Building project glib (2.72.4)
[8/284] Compiling C object gio/tests/task.exe.p/task.c.obj
../gio/tests/task.c(1394): warning C4267: '=': conversion from 'size_t' to 'gint', possible loss of data
[14/284] Generating gio/tests/test.gresource with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/test.gresource
"C:\gtk-build\tools\python.3.10.8\tools\python.exe" "C:\gtk-build\tools\meson-0.63.2\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_94f1b75b9d58c0f70108bcd4a087cb0cdd2d0cfa.dat"
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.63.2\meson.py", line 38, in <module>
    sys.exit(mesonmain.main())
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 266, in main
    return run(sys.argv[1:], launcher)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 255, in run
    return run_script_command(args[1], args[2:])
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 215, in run_script_command
    return module.run(script_args)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 123, in run
    return run_exe(exe)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 76, in run_exe
    raise FileNotFoundError('due to missing DLLs')
FileNotFoundError: due to missing DLLs
[15/284] Generating gio/tests/test_resources2.h with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/test_resources2.h
"C:\gtk-build\tools\python.3.10.8\tools\python.exe" "C:\gtk-build\tools\meson-0.63.2\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_dfae59d75c5df5e26e4f5683d21a51f3f77dcca4.dat"
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.63.2\meson.py", line 38, in <module>
    sys.exit(mesonmain.main())
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 266, in main
    return run(sys.argv[1:], launcher)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 255, in run
    return run_script_command(args[1], args[2:])
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 215, in run_script_command
    return module.run(script_args)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 123, in run
    return run_exe(exe)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 76, in run_exe
    raise FileNotFoundError('due to missing DLLs')
FileNotFoundError: due to missing DLLs
[17/284] Generating gio/tests/plugin-resources.c with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/plugin-resources.c
"C:\gtk-build\tools\python.3.10.8\tools\python.exe" "C:\gtk-build\tools\meson-0.63.2\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_97b81ecc61be5a9f78377590cf1da6e903418cb3.dat"
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.63.2\meson.py", line 38, in <module>
    sys.exit(mesonmain.main())
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 266, in main
    return run(sys.argv[1:], launcher)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 255, in run
    return run_script_command(args[1], args[2:])
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 215, in run_script_command
    return module.run(script_args)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 123, in run
    return run_exe(exe)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 76, in run_exe
    raise FileNotFoundError('due to missing DLLs')
FileNotFoundError: due to missing DLLs
[18/284] Generating gio/tests/test_resources2.c with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/test_resources2.c
"C:\gtk-build\tools\python.3.10.8\tools\python.exe" "C:\gtk-build\tools\meson-0.63.2\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_451f33be8fbb22f7f69397f5bec1851da4118513.dat"
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.63.2\meson.py", line 38, in <module>
    sys.exit(mesonmain.main())
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 266, in main
    return run(sys.argv[1:], launcher)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 255, in run
    return run_script_command(args[1], args[2:])
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 215, in run_script_command
    return module.run(script_args)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 123, in run
    return run_exe(exe)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 76, in run_exe
    raise FileNotFoundError('due to missing DLLs')
FileNotFoundError: due to missing DLLs
[19/284] Generating gio/tests/digit_test_resources.h with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/digit_test_resources.h
"C:\gtk-build\tools\python.3.10.8\tools\python.exe" "C:\gtk-build\tools\meson-0.63.2\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_0a88862b87428948f386bae168d5e046f23913fd.dat"
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.63.2\meson.py", line 38, in <module>
    sys.exit(mesonmain.main())
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 266, in main
    return run(sys.argv[1:], launcher)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 255, in run
    return run_script_command(args[1], args[2:])
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 215, in run_script_command
    return module.run(script_args)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 123, in run
    return run_exe(exe)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 76, in run_exe
    raise FileNotFoundError('due to missing DLLs')
FileNotFoundError: due to missing DLLs
[20/284] Generating gio/tests/digit_test_resources.c with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/digit_test_resources.c
"C:\gtk-build\tools\python.3.10.8\tools\python.exe" "C:\gtk-build\tools\meson-0.63.2\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_48d746b50717d5d12717226362b857e068aa8b05.dat"
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.63.2\meson.py", line 38, in <module>
    sys.exit(mesonmain.main())
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 266, in main
    return run(sys.argv[1:], launcher)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 255, in run
    return run_script_command(args[1], args[2:])
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 215, in run_script_command
    return module.run(script_args)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 123, in run
    return run_exe(exe)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 76, in run_exe
    raise FileNotFoundError('due to missing DLLs')
FileNotFoundError: due to missing DLLs
[22/284] Generating gio/tests/test_resources.c with a custom command (wrapped by meson to set PATH)
FAILED: gio/tests/test_resources.c
"C:\gtk-build\tools\python.3.10.8\tools\python.exe" "C:\gtk-build\tools\meson-0.63.2\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\meson-private\meson_exe_glib-compile-resources_54e5f48f8737da87d8c1800550bc01136ed29706.dat"
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.63.2\meson.py", line 38, in <module>
    sys.exit(mesonmain.main())
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 266, in main
    return run(sys.argv[1:], launcher)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 255, in run
    return run_script_command(args[1], args[2:])
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\mesonmain.py", line 215, in run_script_command
    return module.run(script_args)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 123, in run
    return run_exe(exe)
  File "C:\gtk-build\tools\meson-0.63.2\mesonbuild\scripts\meson_exe.py", line 76, in run_exe
    raise FileNotFoundError('due to missing DLLs')
FileNotFoundError: due to missing DLLs
[23/284] Compiling C object gio/tests/testfilemonitor.exe.p/testfilemonitor.c.obj
../gio/tests/testfilemonitor.c(249): warning C4456: declaration of 'l' hides previous local declaration
../gio/tests/testfilemonitor.c(134): note: see declaration of 'l'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\xavero\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 531, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xavero\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 667, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\Users\xavero\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\projects\glib.py", line 40, in build
    Meson.build(self)
  File "C:\Users\xavero\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_builders.py", line 56, in build
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "C:\Users\xavero\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 989, in exec_ninja
    self.__execute(
  File "C:\Users\xavero\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 1045, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: glib build failed
```

**Comment by danyeaw** [comment]
Hi @evandromelos, I'm not sure why you are getting that error. Have you tried to run `gvsbuild build --from-scratch gtk3` to start over with a clean environment?

**Comment by evandromelos** [comment]
I need to build it for VS2019 so should I run `gvsbuild build --from-scratch --vs-ver 16 gtk3`, right?

**Comment by evandromelos** [comment]
I ran `gvsbuild build --from-scratch --vs-ver 16 gtk3` and it works!

**Comment by evandromelos** [comment]
Context: 
I had a `env` called `PKG_CONFIG_PATH` due to gstreamer, I've removed it and it builds fine.

Thanks @danyeaw.

**Comment by danyeaw** [comment]
Great, I'm glad you figured it out! Do you think this is a common enough thing that we should put a note about it in the README?

**Comment by evandromelos** [comment]
Hey @danyeaw.
I don;t think so.
Our implementation is using gstreamer on rust so we have more things to handle  and had to re-build gtk3 and that it was a problem, if you someone start from the scratch and follow the readme it works fine. 
Thanks again for your time.
