### ISSUE TITLE
Emeus build gives error for function does not take positional arguments.

### ISSUE THREAD

**Issue by danyeaw** [wingtk/gvsbuild#789]
I am getting the following error when trying to build emeus using `gvsbuild build emeus`:

```
(git) Cloning https://github.com/ebassi/emeus.git to C:\gtk-build\src\git-exp\emeus
Cloning into 'C:\gtk-build\src\git-exp\emeus'...
remote: Enumerating objects: 1693, done.
remote: Total 1693 (delta 0), reused 0 (delta 0), pack-reused 1693
Receiving objects: 100% (1693/1693), 456.87 KiB | 791.00 KiB/s, done.
Resolving deltas: 100% (1196/1196), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
(git) Exporting directory C:\gtk-build\build\x64\release\emeus
Building project emeus (git/master)
(Stripping trailing CRs from patch; use --binary to disable.)
patching file meson.build
The Meson build system
Version: 0.64.1
Source dir: C:\gtk-build\build\x64\release\emeus
Build dir: C:\gtk-build\build\x64\release\emeus\_gvsbuild-meson
Build type: native build
Project name: emeus
Project version: 0.99.1
C compiler for the host machine: cl (msvc 19.34.31937 "Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x64")
C linker for the host machine: link link 14.34.31937.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -fstrict-aliasing: NO 
Compiler for C supports arguments -Wpointer-arith: NO 
Compiler for C supports arguments -Wmissing-declarations: NO 
Compiler for C supports arguments -Wmissing-noreturn: NO 
Compiler for C supports arguments -Wmissing-format-attribute: NO 
Compiler for C supports arguments -Wmissing-prototypes: NO 
Compiler for C supports arguments -Wformat=2: NO 
Compiler for C supports arguments -Wstrict-prototypes: NO 
Compiler for C supports arguments -Wnested-externs: NO 
Compiler for C supports arguments -Wold-style-definition: NO 
Compiler for C supports arguments -Wunused: NO 
Compiler for C supports arguments -Wuninitialized: NO 
Compiler for C supports arguments -Wshadow: NO 
Compiler for C supports arguments -Wredundant-decls: NO 
Compiler for C supports arguments -Wlogical-op: NO 
Compiler for C supports arguments -Wcast-align: NO 
Compiler for C supports arguments -Wno-unused-local-typedefs: NO 
Compiler for C supports arguments -Werror=implicit: NO 
Compiler for C supports arguments -Werror=init-self: NO 
Compiler for C supports arguments -Werror=main: NO 
Compiler for C supports arguments -Werror=missing-braces: NO 
Compiler for C supports arguments -Werror=return-type: NO 
Compiler for C supports arguments -Werror=array-bounds: NO 
Compiler for C supports arguments -Werror=write-strings: NO 
Has header "stdlib.h" : YES 
Has header "stdint.h" : YES 
Has header "stdbool.h" : YES 
Library m found: NO
Found pkg-config: C:\gtk-build\gtk\x64\release\bin\pkg-config.EXE (1.9.3)
Run-time dependency glib-2.0 found: YES 2.74.1
Run-time dependency gtk+-3.0 found: YES 3.24.35
Configuring config.h using configuration
src\meson.build:47: WARNING: Project targets '>= 0.43.0' but uses feature introduced in '0.50.0': install arg in configure_file.
Configuring emeus-version.h using configuration

src\tools\meson.build:8:5: ERROR: Function does not take positional arguments.

A full log can be found at C:\gtk-build\build\x64\release\emeus\_gvsbuild-meson\meson-logs\meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 663, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects\emeus.py", line 46, in build
    Meson.build(self, make_tests=True)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 49, in build
    self._setup_meson_and_ninja(ninja_build, meson_params, add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 80, in _setup_meson_and_ninja
    self.exec_vs(cmd, add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 193, in exec_vs
    self.builder.exec_vs(
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 937, in exec_vs
    self.__execute(
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 1039, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\dan\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\gtk-build\github\gvsbuild\.venv\Scripts\python.exe C:\gtk-build\tools\meson-0.64.1\meson.py C:\gtk-build\build\x64\relea
se\emeus C:\gtk-build\build\x64\release\emeus\_gvsbuild-meson --prefix C:\gtk-build\gtk\x64\release -Ddocs=false -Dintrospection=false --buildtype debugoptimized' returned non-zero exit status 1.
Error: emeus build failed
```

**Comment by danyeaw** [comment]
Fixed by https://github.com/ebassi/emeus/pull/41
