### ISSUE TITLE
freetype-6.dll : fatal error LNK1120: 11 unresolved externals

### ISSUE THREAD

**Issue by tjwilli58** [wingtk/gvsbuild#795]
Trying to build gtk3 with `gvsbuild build gtk3`. Everything seems to be going fine until it gets to building the `freetype` project. I just cloned the repos, created and activated a venv, then tried:

`gvsbuild build gtk3`

```
Build targets in project: 5

freetype2 2.12.1

  Operating System
    OS       : windows

  Used Libraries
    Zlib     : system
    Bzip2    : no
    Png      : yes
    Harfbuzz : yes
    Brotli   : no

  User defined options
    buildtype: debugoptimized
    prefix   : C:\gtk-build\gtk\x64\release

Found ninja-1.11.1 at C:\gtk-build\tools\ninja-1.11.1\ninja.EXE
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
[45/46] Linking target freetype-6.dll
FAILED: freetype-6.dll freetype-6.pdb
"link"  /MACHINE:x64 /OUT:freetype-6.dll src_base_ftver.rc_ftver.res freetype-6.dll.p/src_base_ftbase.c.obj freetype-6.dll.p/src_base_ftinit.c.obj freetype-6.dll.p/src_truetype_truetype.c.obj freetype-6.dll.p/src_type1_type1.c.obj freetype-6.dll.p/src_cff_cff.c.obj freetype-6.dll.p/src_cid_type1cid.c.obj freetype-6.dll.p/src_pfr_pfr.c.obj freetype-6.dll.p/src_type42_type42.c.obj freetype-6.dll.p/src_winfonts_winfnt.c.obj freetype-6.dll.p/src_pcf_pcf.c.obj freetype-6.dll.p/src_bdf_bdf.c.obj freetype-6.dll.p/src_sfnt_sfnt.c.obj freetype-6.dll.p/src_autofit_autofit.c.obj freetype-6.dll.p/src_pshinter_pshinter.c.obj freetype-6.dll.p/src_smooth_smooth.c.obj freetype-6.dll.p/src_raster_raster.c.obj freetype-6.dll.p/src_svg_svg.c.obj freetype-6.dll.p/src_sdf_sdf.c.obj freetype-6.dll.p/src_cache_ftcache.c.obj freetype-6.dll.p/src_gzip_ftgzip.c.obj freetype-6.dll.p/src_lzw_ftlzw.c.obj freetype-6.dll.p/src_psaux_psaux.c.obj freetype-6.dll.p/src_psnames_psnames.c.obj freetype-6.dll.p/src_base_ftbbox.c.obj freetype-6.dll.p/src_base_ftbdf.c.obj freetype-6.dll.p/src_base_ftbitmap.c.obj freetype-6.dll.p/src_base_ftcid.c.obj freetype-6.dll.p/src_base_ftfstype.c.obj freetype-6.dll.p/src_base_ftgasp.c.obj freetype-6.dll.p/src_base_ftglyph.c.obj freetype-6.dll.p/src_base_ftgxval.c.obj freetype-6.dll.p/src_base_ftmm.c.obj freetype-6.dll.p/src_base_ftotval.c.obj freetype-6.dll.p/src_base_ftpatent.c.obj freetype-6.dll.p/src_base_ftpfr.c.obj freetype-6.dll.p/src_base_ftstroke.c.obj freetype-6.dll.p/src_base_ftsynth.c.obj freetype-6.dll.p/src_base_fttype1.c.obj freetype-6.dll.p/src_base_ftwinfnt.c.obj freetype-6.dll.p/builds_windows_ftsystem.c.obj freetype-6.dll.p/builds_windows_ftdebug.c.obj "/nologo" "/release" "/nologo" "/DEBUG" "/PDB:freetype-6.pdb" "/DLL" "/IMPLIB:freetype.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/zlib1.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/libpng16.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/harfbuzz.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
   Creating library freetype.lib and object freetype.exp
harfbuzz.lib(harfbuzz.cc.obj) : error LNK2019: unresolved external symbol g_bytes_get_data referenced in function hb_glib_blob_create
harfbuzz.lib(harfbuzz.cc.obj) : error LNK2019: unresolved external symbol g_bytes_ref referenced in function hb_glib_blob_create
harfbuzz.lib(harfbuzz.cc.obj) : error LNK2019: unresolved external symbol g_bytes_unref referenced in function "void __cdecl _hb_g_bytes_unref(void *)" (?_hb_g_bytes_unref@@YAXPEAX@Z)
harfbuzz.lib(harfbuzz.cc.obj) : error LNK2019: unresolved external symbol g_unicode_script_to_iso15924 referenced in function hb_glib_script_to_script
harfbuzz.lib(harfbuzz.cc.obj) : error LNK2019: unresolved external symbol g_unicode_script_from_iso15924 referenced in function hb_glib_script_from_script
harfbuzz.lib(harfbuzz.cc.obj) : error LNK2019: unresolved external symbol g_unichar_type referenced in function "enum hb_unicode_general_category_t __cdecl hb_glib_unicode_general_category(struct hb_unicode_funcs_t *,unsigned int,void *)" (?hb_glib_unicode_general_category@@YA?AW4hb_unicode_general_category_t@@PEAUhb_unicode_funcs_t@@IPEAX@Z)
harfbuzz.lib(harfbuzz.cc.obj) : error LNK2019: unresolved external symbol g_unichar_combining_class referenced in function "enum hb_unicode_combining_class_t __cdecl hb_glib_unicode_combining_class(struct hb_unicode_funcs_t *,unsigned int,void *)" (?hb_glib_unicode_combining_class@@YA?AW4hb_unicode_combining_class_t@@PEAUhb_unicode_funcs_t@@IPEAX@Z)
harfbuzz.lib(harfbuzz.cc.obj) : error LNK2019: unresolved external symbol g_unichar_get_mirror_char referenced in function "unsigned int __cdecl hb_glib_unicode_mirroring(struct hb_unicode_funcs_t *,unsigned int,void *)" (?hb_glib_unicode_mirroring@@YAIPEAUhb_unicode_funcs_t@@IPEAX@Z)
harfbuzz.lib(harfbuzz.cc.obj) : error LNK2019: unresolved external symbol g_unichar_get_script referenced in function "enum hb_script_t __cdecl hb_glib_unicode_script(struct hb_unicode_funcs_t *,unsigned int,void *)" (?hb_glib_unicode_script@@YA?AW4hb_script_t@@PEAUhb_unicode_funcs_t@@IPEAX@Z)
harfbuzz.lib(harfbuzz.cc.obj) : error LNK2019: unresolved external symbol g_unichar_compose referenced in function "int __cdecl hb_glib_unicode_compose(struct hb_unicode_funcs_t *,unsigned int,unsigned int,unsigned int *,void *)" (?hb_glib_unicode_compose@@YAHPEAUhb_unicode_funcs_t@@IIPEAIPEAX@Z)
harfbuzz.lib(harfbuzz.cc.obj) : error LNK2019: unresolved external symbol g_unichar_decompose referenced in function "int __cdecl hb_glib_unicode_decompose(struct hb_unicode_funcs_t *,unsigned int,unsigned int *,unsigned int *,void *)" (?hb_glib_unicode_decompose@@YAHPEAUhb_unicode_funcs_t@@IPEAI1PEAX@Z)
freetype-6.dll : fatal error LNK1120: 11 unresolved externals
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 663, in __build_one
    skip_deps = proj.build()
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\projects\freetype.py", line 38, in build
    Meson.build(self)
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\base_builders.py", line 58, in build
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 983, in exec_ninja
    self.__execute(
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 1039, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\Tim\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: freetype build failed
```

**Comment by danyeaw** [comment]
@tjwilli58 Thanks for the bug report. Which version of msvc do you have installed?

**Comment by tjwilli58** [comment]
vs2017, vs2019, vs2022. I was using vs022 at the time.
I also did 
`choco install visualstudio2022-workload-vctools`

I'm a little reluctant to use Chocalately, because I'm not so sure what I'm installing that way, but figured maybe that's why  I've been having issues. Doing that didn't help though.

**Comment by danyeaw** [comment]
Could you also please try to run `gvsbuild build --from-scratch gtk3` to make sure that any previous builds are cleared out?

**Comment by tjwilli58** [comment]
That worked! Thanks!
Now on to gst-python ...

```
Project(s) built:
    ninja                     (1.550 s)
    meson                     (9.626 s)
    pkgconf                   (15.846 s)
    cmake                     (9.579 s)
    win-iconv                 (7.803 s)
    gettext                   (145.775 s)
    libffi                    (19.165 s)
    zlib                      (6.653 s)
    pcre2                     (44.102 s)
    glib                      (263.026 s)
    atk                       (27.680 s)
    nasm                      (1.564 s)
    libjpeg-turbo             (72.511 s)
    libtiff-4                 (52.246 s)
    libpng                    (17.779 s)
    gdk-pixbuf                (52.858 s)
    freetype                  (25.086 s)
    gperf                     (10.395 s)
    expat                     (22.957 s)
    fontconfig                (33.455 s)
    pixman                    (26.471 s)
    cairo                     (163.092 s)
    harfbuzz                  (197.985 s)
    fribidi                   (19.226 s)
    pango                     (44.281 s)
    libepoxy                  (23.853 s)
    gtk3                      (323.045 s)
```

**Comment by danyeaw** [comment]
Yay, glad you got it working!
