### ISSUE TITLE
problem building gst-python: Run-time dependency gstreamer-plugins-base-1.0 found: NO (tried pkgconfig and cmake)

### ISSUE THREAD

**Issue by tjwilli58** [wingtk/gvsbuild#796]
I'm trying to build gst-python using `gvsbuild` and ran into this error:

```
Run-time dependency gstreamer-plugins-base-1.0 found: NO (tried pkgconfig and cmake)

testsuite\meson.build:25:2: ERROR: No default provided for dependency <NotFoundDependency gstreamer-plugins-base-1.0: False>, which is not pkg-config, cmake, or config-tool based.

A full log can be found at C:\gtk-build\build\x64\release\gst-python\_gvsbuild-meson\meson-logs\meson-log.txt

```
The file `C:\gtk-build\build\x64\release\gst-python\_gvsbuild-meson\meson-logs\meson-log.txt` doesn't exist. There is an empty folder `C:\gtk-build\build\x64\release\gst-python-rel`.

I set my PATH to find gstreamer, and can run this pipeline successfully, so I know at least that the gstreamer binaries are found:

`gst-launch-1.0.exe videotestsrc ! autovideosink`

Any help is appreciated.

**Comment by tjwilli58** [comment]
Trying to add `%GSTREAMER_1_0_ROOT_MSVC_X86_64%\lib` to PATH.

**Comment by tjwilli58** [comment]
nope

**Comment by danyeaw** [comment]
Does it work to run `gvsbuild build --enable-gi gst-plugins-base gst-python`? Maybe we need to make gst-plugins-base a dependency of gst-python

**Comment by tjwilli58** [comment]
No. It fails with this:

```
[57/774] Generating gst-libs/gst/tag/GstTag-1.0.gir with a custom command (wrapped by meson to set PATH, to set env)
FAILED: gst-libs/gst/tag/GstTag-1.0.gir
"d:\GitClones\gvsbuild\.venv\Scripts\python.exe" "C:\gtk-build\tools\meson-1.0.0\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\gst-plugins-base\_gvsbuild-meson\meson-private\meson_exe_python.exe_0a74008b99ac007e58c61686508356e9e5408160.dat"
while executing ['d:\\GitClones\\gvsbuild\\.venv\\Scripts\\python.exe', 'C:/gtk-build/gtk/x64/release/bin/../bin/g-ir-scanner', '--quiet', '--no-libtool', '--namespace=GstTag', '--nsversion=1.0', '--warn-all', '--output', 'gst-libs/gst/tag/GstTag-1.0.gir', '--add-init-section=extern void gst_init(gint*,gchar**);g_setenv("GST_REGISTRY_DISABLE", "yes", TRUE);g_setenv("GST_REGISTRY_1.0", "C:/gtk-build/build/x64/release/gst-plugins-base/_gvsbuild-meson/gir_empty_registry.reg", TRUE);g_setenv("GST_PLUGIN_PATH_1_0", "", TRUE);g_setenv("GST_PLUGIN_SYSTEM_PATH_1_0", "", TRUE);gst_init(NULL,NULL);', '--quiet', '--c-include=gst/tag/tag.h', '-IC:/gtk-build/build/x64/release/gst-plugins-base/gst-libs/gst/tag', '-IC:/gtk-build/build/x64/release/gst-plugins-base/_gvsbuild-meson/gst-libs/gst/tag', '-IC:/gtk-build/build/x64/release/gst-plugins-base/.', '-IC:/gtk-build/build/x64/release/gst-plugins-base/_gvsbuild-meson/.', '-IC:/gtk-build/build/x64/release/gst-plugins-base/gst-libs', '-IC:/gtk-build/build/x64/release/gst-plugins-base/_gvsbuild-meson/gst-libs', '--filelist=C:/gtk-build/build/x64/release/gst-plugins-base/_gvsbuild-meson/gst-libs/gst/tag/gsttag-1.0-0.dll.p/GstTag_1.0_gir_filelist', '--include=Gst-1.0', '--include=GstBase-1.0', '--symbol-prefix=gst', '--identifier-prefix=Gst', '--pkg-export=gstreamer-tag-1.0', '--cflags-begin', '-DG_DISABLE_CAST_CHECKS', '-IC:/gtk-build/build/x64/release/gst-plugins-base/.', '-IC:/gtk-build/build/x64/release/gst-plugins-base/_gvsbuild-meson/.', '-IC:/gtk-build/build/x64/release/gst-plugins-base/gst-libs', '-IC:/gtk-build/build/x64/release/gst-plugins-base/_gvsbuild-meson/gst-libs', '-IC:/gtk-build/gtk/x64/release/bin/../include', '-IC:/gtk-build/gtk/x64/release/bin/../include/gstreamer-1.0', '-IC:/gtk-build/gtk/x64/release/bin/../include/glib-2.0', '-IC:/gtk-build/gtk/x64/release/bin/../lib/glib-2.0/include', '-IC:/gtk-build/gtk/x64/release/bin/../include/gobject-introspection-1.0', '--cflags-end', '--add-include-path=C:/gtk-build/gtk/x64/release/bin/../share/gir-1.0', '-LC:/gtk-build/build/x64/release/gst-plugins-base/_gvsbuild-meson/gst-libs/gst/tag', '--library', 'gsttag-1.0', '-LC:/gtk-build/gtk/x64/release/bin/../lib', '-LC:/gtk-build/gtk/x64/release/bin/../lib', '--extra-library=gmodule-2.0', '--extra-library=gstbase-1.0', '--extra-library=gstreamer-1.0', '--extra-library=glib-2.0', '--extra-library=intl', '--extra-library=gobject-2.0', '--extra-library=zlib1', '--extra-library=girepository-1.0', '--sources-top-dirs', 'C:/gtk-build/build/x64/release/gst-plugins-base/', '--sources-top-dirs', 'C:/gtk-build/build/x64/release/gst-plugins-base/_gvsbuild-meson/']
--- stdout ---

--- stderr ---
Couldn't find include 'Gst-1.0.gir' (search path: '['C:/gtk-build/gtk/x64/release/bin/../share/gir-1.0', 'C:\\gtk-build\\gtk\\x64\\release\\share', 'gir-1.0', 'C:\\gtk-build\\gtk\\x64\\release\\share\\gir-1.0']')

[62/774] Compiling C object gst-libs/gst/video/gstvideo-1.0-0.dll.p/video-blend.c.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 663, in __build_one
    skip_deps = proj.build()
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\projects\gstreamer.py", line 108, in build
    Meson.build(self)
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\base_builders.py", line 58, in build
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 983, in exec_ninja
    self.__execute(
  File "d:\GitClones\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 1039, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\Tim\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: gst-plugins-base build failed
```
I'm going to and add `--clean` and see what happens.

**Comment by tjwilli58** [comment]
That did it.
```
Project(s) built:
    meson                     (12.743 s)
    ninja                     (1.525 s)
    pkgconf                   (13.017 s)
    cmake                     (13.743 s)
    win-iconv                 (8.269 s)
    gettext                   (150.241 s)
    libffi                    (17.549 s)
    zlib                      (7.483 s)
    pcre2                     (41.643 s)
    glib                      (255.138 s)
    msys2                     (0.016 s)
    gobject-introspection     (115.297 s)
    atk                       (40.190 s)
    nasm                      (1.547 s)
    libjpeg-turbo             (74.873 s)
    libtiff-4                 (55.684 s)
    libpng                    (18.774 s)
    gdk-pixbuf                (70.238 s)
    freetype                  (27.201 s)
    gperf                     (12.500 s)
    expat                     (23.613 s)
    fontconfig                (34.492 s)
    pixman                    (30.363 s)
    cairo                     (153.738 s)
    harfbuzz                  (210.965 s)
    fribidi                   (17.928 s)
    pango                     (73.907 s)
    libepoxy                  (25.452 s)
    gtk3                      (421.809 s)
    orc                       (29.221 s)
    gstreamer                 (99.061 s)
    opus                      (31.688 s)
    gst-plugins-base          (241.497 s)
    pycairo                   (68.878 s)
    pygobject                 (109.996 s)
    gst-python                (20.327 s)
```
Now to see if I can use it!

**Comment by danyeaw** [comment]
I can reproduce this issue if I build gst-python without gst-plugins-base. I'll submit a PR to update the dependencies.

**Comment by tjwilli58** [comment]
I set my PYTHONPATH, but when I try to `import gi`, I get 
```
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\gstreamer\tjwbuild\gtk\x64\release\lib\site-packages\gi\__init__.py", line 47, in <module>
    from . import _gi
ImportError: DLL load failed while importing _gi: The specified module could not be found.
```
Then I found the [issue ](https://gitlab.gnome.org/GNOME/pygobject/-/issues/545) you created on pygobject. 
Oh well.

**Comment by danyeaw** [comment]
Giving that issue a thumbs up or commenting that you ran in to it would hopefully help us get it fixed. You have a couple of options:

Use Python Wheels built by gvsbuild
1. Run `gvsbuild build --enable-gi --py-wheel gobject-introspection`
2. `poetry run pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pygobject\dist\PyGObject*.whl)`

Pip install PyGObject like normally, but run `os.add_dll_directory` before importing gi
```
import os
os.add_dll_directory("C:/gtk-build/gtk/x64/release/bin")
import gi
```

**Comment by tjwilli58** [comment]
Thanks @danyeaw for helping me get `gst-python, pygobject` et al built. However, not I find that [GstInsertBin ](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad-libs/html/gst-plugins-bad-libs-GstInsertbin.html) isn't there. 

```python
>>> gi.require_version('GstInsertBin','1.0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\anaconda3\envs\fieldcapenvpy39_pyqt\lib\site-packages\gi\__init__.py", line 139, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GstInsertBin not available
```

I added a comment on a 4-year old open issue about it.
https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/issues/164

**Comment by tjwilli58** [comment]
I realized that I forgot to build `gst-plugins-bad`. 

```python
>>> gi.require_version('GstInsertBin','1.0')
>>> from gi.repository import GstInsertBin
>>> dir(GstInsertBin)
['InsertBin', 'InsertBinClass', 'InsertBinPrivate', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__file__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__loader__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__package__', '__path__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__spec__', '__str__', '__subclasshook__', '__weakref__', '_namespace', '_version']
```

**Comment by danyeaw** [comment]
Nice @tjwilli58, glad you figured it out!

**Comment by tjwilli58** [comment]
2023.6.0
I'm using the latest commit from the repos.

Author:		Dan Yeaw <dan@yeaw.me>
Author date:	2 days ago (6/8/2023 8:19:11 PM)
Committer:	Ignacio Casal Quinteiro <nacho.resa@gmail.com>
Commit date:	2 days ago (6/9/2023 3:08:21 AM)
Commit hash:	0f8553f2c39dc8437540cdb5370e5cebe8a5eb7c
Child:		Commit index
Parent:		979a32e0

Update librsvg to version 2.56.1
Contained in branches:
main

Contained in no tag

Derives from tag: 2023.6.0 + 5 commits
