### ISSUE TITLE
pygobject - ImportError: DLL load failed while importing _gi: The specified module could not be found.

### ISSUE THREAD

**Issue by coolcatco888** [wingtk/gvsbuild#842]
I followed the [guide](https://github.com/wingtk/gvsbuild) to build gtk3 and pyobject however, I cannot import any python gtk libraries.

Commands to build:
```
gvsbuild build gtk3
gvsbuild build pygobject
```

Failure encountered when trying to import gi:
```
PS C:\WINDOWS\system32> pip install pygobject
Requirement already satisfied: pygobject in c:\program files\python311\lib\site-packages (3.42.2)
Requirement already satisfied: pycairo>=1.16.0 in c:\users\cley\appdata\roaming\python\python311\site-packages (from pygobject) (1.23.0)
PS C:\WINDOWS\system32> python
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\gi\__init__.py", line 40, in <module>
    from . import _gi
ImportError: DLL load failed while importing _gi: The specified module could not be found.
```

**Comment by danyeaw** [comment]
Hi @coolcatco888, if you want to use pygobject you need to run the following:

```
> gvsbuild build --enable-gi --py-wheel gtk3 pygobject
```
Once that finishes, then you need to use the gvsbuild generated wheels:

```
> pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pygobject\dist\PyGObject*.whl)
> pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pycairo\dist\pycairo*.whl)
```
I would also highly recommend using a virtualenv.

These steps are needed because upstream patches in PyGObject and pycairo haven't been merged yet, so we have to patch those libraries ourselves and build the wheels using gvsbuild. If these get merged, then this won't be required:
https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/211
https://github.com/pygobject/pycairo/pull/305

Another option is you can manually run `os.add_dll_directory` prior to running `import gi`.

If these instructions help you get it working, would you mind helping us update the README to make it more clear for everyone?

**Comment by coolcatco888** [comment]
Thanks for your help! I am getting this error now after importing:

```
PS C:\temp> & "C:/Program Files/Python311/python.exe" c:/temp/main.py
Traceback (most recent call last):
  File "c:\temp\main.py", line 2, in <module>
    from ui.mainwindow import MainWindow
  File"c:\temp\main.py", line 16, in <module>
    gi.require_version("Gtk", "3.0")
  File "C:\Program Files\Python311\Lib\site-packages\gi\__init__.py", line 139, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
PS C:\temp> 
```

**Comment by danyeaw** [comment]
Could you please try with a virtualenv?

**Comment by coolcatco888** [comment]
> Could you please try with a virtualenv?

Sorry, not sure I follow. Did you want me to try to setup my environment in Windows running in a VM?

**Comment by danyeaw** [comment]
@coolcatco888 I mean a Python virtualenv: https://docs.python.org/3/tutorial/venv.html

**Comment by manuvarkey** [comment]
@danyeaw 

I am affected by the same issue. Build proceeds without errors. After running the following commands in venv,

```
pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pygobject\dist\PyGObject*.whl)
pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pycairo\dist\pycairo*.whl)
```

Running the following program.

```
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```

Error is displayed at `gi.require_version("Gtk", "3.0")`

```
Traceback (most recent call last):
  File "C:\Users\EEE\test.py", line 2, in <module>
    gi.require_version("Gtk", "3.0")
  File "C:\Python311\Lib\site-packages\gi\__init__.py", line 139, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

**Comment by manuvarkey** [comment]
Output of  `$env:PATH -split ';'` in powershell is given below. 


```
C:\Users\EEE\python_env\Scripts
C:\gtk-build\gtk\x64\release\bin
C:\gtk-build\gtk\x64\release\lib
C:\Python311\Scripts\
C:\Python311\
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\ProgramData\Oracle\Java\javapath
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\Aladdin\eToken\PKIClient\x32
C:\Program Files\Aladdin\eToken\PKIClient\x64
C:\ProgramData\chocolatey\bin
C:\Program Files\Git\cmd
C:\Users\EEE\AppData\Local\Microsoft\WindowsApps

c:\users\eee\appdata\roaming\python\python311\scripts
c:\users\eee\.local\bin
```

**Comment by manuvarkey** [comment]
@danyeaw Same error is shown in venv also
```

(python_env) PS C:\Users\EEE\Test> python test.py
Traceback (most recent call last):
  File "C:\Users\EEE\Test\test.py", line 3, in <module>
    gi.require_version("Gtk", "3.0")
  File "C:\Users\EEE\python_env\Lib\site-packages\gi\__init__.py", line 139, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

**Comment by danyeaw** [comment]
Did you check that your $env:LIB and $env:INCLUDE are set correctly?

**Comment by manuvarkey** [comment]
@danyeaw 

```
(python_env) PS C:\Users\EEE\test>  $env:LIB -split ';'
C:\gtk-build\gtk\x64\release\lib

(python_env) PS C:\Users\EEE\test>  $env:INCLUDE -split ';'
C:\gtk-build\gtk\x64\release\include
C:\gtk-build\gtk\x64\release\include\cairo
C:\gtk-build\gtk\x64\release\include\glib-2.0
C:\gtk-build\gtk\x64\release\include\gobject-introspection-1.0
C:\gtk-build\gtk\x64\release\lib\glib-2.0\include

(python_env) PS C:\Users\EEE\test>
```

**Comment by danyeaw** [comment]
@manuvarkey What command did you use to build gvsbuild? Have you tried rebuilding it from scratch with:
```
gvsbuild build --from-scratch --enable-gi --py-wheel gtk3 pygobject
```

**Comment by manuvarkey** [comment]
@danyeaw That solves it! Now it works fine both in regular and virtual environments even without running the following commands.
```
pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pygobject\dist\PyGObject*.whl)
pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pycairo\dist\pycairo*.whl)
```
I had built gtk3 stack with `gvsbuild build gtk3` initially and further built pygobject with `gvsbuild build --enable-gi --py-wheel gtk3 pygobject` which should have caused issues.

**Comment by danyeaw** [comment]
Nice, I'm glad you resolved it!
