### ISSUE TITLE
AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by doadin** [wingtk/gvsbuild#957]
Running 

`gvsbuild build --platform=x64 --vs-ver=17 --enable-gi --py-wheel --skip gtksourceview4,emeus,clutter gtk3-full pycairo pygobject lz4 enchant`

The same command I used like a year ago to build successfully I am now getting error:

`+--------------------- Traceback (most recent call last) ---------------------+
| C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\gvsbuild\bu |
| ild.py:419 in build                                                         |
|                                                                             |
|   416             pv = f"'{v}'" if type(v) is str else repr(v)              |
|   417             log.message_indent(f"'{co}': {pv}, ")                     |
|   418     builder = Builder(opts)                                           |
| > 419     builder.preprocess()                                              |
|   420                                                                       |
|   421     to_build = __get_projects_to_build(opts)                          |
|   422     if not to_build:                                                  |
|                                                                             |
| +-------------------------------- locals ---------------------------------+ |
| |        archives_download_dir = WindowsPath('C:/gtk-build/src')          | |
| |                    build_dir = WindowsPath('C:/gtk-build')              | |
| |                      builder = <gvsbuild.utils.builder.Builder object   | |
| |                                at 0x000002523[57](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:58)FDC00>                   | |
| |                  capture_out = False                                    | |
| |                   cargo_opts = None                                     | |
| |                   check_hash = False                                    | |
| |                        clean = False                                    | |
| |                  clean_built = False                                    | |
| |                configuration = <Configuration.debug_optimized:          | |
| |                                'debug-optimized'>                       | |
| |                        debug = False                                    | |
| |                         deps = True                                     | |
| |                    enable_gi = True                                     | |
| |                   export_dir = None                                     | |
| |                   fast_build = False                                    | |
| |            ffmpeg_enable_gpl = False                                    | |
| |                 from_scratch = False                                    | |
| |               git_expand_dir = None                                     | |
| |                   keep_going = False                                    | |
| |                   keep_tools = False                                    | |
| |                   log_single = False                                    | |
| |                     log_size = 0                                        | |
| |                     make_zip = False                                    | |
| |                 msbuild_opts = None                                     | |
| |                     msys_dir = None                                     | |
| |         net_target_framework = None                                     | |
| | net_target_framework_version = None                                     | |
| |                   ninja_opts = None                                     | |
| |                         opts = <gvsbuild.utils.base_project.Options     | |
| |                                object at 0x0000025235AC9FF0>            | |
| |                            p = 'enchant'                                | |
| |             patches_root_dir = WindowsPath('C:/hostedtoolcache/windows� | |
| |                     platform = <Platform.x[64](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:65): 'x64'>                    | |
| |                    print_out = False                                    | |
| |                     projects = [                                        | |
| |                                    'gtk3-full',                         | |
| |                                    'pycairo',                           | |
| |                                    'pygobject',                         | |
| |                                    'lz4',                               | |
| |                                    'enchant'                            | |
| |                                ]                                        | |
| |                    prop_file = WindowsPath('C:/hostedtoolcache/windows� | |
| |                     py_wheel = True                                     | |
| |                         skip = ['gtksourceview4,emeus,clutter']         | |
| |               tools_root_dir = None                                     | |
| |                      use_env = False                                    | |
| |                      verbose = False                                    | |
| |              vs_install_path = None                                     | |
| |                       vs_ver = <VsVer.vs2022: '17'>                     | |
| |                  win_sdk_ver = None                                     | |
| |                 zip_continue = False                                    | |
| +-------------------------------------------------------------------------+ |
|                                                                             |
| C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\gvsbuild\ut |
| ils\builder.py:470 in preprocess                                            |
|                                                                             |
|    4[67](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:68)                 proj.clean = True                                    |
|    4[68](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:69)                                                                      |
|    4[69](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:70)         for proj in Project.list_projects():                         |
| >  4[70](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:71)             self.__compute_deps(proj)                                |
|    4[71](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:72)             log.debug(f"{proj.name} => {[d.name for d in proj.all_de |
|    4[72](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:73)                                                                      |
|    4[73](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:74)     def __compute_deps(self, proj):                                  |
|                                                                             |
| +-------------------------------- locals ---------------------------------+ |
| | archive = 'go1.20.4.windows-amd64.zip'                                  | |
| |    proj = 'dev-shell'                                                   | |
| |    self = <gvsbuild.utils.builder.Builder object at 0x00000252357FDC00> | |
| |     url = 'https://go.dev/dl/go1.20.4.windows-amd64.zip'                | |
| +-------------------------------------------------------------------------+ |
|                                                                             |
| C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\gvsbuild\ut |
| ils\builder.py:482 in __compute_deps                                        |
|                                                                             |
|    4[79](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:80)             for p in dep.all_dependencies:                           |
|    4[80](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:81)                 deps.add(p)                                          |
|    4[81](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:82)             deps.add(dep)                                            |
| >  4[82](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:83)         proj.finalize_dep(self, deps)                                |
|    4[83](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:84)         proj.all_dependencies = deps                                 |
|    4[84](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:85)                                                                      |
|    4[85](https://github.com/doadin/gvsbuild-release/actions/runs/5136914567/jobs/9244287894#step:7:86)     def _drop_proj(self, drop_prj):                                  |
|                                                                             |
| +------------------------------- locals -------------------------------+    |
| |  dep = 'tools'                                                       |    |
| | deps = {                                                             |    |
| |            'cargo',                                                  |    |
| |            'cmake',                                                  |    |
| |            'go',                                                     |    |
| |            'meson',                                                  |    |
| |            'msys2',                                                  |    |
| |            'nasm',                                                   |    |
| |            'ninja',                                                  |    |
| |            'perl',                                                   |    |
| |            'tools'                                                   |    |
| |        }                                                             |    |
| |    p = 'perl'                                                        |    |
| | proj = 'dev-shell'                                                   |    |
| | self = <gvsbuild.utils.builder.Builder object at 0x00000252357FDC00> |    |
| +----------------------------------------------------------------------+    |
|                                                                             |
| C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\gvsbuild\pr |
| ojects\dev_shell.py:46 in finalize_dep                                      |
|                                                                             |
|   43                                                                        |
|   44     def finalize_dep(self, builder, deps):                             |
|   45         if builder.opts.skip:                                          |
| > 46             skip = builder.opts.skip.split(",")                        |
|   47             for s in skip:                                             |
|   48                 p = Project.get_project(s)                             |
|   49                 if p in deps:                                          |
|                                                                             |
| +-------------------------------- locals ---------------------------------+ |
| | builder = <gvsbuild.utils.builder.Builder object at 0x00000252357FDC00> | |
| |    deps = {                                                             | |
| |               'cargo',                                                  | |
| |               'cmake',                                                  | |
| |               'go',                                                     | |
| |               'meson',                                                  | |
| |               'msys2',                                                  | |
| |               'nasm',                                                   | |
| |               'ninja',                                                  | |
| |               'perl',                                                   | |
| |               'tools'                                                   | |
| |           }                                                             | |
| |    self = 'dev-shell'                                                   | |
| +-------------------------------------------------------------------------+ |
+-----------------------------------------------------------------------------+
AttributeError: 'list' object has no attribute 'split'`

**Comment by danyeaw** [comment]
Hi @doadin, try using spaces between the project names with no commas

**Comment by doadin** [comment]
@danyeaw Did not help. 

The build and workflow file:

https://github.com/doadin/gvsbuild-release/actions/runs/5140393185/jobs/9251807193 . https://github.com/doadin/gvsbuild-release/actions/runs/5140393185/workflow .

**Comment by doadin** [comment]
Thanks for this, it now builds further but I am running into another issue.
https://github.com/doadin/gvsbuild-release/actions/runs/5149056649/jobs/9271570707

**Comment by doadin** [comment]
I should probabbly make a new Issue for this but I see, https://github.com/mesonbuild/meson/blob/master/mesonbuild/compilers/c.py#L487 that in the log and
https://github.com/wingtk/gvsbuild/commit/53753e7df5ab23087b7f75286f4ebfdaba9e3362

Maybe theres was something missing in changing to meson?

**Comment by danyeaw** [comment]
Hi @doadin, you need to move the Git/bin folder out of the way that is on the GitHub Actions runner:

```
      - name: GTK binaries move git binary
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          move "C:\Program Files\Git\usr\bin" "C:\Program Files\Git\usr\notbin"
          move "C:\Program Files\Git\bin" "C:\Program Files\Git\notbin"
```

**Comment by doadin** [comment]
@danyeaw ok, I had:

`
      - name: Move git binary
        # Temporarily move preinstalled git to prevent errors related to cygwin.
        run: Rename-Item "C:\Program Files\Git\usr\bin" notbin
`

so was missing the other part I guess. Thanks! testing now.

**Comment by doadin** [comment]
@danyeaw Made it a lot further but still error: https://github.com/doadin/gvsbuild-release/actions/runs/5150698778/jobs/9275134361

**Comment by danyeaw** [comment]
@doadin It looks like Cogl is failing. I saw you were skipping Clutter, do you need Cogl?

**Comment by doadin** [comment]
@danyeaw Im just building gtk for use with deluge, I dont think it uses either. I was just trying to update my build, is this a build issue for gvsbuild or cogl?

**Comment by danyeaw** [comment]
It is a cogl issue. Our CI, build the following things:

```
gvsbuild build --ninja-opts -j2 gtk3 gtksourceview4 graphene glib-networking
gvsbuild build --ninja-opts -j2 --enable-gi cairo gtk4 libadwaita gtksourceview5 gobject-introspection adwaita-icon-theme hicolor-icon-theme
```

**Comment by doadin** [comment]
@danyeaw ah, and the link to cogl goes to a gitlab that is "Archived" and hasnt been updated in 2 years so I guess thats never getting fixed.

**Comment by doadin** [comment]
@danyeaw I am probabbly just missing something but I tried to add to skip and it did NOT skip.

**Comment by doadin** [comment]
https://github.com/doadin/gvsbuild-release/actions/runs/5155632019/jobs/9285556319

**Comment by danyeaw** [comment]
It looks like it is not possible to pass a list of optional values in with Typer which is the library we are using: https://github.com/tiangolo/typer/issues/554

It is possible to call it each time though it looks like, and I verified that it dropped both:
```
> gvsbuild build --skip cogl --skip gtksourceview4 gtk3-full
```

Or you could also just explicitly call out the libraries you want to build and avoid using the gtk3-full group. I'll update the help menu and README to make this clearer.

**Comment by doadin** [comment]
@danyeaw ok I will test this. Thank you, helping me along here.  All I know is the build process was successful Jun 13, 2022. I tried to re-run same github action this week and it failed. SO what happened between then and now and why I am just trying. :)

**Comment by doadin** [comment]
@danyeaw yea the  multiple skips seems to work but got another error for librsvg. Probabbly should just choose what part I need instead of full, would probabbly be easier.

**Comment by danyeaw** [comment]
Ya, I ran in to that error with librsvg today as well. I submitted an issue upstream: https://gitlab.gnome.org/GNOME/librsvg/-/issues/968

**Comment by doadin** [comment]
https://github.com/doadin/gvsbuild-release/actions/runs/5161905965/jobs/9299247177

`

Need python for x86, but found x86_64

cairo\meson.build:35:20: ERROR: Python dependency not found

A full log can be found at C:\gtk-build\build\Win32\release\pycairo\_gvsbuild-meson\meson-logs\meson-log.txt
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x86\lib\site-packages\gvsbuild\utils\builder.py", line 525, in build
    if self.__build_one(p):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x86\lib\site-packages\gvsbuild\utils\builder.py", line 661, in __build_one
    skip_deps = proj.build()
  File "C:\hostedtoolcache\windows\Python\3.10.11\x86\lib\site-packages\gvsbuild\projects\pycairo.py", line 38, in build
    Meson.build(self)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x86\lib\site-packages\gvsbuild\utils\base_builders.py", line 49, in build
    self._setup_meson_and_ninja(ninja_build, meson_params, add_path)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x86\lib\site-packages\gvsbuild\utils\base_builders.py", line 81, in _setup_meson_and_ninja
    self.exec_vs(cmd, add_path=add_path)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x86\lib\site-packages\gvsbuild\utils\base_project.py", line 195, in exec_vs
    self.builder.exec_vs(
  File "C:\hostedtoolcache\windows\Python\3.10.11\x86\lib\site-packages\gvsbuild\utils\builder.py", line 935, in exec_vs
    self.__execute(
  File "C:\hostedtoolcache\windows\Python\3.10.11\x86\lib\site-packages\gvsbuild\utils\builder.py", line 1037, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x86\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\hostedtoolcache\windows\Python\3.10.11\x86\python.exe C:\gtk-build\tools\meson-1.1.1\meson.py setup C:\gtk-build\build\Win32\release\pycairo C:\gtk-build\build\Win32\release\pycairo\_gvsbuild-meson --prefix C:\gtk-build\gtk\Win32\release --buildtype release' returned non-zero exit status 1.
Error: pycairo build failed

`

**Comment by doadin** [comment]
@danyeaw so i started reducing down the command trying to see where this non-project is maybe getting put in and it seems like its just a problem parseing the skips maybe? with the above command it said cant find project c . Once I got it down to just 

gvsbuild build --skip gtksourceview4 --skip emeus --configuration=release --platform=x64 --vs-ver=16 --enable-gi --py-wheel gtk3

It says can not find project e . Notice the last skips don't start with c and now start with e .

**Comment by doadin** [comment]
@danyeaw sorry last @ gvsbuild build --platform=x64 --vs-ver=16 --enable-gi --py-wheel gtk3 pycairo pygobject lz4 enchant works so fairly positive I have narrowed it down to the skip option is still broke but in a different way :(

**Comment by doadin** [comment]
Unfortunately while the build gets far without skips, still fails:
https://github.com/doadin/gvsbuild-release/actions/runs/5205711137/jobs/9391460212

**Comment by danyeaw** [comment]
Hi @doadin, for the last one it looks like you are trying to build with win32, but meson is finding x64 version of Python.

It may be possible to pass in the path of python as a meson option to pycairo using the `python -m build --config-setting -Dpython=C:\path\to\python`. However, it may just be easier to remove versions of Python you don't want to use off your Path in CI.

**Comment by doadin** [comment]
@danyeaw yea I am not sure what the path looks like I am using setup-python action to manage python. Which seems like it puts the right python in place from my tests. But im not sure.

**Comment by doadin** [comment]
@danyeaw I created just a simple action for testing which is just the same action file but without the gvsbuild option and added a step to print python version being called by python on cmd and print path and I only see python of the correct bit in each job. SO the only thing I could think of is something in the build process modifying it? https://github.com/doadin/pythonaction/actions/runs/5217369432/jobs/9417133444

**Comment by doadin** [comment]
I would think https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-update-environment-flag would handle this.

**Comment by danyeaw** [comment]
The runner comes with Python 3.9 installed before you run setup-python. https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#language-and-runtime

This looks like a limitation of meson to me. If there are multiple versions of Python, it may not choose the Python that meson was run with. Setup-python looks like it is changing the default python, but it doesn't remove other versions on the path.

**Comment by doadin** [comment]
@danyeaw yea in the trace you can see it is being run from a different python than meson "found" and just running a python command you can see it running with the python version added by setup-python action. Im not sure how not remove the others from path but Ill figure it out. Thanks for the other fix!

**Comment by doadin** [comment]
@danyeaw well looks like removing all other python from path did not work. 
https://github.com/doadin/gvsbuild-release/actions/runs/5219121735/jobs/9420597840
