### ISSUE TITLE
Error when using relative directory with --build-dir option

### ISSUE THREAD

**Issue by g40** [wingtk/gvsbuild#976]
Thanks for this project. Looks like it might be extremely useful. 

Trying to build I get the error below. Not sure if it is relevant but the root gvsbuild folder contains the correct meson folder with the missing `meson.py`:

```
R:\src\libs\gvsbuild>ls -a
.  ..  build  export  gtk  logs  src  tools
R:\src\libs\gvsbuild>ls -a tools
.  ..  meson-1.1.1  ninja-1.11.1
```

As reported when building:

```
gvsbuild build --from-scratch --build-dir . --msys-dir  r:\apps\msys64 --configuration debug gtk3
Build type is Configuration.debug
Cleanup build directories
Removing working/building dir (.\build\x64\debug)
Removing destination dir (.\gtk\x64\debug)
Removing git expand dir (src\git-exp)
Removing tools dir (tools)
Cleaning up the build environment
Checking msys tool
Using r:\apps\msys64 for msys installation
Checking Msvc tool

Visual Studio installation(s) found:
    Visual Studio Community 2022 @ r:\vs2022

Using Visual Studio at r:\vs2022
Downloading packages
Building project ninja (1.11.1)
Building project meson (1.1.1)
(tar) Exporting pkgconf
Building project pkgconf (1.9.5)
(Stripping trailing CRs from patch; use --binary to disable.)
patching file libpkgconf/bsdstubs.c
Hunk #1 succeeded at 23 with fuzz 1.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file libpkgconf/libpkgconf.h
R:\apps\python\python.exe: can't open file 'R:\\src\\libs\\gvsbuild\\build\\x64\\debug\\pkgconf\\tools\\meson-1.1.1\\meson.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "R:\apps\python\Lib\site-packages\gvsbuild\utils\builder.py", line 525, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "R:\apps\python\Lib\site-packages\gvsbuild\utils\builder.py", line 661, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "R:\apps\python\Lib\site-packages\gvsbuild\projects\pkgconf.py", line 39, in build
    Meson.build(self)
  File "R:\apps\python\Lib\site-packages\gvsbuild\utils\base_builders.py", line 49, in build
    self._setup_meson_and_ninja(ninja_build, meson_params, add_path)
  File "R:\apps\python\Lib\site-packages\gvsbuild\utils\base_builders.py", line 81, in _setup_meson_and_ninja
    self.exec_vs(cmd, add_path=add_path)
  File "R:\apps\python\Lib\site-packages\gvsbuild\utils\base_project.py", line 195, in exec_vs
    self.builder.exec_vs(
  File "R:\apps\python\Lib\site-packages\gvsbuild\utils\builder.py", line 935, in exec_vs
    self.__execute(
  File "R:\apps\python\Lib\site-packages\gvsbuild\utils\builder.py", line 1039, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "R:\apps\python\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'R:\apps\python\python.exe tools\meson-1.1.1\meson.py setup .\build\x64\debug\pkgconf .\build\x64\debug\pkgconf\_gvsbuild-meson --prefix .\gtk\x64\debug -Dtests=disabled --buildtype debug' returned non-zero exit status 2.
Error: pkgconf build failed
```

**Comment by g40** [comment]
So the Ninja problem is **resolved** by passing a full path to the source directory to gvsbuild. 

Not sure if this is a bug or intentional?

```
>gvsbuild build --from-scratch --build-dir r:\src\libs\gvsbuild --msys-dir  r:\apps\msys64 --configuration debug gtk3
```

**Comment by tjwilli58** [comment]
I'm also using `--build-dir` to build in a place different than the default of `C:\gtk-build`. I'm using a full path for my location.

I'm assuming your current directory is `R:\src\libs\gvsbuild`?  I'm curious to see what would happen if you tried `--build-dir .\ `, instead of `--build-dir .`

**Comment by tjwilli58** [comment]
Maybe even `--build-dir ..\gvsbuild`

**Comment by g40** [comment]
@tjwilli58 Fails in the exactly the same way. No matter, just needs to be  clarified.

**Comment by danyeaw** [comment]
@g40 This sounds like an issue we should address if relative paths don't work properly. I'm going to reopen the issue.
