### ISSUE TITLE
gst-python, pycairo, pygobject builds, but _gi not found.

### ISSUE THREAD

**Issue by tjwilli58** [wingtk/gvsbuild#981]
I used gvsbuild  to successfully build pycairo, pygobject, gst-python. The problem is that when I try to `import gi` from a python prompt as a test, I get

```
PS C:\Users\Tim> python
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\gstreamer\gtk-build\gtk\x64\release\lib\site-packages\gi\__init__.py", line 47, in <module>
    from . import _gi
ImportError: DLL load failed while importing _gi: The specified module could not be found.
>>>
```
I set PYTHONPATH before invoking python so the site-packages created from the gvsbuiild can be found.  I know about needing to use `os.add_dll_directory(path)` because of the change in python3.8, but that is only for finding DLLs 
https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew 
Only the system paths, the **directory containing the DLL or PYD file**, and directories added with [add_dll_directory()](https://docs.python.org/3/library/os.html#os.add_dll_directory) are searched for load-time dependencies.

In site-packages, the `gi` folder exists, but for `_gi`, the DLLs are either misnamed, or in the wrong format.

```
PS D:\gstreamer\gtk-build\gtk\x64\release\lib\site-packages> dir .\gi


    Directory: D:\gstreamer\gtk-build\gtk\x64\release\lib\site-packages\gi


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         6/21/2023   7:44 AM                overrides
d-----         6/21/2023   7:32 AM                repository
d-----         6/21/2023   5:26 PM                __pycache__
-a----         8/25/2019   1:33 PM           6688 docstring.py
-a----         3/19/2023   6:28 AM           5498 importer.py
-a----         3/19/2023   6:28 AM           9856 module.py
-a----          5/6/2020  12:48 PM            727 pygtkcompat.py
-a----          5/6/2020  12:48 PM          13543 types.py
-a----        12/30/2019   6:13 AM           1969 _constants.py
-a----         11/6/2020  10:06 AM           2082 _error.py
-a----         6/21/2023   7:32 AM           1940 _gi.cp311-win_amd64.lib
-a----         6/21/2023   7:32 AM        2363392 _gi.cp311-win_amd64.pdb
-a----         6/21/2023   7:32 AM         316928 _gi.cp311-win_amd64.pyd
-a----         6/21/2023   7:32 AM           2048 _gi_cairo.cp311-win_amd64.lib
-a----         6/21/2023   7:32 AM         602112 _gi_cairo.cp311-win_amd64.pdb
-a----         6/21/2023   7:32 AM          23552 _gi_cairo.cp311-win_amd64.pyd
-a----         3/19/2023   6:28 AM          10193 _gtktemplate.py
-a----         11/6/2020  10:06 AM          13140 _option.py
-a----          5/6/2020  12:48 PM           7615 _ossighelper.py
-a----          5/6/2020  12:48 PM          14163 _propertyhelper.py
-a----        12/30/2019   6:13 AM           9303 _signalhelper.py
-a----         6/21/2023   7:31 AM           6258 __init__.py

```
I'm no don't really know about all the different file formats, but for an older version I have of gstreamer (1.17.2) and pygobject, (using python3.7), the corresponding folder looks like this. 

```
PS D:\gstreamer\1.17.2\x86_64\lib\python3.7\site-packages> dir gi


    Directory: D:\gstreamer\1.17.2\x86_64\lib\python3.7\site-packages\gi


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         7/31/2020  11:37 AM                overrides
d-----         7/15/2020   7:57 AM                repository
d-----        12/26/2022   9:59 PM                __pycache__
-a----         1/20/2019   4:52 AM           6688 docstring.py
-a----         1/20/2019   4:52 AM           5280 importer.py
-a----         1/20/2019   4:52 AM           9705 module.py
-a----         1/20/2019   4:52 AM            766 pygtkcompat.py
-a----         1/20/2019   4:52 AM          14330 types.py
-a----         1/20/2019   4:52 AM           1493 _compat.py
-a----         1/20/2019   4:52 AM           1969 _constants.py
-a----         1/20/2019   4:52 AM           2082 _error.py
-a----         7/13/2020   3:16 PM           1384 _gi.dll.a
-a----         7/13/2020   3:16 PM        2856525 _gi.pyd
-a----         7/13/2020   3:16 PM           1456 _gi_cairo.dll.a
-a----         7/13/2020   3:16 PM         454301 _gi_cairo.pyd
-a----         1/20/2019   4:52 AM           7835 _gtktemplate.py
-a----         1/20/2019   4:52 AM          13192 _option.py
-a----         1/20/2019   4:52 AM           8083 _ossighelper.py
-a----         1/20/2019   4:52 AM          14331 _propertyhelper.py
-a----         1/20/2019   4:52 AM           9303 _signalhelper.py
-a----         1/20/2019   4:52 AM           5894 __init__.py
```
Can gvsbuild create DLLs instead? I tried to just rename these files without the `cp311-win_amd64`, but that didn't work.

Also, when the build is done, pycairo and pygobject pip installed to my local site-packages, but I can't uninstall them if the python used was not installed as admin.

**Comment by danyeaw** [comment]
Hi @tjwilli58!
Did you build the wheels for pygobject and pycairo with the `--wheel` option?

**Comment by tjwilli58** [comment]
Yes, but pip installing them or not didn’t help with the import gi.

**Comment by danyeaw** [comment]
There are examples from other projects on how to set up a development environment like https://docs.gaphor.org/en/latest/windows.html

If you need help, please provide a minimum reproducible example with the steps you took.

**Comment by tjwilli58** [comment]
For just testing if I can import gi, I don’t need to either.

**Comment by tjwilli58** [comment]
What is the obsession with doing everything as Administrator?

**Comment by tjwilli58** [comment]
Hi @danyeaw , 
I figured it out. I hadn't set my PATH, LIB, INCLUDE **before** building. Once I did that and rebuilt `gst-python` I could `import gi` from python

(Actually, it may be that I just needed to set my PATH in addition to PYTHONPATH)
```
PS C:\Users\Tim> $env:path = "D:\gstreamer\gtk-build\gtk\x64\release\bin;" + $env:path
PS C:\Users\Tim> $env:pythonpath="D:\gstreamer\gtk-build\gtk\x64\release\lib\site-packages\"
```
```
PS C:\Users\Tim> python
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Gst','1.0')
>>> from gi.repository import Gst
>>>
```

**Comment by tjwilli58** [comment]
Hi @danyeaw ,

So I rebuilt everything without setting PATH, LIB, INCLUDE. After putting the bin folder for gst-*.exe in my PATH, I could `import gi` in python.

I also didn't use `--py-wheel` as a test. I did build `gst-python` with `--enable-gi` though.

However, testing the pipline
```
(.venv311) PS D:\GitClones\gvsbuild> gst-launch-1.0.exe mfvideosrc ! autovideosink

** (gst-launch-1.0:15964): CRITICAL **: 20:06:56.657: pygobject initialization failed
Use Windows high-resolution clock, precision: 1 ms
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Got context from element 'autovideosink0': gst.d3d11.device.handle=context, device=(GstD3D11Device)"\(GstD3D11Device\)\ d3d11device5", adapter=(uint)0, adapter-luid=(gint64)69569, device-id=(uint)6044, vendor-id=(uint)4318, hardware=(boolean)true, description=(string)"NVIDIA\ GeForce\ 940MX";
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
WARNING: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstD3D11VideoSink:autovideosink0-actual-sink-d3d11video: Pipeline construction is invalid, please add queues.
Additional debug info:
../libs/gst/base/gstbasesink.c(1258): gst_base_sink_query_latency (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstD3D11VideoSink:autovideosink0-actual-sink-d3d11video:
Not enough buffering available for  the processing deadline of 0:00:00.015000000, add enough queues to buffer  0:00:00.013760900 additional data. Shortening processing latency to 0:00:00.001239100.
WARNING: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstD3D11VideoSink:autovideosink0-actual-sink-d3d11video: Pipeline construction is invalid, please add queues.
Additional debug info:
../libs/gst/base/gstbasesink.c(1258): gst_base_sink_query_latency (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstD3D11VideoSink:autovideosink0-actual-sink-d3d11video:
Not enough buffering available for  the processing deadline of 0:00:00.015000000, add enough queues to buffer  0:00:00.013760900 additional data. Shortening processing latency to 0:00:00.001239100.
handling interrupt.9.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:12.053831000
Setting pipeline to NULL ...
Freeing pipeline ...
(.venv311) PS D:\GitClones\gvsbuild>
```

`pygobject` failed initialization, but the pipeline did work and displayed my webcam.  I then `pip install`ed pycairo, pygobject, and still got that message.

**Comment by tjwilli58** [comment]
Rebuilt `gst-python` with PATH, LIB, INCLUDE modified.  Still got message
```
** (gst-launch-1.0:75716): CRITICAL **: 21:42:05.070: pygobject initialization failed
```

**Comment by tjwilli58** [comment]
`gst-plugins-bad` needs to be built with `--enable-gi`.
