### ISSUE TITLE
Error: harfbuzz build failed

### ISSUE THREAD

**Issue by SomnathS09** [wingtk/gvsbuild#995]
Using Visual Studio 2022

```
Found ninja-1.11.1 at C:\gtk-build\tools\ninja-1.11.1\ninja.EXE
[26/245] Compiling C++ object src/harfbuzz.dll.p/hb-ot-font.cc.obj
FAILED: src/harfbuzz.dll.p/hb-ot-font.cc.obj
"cl" "-Isrc\harfbuzz.dll.p" "-Isrc" "-I..\src" "-I." "-I.." "-IC:/gtk-build/gtk/x64/release/bin/../include/freetype2" "-IC:/gtk-build/gtk/x64/release/bin/../include/libpng16" "-IC:/gtk-build/gtk/x64/release/bin/../include" "-IC:/gtk-build/gtk/x64/release/bin/../include/glib-2.0" "-IC:/gtk-build/gtk/x64/release/bin/../lib/glib-2.0/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/Zc:__cplusplus" "/W2" "/EHs-c-" "/GR-" "/std:c++14" "/permissive-" "/O2" "/Zi" "/wd4244" "/utf-8" "-DHAVE_CONFIG_H" "-DHB_DLL_EXPORT" "/Fdsrc\harfbuzz.dll.p\hb-ot-font.cc.pdb" /Fosrc/harfbuzz.dll.p/hb-ot-font.cc.obj "/c" ../src/hb-ot-font.cc
C:\gtk-build\build\x64\release\harfbuzz\src\hb-sanitize.hh(148) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
  cl!RaiseException()+0x69
  cl!RaiseException()+0x69
  cl!InvokeCompilerPassW()+0xa442f
  cl!InvokeCompilerPassW()+0xda8d3

[31/245] Compiling C++ object src/harfbuzz.dll.p/hb-ot-layout.cc.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\mypc\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\utils\builder.py", line 525, in build
    if self.__build_one(p):
  File "C:\Users\mypc\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\utils\builder.py", line 661, in __build_one     
    skip_deps = proj.build()
  File "C:\Users\mypc\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\projects\harfbuzz.py", line 42, in build        
    Meson.build(self)
  File "C:\Users\mypc\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\utils\base_builders.py", line 58, in build      
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "C:\Users\mypc\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\utils\builder.py", line 983, in exec_ninja      
    self.__execute(
  File "C:\Users\mypc\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\utils\builder.py", line 1039, in __execute      
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: harfbuzz build failed
```

**Comment by danyeaw** [comment]
@SomnathS09 Thanks for submitting this. Could you please provide more information about what your setup is what command you ran?

**Comment by SomnathS09** [comment]
Closing it as running build `gvsbuild build --enable-gi --py-wheel gtk4 pygobject` second time worked.
